"""Curated first-grade sequences for the six subjects that complete the level."""
from __future__ import annotations


def _spec(topic: str, misconception: str, materials: str, example: str, *steps: str) -> dict:
    return {"topic": topic, "misconception": misconception, "materials": materials, "example": example, "steps": steps}


ATTITUDES = {
    "MU": (
        ("de Actitud MU01 OAA A", "curiosidad y disfrute de los sonidos y la música"),
        ("de Actitud MU01 OAA B", "confianza al compartir música"),
        ("de Actitud MU01 OAA C", "comunicación de percepciones e ideas mediante la música"),
        ("de Actitud MU01 OAA D", "valoración de estilos y expresiones musicales diversas"),
        ("de Actitud MU01 OAA E", "reconocimiento de la dimensión espiritual y trascendente de la música"),
        ("de Actitud MU01 OAA F", "creatividad mediante juego, imaginación y experimentación"),
        ("de Actitud MU01 OAA G", "colaboración respetuosa en audición, creación e interpretación"),
    ),
    "EF": (
        ("de Actitud EF01 OAA A", "valoración de la actividad física para la salud"),
        ("de Actitud EF01 OAA B", "disposición a mejorar y practicar regularmente"),
        ("de Actitud EF01 OAA C", "confianza corporal sin comparación competitiva"),
        ("de Actitud EF01 OAA D", "participación activa con alternativas accesibles"),
        ("de Actitud EF01 OAA E", "participación equitativa de hombres y mujeres"),
        ("de Actitud EF01 OAA F", "respeto por la diversidad física"),
        ("de Actitud EF01 OAA G", "colaboración y aceptación de retroalimentación"),
        ("de Actitud EF01 OAA H", "esfuerzo personal, superación y perseverancia"),
    ),
    "TE": (
        ("de Actitud TE01 OAA A", "curiosidad por usos, funcionamiento y materiales"),
        ("de Actitud TE01 OAA B", "creatividad y pensamiento divergente"),
        ("de Actitud TE01 OAA C", "iniciativa en diseño y creación"),
        ("de Actitud TE01 OAA D", "colaboración y aceptación de consejos"),
        ("de Actitud TE01 OAA E", "uso seguro y responsable de TIC y respeto de autoría"),
    ),
    "EN": (
        ("de Actitud EN01 OAA A", "interés por el contexto propio y el entorno"),
        ("de Actitud EN01 OAA B", "confianza progresiva para aprender otro idioma"),
        ("de Actitud EN01 OAA C", "curiosidad y respeto ante otras realidades y culturas"),
        ("de Actitud EN01 OAA D", "trabajo cooperativo para comunicarse"),
    ),
    "LC": (
        ("de Actitud LC01 OAA A", "pertenencia a la red de la vida desde lengua y cultura"),
        ("de Actitud LC01 OAA B", "interculturalidad basada en aprecio y comprensión mutua"),
        ("de Actitud LC01 OAA C", "respeto, reciprocidad y cuidado del entorno"),
        ("de Actitud LC01 OAA D", "rigurosidad, oralidad y vínculo con la enseñanza ancestral"),
    ),
}


SEQUENCES = {
    "MU01 OA 01": _spec("Cualidades del sonido y elementos musicales", "llama fuerte a todo sonido agudo o confunde pulso con ritmo", "objetos sonoros, instrumentos, tarjetas gráficas y audios breves con procedencia", "Contrastar un cascabel agudo y corto con un tambor grave y largo; luego caminar un pulso mientras las palmas ejecutan un patrón", "Altura, timbre, intensidad y duración|distinguiré cualidades sin mezclarlas", "Pulso, acento y patrón|mantendré un pulso y reconoceré lo que cambia", "Secciones que regresan|identificaré contraste y repetición", "Partitura no convencional|representaré lo escuchado con símbolos explicables"),
    "MU01 OA 02": _spec("Sensaciones, emociones e ideas sugeridas por la música", "declara que una música tiene una emoción única y correcta", "audios contrastantes con procedencia, telas, hojas y pequeña percusión", "Escuchar dos fragmentos sin título y relacionar cada respuesta con intensidad, timbre, tempo o silencio, no con una respuesta impuesta", "Escucha corporal|mostraré con movimiento un cambio que oigo", "Palabras para una impresión|describiré sensación y pista sonora", "Respuesta visual o musical|traduciré una idea a otro medio", "Interpretaciones distintas|compararé respuestas sin decidir una única correcta"),
    "MU01 OA 03": _spec("Escucha abundante de músicas de diversos contextos", "reduce una tradición a una pieza o juzga estilos como superiores", "selección anual trazable de músicas breves, mapa, fichas de escucha y parlante", "Comparar una ronda local, una pieza instrumental escrita, una expresión de pueblo originario validada y una canción popular infantil, nombrando contexto y rasgos audibles", "Preparar una escucha atenta|anticiparé qué observar sin conocer la respuesta", "Tradición oral|reconoceré participación, repetición y contexto", "Tradición escrita|describiré instrumentos, voces y secciones", "Música popular|identificaré pulso, timbre y función", "Bitácora de repertorio|compararé músicas y registraré límites de mi información"),
    "MU01 OA 04": _spec("Canto al unísono y percusión", "grita para cantar fuerte o acelera al tocar en grupo", "canción apropiada, instrumentos de percusión, objetos sonoros y señal de dirección", "Cantar una frase por eco con respiración cómoda y acompañarla con un ostinato de dos sonidos que no tape las voces", "Voz cuidada y afinación compartida|cantaré por eco sin forzar", "Pulso común|entraré y terminaré con una señal", "Acompañamiento de percusión|mantendré un patrón sin acelerar", "Interpretación conjunta|equilibraré voz, instrumento y escucha"),
    "MU01 OA 05": _spec("Exploración e improvisación de ideas musicales", "confunde improvisar con producir ruido continuo sin escuchar", "voz, pequeña percusión, objetos seguros, tarjetas de cualidades y silencios", "Crear una respuesta de cuatro pulsos a una pregunta musical, conservando una regla —solo sonidos cortos— e incluyendo silencio", "Explorar una fuente sonora|descubriré tres posibilidades controladas", "Pregunta y respuesta|improvisaré una idea breve que escucha a otra", "Reglas que abren creatividad|variaré una cualidad manteniendo un límite", "Miniatura musical|organizaré inicio, contraste y cierre"),
    "MU01 OA 06": _spec("Presentación de trabajos musicales", "evalúa a la persona o busca perfección antes de compartir", "trabajos musicales del curso, espacio delimitado, pauta de escucha y registro opcional", "Ensayar una pieza breve con roles de entrada, pulso y cierre; recibir una observación audible y repetir solo el tramo que necesita ajuste", "Elegir qué comunicar|definiré propósito y audiencia", "Preparar roles y señales|coordinaré inicio, desarrollo y final", "Ensayo con evidencia|mejoraré un aspecto audible", "Presentar y conversar|compartiré música y responderé una pregunta respetuosa"),
    "MU01 OA 07": _spec("Experiencias musicales y sonoras de la vida cotidiana", "enumera gustos sin describir dónde, cuándo o para qué aparece la música", "mapa sonoro, tarjetas de rutinas, grabación opcional sin datos y bitácora", "Reconstruir el paisaje sonoro de una mañana —alarma, tránsito, voces, canción— y distinguir sonido, música, contexto y significado personal", "Mapa de sonidos cotidianos|localizaré sonidos de una rutina", "Música y ocasión|relacionaré una experiencia con su función", "Memoria sonora cuidada|describiré una experiencia sin exponer datos privados", "Autobiografía musical breve|comunicaré una relación personal con evidencia sonora"),

    "EF01 OA 01": _spec("Locomoción, manipulación y estabilidad", "prioriza velocidad o resultado sobre control y seguridad", "conos, líneas, balones blandos, colchonetas y marcas de distancia", "Circuito: caminar-correr y detenerse en equilibrio, saltar dos pies sobre líneas, lanzar a un compañero y rodar con espacio seguro", "Locomoción con control|alternaré caminar, correr y detenerme", "Saltos y aterrizajes|saltaré con dos pies y caeré estable", "Lanzar y recibir|ajustaré fuerza y manos a la trayectoria", "Giros, rodadas y suspensiones|mantendré control y distancia", "Circuito combinado|enlazaré habilidades sin perder seguridad"),
    "EF01 OA 02": _spec("Relaciones espaciales y temporales en el movimiento", "memoriza derecha e izquierda sin ajustar el cuerpo a objetos o compañeros", "flechas, aros, conos, pañuelos y música con tempo contrastante", "Moverse a la derecha de un cono, pasar entre dos aros y llegar después de una señal; repetir lento y rápido sin chocar", "Mi cuerpo como referencia|distinguiré derecha, izquierda, arriba y abajo", "Objeto y espacio|me ubicaré dentro, fuera, entre y al lado", "Compañero y distancia|ajustaré delante, detrás, cerca y lejos", "Antes, durante y después|responderé a una secuencia de señales", "Rápido y lento con control|cambiaré velocidad conservando trayectoria"),
    "EF01 OA 03": _spec("Juegos con oposición y colaboración", "cree que jugar bien equivale a ganar o eliminar a otros", "petos, pañuelos, balones blandos, conos y tarjetas de reglas", "Comparar una persecución individual, un traslado cooperativo y un juego de oposición donde recuperar el objeto no elimina a nadie", "Jugar sin oposición|seguiré reglas y cuidaré el espacio", "Colaborar para una meta|coordinaré acciones con otros", "Oposición segura|anticiparé sin empujar ni bloquear peligrosamente", "Cambiar y explicar una regla|mejoraré participación y desafío"),
    "EF01 OA 04": _spec("Habilidades motrices en entornos diversos", "repite el mismo movimiento sin leer superficie, límites o riesgos", "patio y espacio alternativo, tizas, conos, cuerdas y plano simple", "Comparar caminar una línea lisa, rodear árboles o marcas y desplazarse sobre arena simulada, eligiendo apoyo y velocidad", "Leer el entorno|identificaré superficie, límites y riesgos", "Adaptar locomoción|cambiaré paso y velocidad según el lugar", "Manipular en otro espacio|ajustaré fuerza y dirección", "Ruta segura|planificaré y ejecutaré un recorrido"),
    "EF01 OA 05": _spec("Expresión corporal de sensaciones, ideas y emociones", "imita una pose estereotipada y supone que una emoción tiene un solo movimiento", "música instrumental, tarjetas abstractas, telas y espacio personal delimitado", "Transformar la idea de liviano a pesado usando nivel, energía, pausa y dirección, sin pedir experiencias íntimas", "Espacio personal y niveles|variaré tamaño y altura con control", "Ritmo y energía|cambiaré movimiento según un pulso", "Una idea en movimiento|crearé una frase corporal no literal", "Composición compartida|uniré propuestas respetando distintas expresiones"),
    "EF01 OA 06": _spec("Actividad moderada a vigorosa mediante juegos y circuitos", "confunde intensidad con competir al máximo o ignorar señales corporales", "conos, cuerda, aros, cronómetro docente y escala del habla", "Completar estaciones de desplazamiento continuo y usar la prueba del habla para distinguir intensidad moderada de vigorosa", "Activar progresivamente|aumentaré movimiento sin partir al máximo", "Circuito continuo|sostendré actividad moderada con técnica", "Intervalos de juego|reconoceré un tramo vigoroso y recuperaré", "Regular el esfuerzo|ajustaré intensidad usando señales corporales"),
    "EF01 OA 07": _spec("Actividad física cotidiana y juegos tradicionales", "piensa que solo el deporte formal cuenta como actividad física", "selección contextualizada de juegos, cuerdas, tizas y registro semanal no competitivo", "Practicar una ronda, saltos de cuerda adaptados y una persecución tradicional explicando reglas, procedencia disponible y opciones de acceso", "Moverse en la rutina|identificaré oportunidades cotidianas", "Juego tradicional contextualizado|aprenderé reglas y procedencia", "Variar para incluir|adaptaré espacio, tiempo o implemento", "Plan semanal realista|elegiré prácticas variadas y seguras"),
    "EF01 OA 08": _spec("Sensaciones y respuestas corporales al ejercicio", "interpreta sudor o respiración rápida como daño automático o ignora dolor y mareo", "silueta, escala del habla, tarjetas de señales y agua disponible", "Comparar pulso, respiración, temperatura y facilidad para hablar antes y después de un juego breve, distinguiendo esfuerzo esperable de señal de detención", "Antes de moverme|registraré cómo está mi cuerpo", "Cambios durante el esfuerzo|notaré respiración, calor y habla", "Recuperación|observaré qué vuelve gradualmente", "Señales para regular o detener|tomaré una decisión de autocuidado"),
    "EF01 OA 09": _spec("Higiene, postura, alimentación y vida saludable", "trata el hábito como regla aislada o responsabiliza moralmente por recursos familiares", "tarjetas de rutinas, mochila liviana, agua, jabón y colaciones ilustradas", "Resolver casos: manos sucias tras el patio, mochila mal ajustada y colación disponible, proponiendo una acción posible sin juzgar hogares", "Higiene después de moverse|secuenciaré lavado y cuidado personal", "Postura y carga|ajustaré una posición sin rigidez", "Agua y colación|reconoceré opciones disponibles que apoyan actividad", "Rutina antes y después|ordenaré acciones de autocuidado", "Decidir con contexto|propondré una alternativa posible y respetuosa"),
    "EF01 OA 10": _spec("Trabajo en equipo y roles motrices", "asocia liderazgo con mandar o deja siempre el material a la misma persona", "material de juego, tarjetas rotativas de roles y pauta de colaboración", "Realizar un desafío de transporte con roles de organización, ejecución, cuidado de material y observación que rotan", "Un equipo necesita acuerdos|definiré una meta y escucharé", "Roles que rotan|cumpliré una responsabilidad sin jerarquizar", "Consejo útil|daré y recibiré retroalimentación concreta", "Desafío cooperativo|evaluaré cómo aportó cada rol"),
    "EF01 OA 11": _spec("Comportamientos seguros en actividad física", "obedece señales de memoria sin comprender el riesgo que previenen", "conos, implementos blandos, tarjetas de riesgo y botiquín visible sin manipular", "Detectar en un montaje ficticio límites poco claros, material suelto y falta de distancia; corregir antes de iniciar", "Calentar jugando|prepararé articulaciones y atención", "Escuchar y comprobar instrucciones|mostraré la regla antes de partir", "Implementos bajo supervisión|transportaré y usaré material con control", "Límites y distancias|mantendré una zona segura", "Detener, avisar y reanudar|actuaré ante una condición insegura"),

    "OR01 OA 01": _spec("Características, habilidades e intereses personales", "convierte la actividad en comparación, etiqueta fija o exposición obligatoria", "tarjetas de fortalezas observables, siluetas y portafolio privado", "Describir una habilidad como algo que se practica —armar rompecabezas— y un interés como algo que se desea explorar, permitiendo elegir qué compartir", "Lo que observo de mí|describiré una característica sin compararme", "Habilidades que se desarrollan|reconoceré una acción que puedo practicar", "Intereses que orientan elecciones|nombraré algo que deseo conocer", "Retrato personal flexible|valoraré rasgos propios y posibilidades de cambio"),
    "OR01 OA 02": _spec("Identificación y expresión de emociones", "juzga una emoción como mala o supone lo que otra persona siente", "rostros ambiguos, termómetro emocional, relatos ficticios y tarjetas de estrategias", "Ante un personaje con manos tensas y voz alta, separar lo observable de la hipótesis rabia o miedo y preguntar antes de concluir", "Señales y nombres|distinguiré emoción de conducta", "Una situación, emociones posibles|evitaré adivinar lo que otro siente", "Formas seguras de expresar|elegiré palabras y acciones sin dañar", "Pedir apoyo y regular|practicaré una estrategia para un caso ficticio"),
    "OR01 OA 03": _spec("Expresiones de afecto, cariño y cuidado", "obliga contacto físico o presenta una única forma familiar de demostrar afecto", "historias diversas, tarjetas de consentimiento y escenas ficticias", "Comparar escuchar, compartir tiempo, ayudar y abrazar solo con acuerdo; mostrar que recibir cariño no exige aceptar contacto", "Muchas formas de cuidar|reconoceré expresiones verbales y acciones", "Preferencias y consentimiento|preguntaré y respetaré un no", "Dar y recibir ayuda|distinguiré apoyo de imposición", "Redes de cuidado|identificaré adultos seguros sin revelar datos"),
    "OR01 OA 04": _spec("Autocuidado, intimidad e información personal", "memoriza prohibiciones sin saber cuándo detenerse, alejarse o pedir ayuda", "casos ficticios, semáforo de privacidad, rutina de higiene y red de apoyo", "Clasificar nombre de pila, contraseña, dirección y foto privada según contexto; ensayar detenerse, no compartir y acudir a un adulto seguro", "Higiene y descanso|secuenciaré rutinas posibles", "Alimentación, recreación y movimiento|equilibraré formas de cuidado", "Mi cuerpo y la intimidad|reconoceré límites y pediré ayuda", "Información pública y privada|decidiré qué no compartir", "Plan de protección|practicaré detenerme, alejarme, contar y persistir"),
    "OR01 OA 05": _spec("Buen trato, respeto y solidaridad", "repite fórmulas corteses sin escuchar ni reparar el efecto de sus acciones", "títeres, casos de aula y tarjetas de turnos y reparación", "Transformar un préstamo tomado sin permiso en pedir, aceptar la respuesta, devolver y reparar si hubo daño", "Saludar y pedir con claridad|usaré formas de buen trato con sentido", "Escuchar y respetar turnos|mostraré que comprendí al otro", "Cuidar pertenencias y rutinas|actuaré responsablemente", "Compartir y ayudar sin imponer|ofreceré apoyo que admite respuesta", "Reparar el vínculo|propondré una acción después de un daño"),
    "OR01 OA 06": _spec("Resolución de conflictos entre pares", "busca culpable o exige reconciliación inmediata sin acuerdo", "viñetas ficticias, objeto de turno y organizador del acuerdo", "Dos personajes quieren el mismo material: cada uno describe hechos, escucha la necesidad, propone turnos y comprueba si el acuerdo es aceptable", "Hecho, emoción y necesidad|describiré el conflicto sin insultar", "Escuchar otra versión|reformularé antes de responder", "Proponer alternativas|buscaré más de una solución", "Acuerdo y reparación|elegiré, probaré y revisaré una solución"),
    "OR01 OA 07": _spec("Pertenencia y participación en grupos", "presenta familia o curso como estructuras únicas y confunde pertenecer con obedecer siempre", "mapas de grupos, roles optativos y fotografías ficticias diversas", "Ubicar familia, curso y pares en círculos de pertenencia, señalando aportes, derechos y formas de pedir ayuda sin registrar nombres privados", "Grupos diversos|reconoceré quiénes los componen sin estereotipos", "Lo que recibo y aporto|describiré reciprocidad", "Participar con una tarea|asumiré un rol concreto", "Valorar pertenencias múltiples|comunicaré semejanzas y diferencias con respeto"),
    "OR01 OA 08": _spec("Hábitos y actitudes para aprender", "confunde orden con silencio o atribuye una dificultad a falta de voluntad", "útiles, organizador visual, bandejas y bitácora de aprendizaje", "Preparar una mesa para una tarea, usar y devolver materiales, y cerrar nombrando qué estrategia permitió aprender", "Preparar lo necesario|seleccionaré y cuidaré útiles", "Orden que ayuda|organizaré espacio y materiales para una tarea", "Sostener y pedir ayuda|usaré una estrategia ante dificultad", "Reconocer aprendizaje|diré qué aprendí y cómo", "Rutina autónoma|planificaré inicio, trabajo y cierre"),

    "TE01 OA 01": _spec("Representación de diseños tecnológicos", "dibuja un objeto decorativo sin usuario, propósito ni partes funcionales", "papel, lápices, bloques, cartón y casos de necesidad", "Diseñar un marcador de página para una persona que pierde la línea: mostrar uso, forma, material y tamaño en dibujo y modelo", "Necesidad y usuario|definiré para quién y para qué diseño", "Muchas ideas posibles|produciré alternativas antes de elegir", "Dibujo que comunica|mostraré forma, partes y uso", "Modelo concreto|representaré volumen y unión", "Explicar una elección|vincularé el diseño con la necesidad"),
    "TE01 OA 02": _spec("Tareas, materiales y herramientas de elaboración", "enumera materiales sin ordenar tareas o elige herramientas por apariencia", "objeto simple, tarjetas de proceso, materiales y herramientas escolares", "Desarmar conceptualmente la fabricación de un sobre: medir, marcar, cortar, plegar y unir; asociar cada tarea con material y herramienta", "Mirar el resultado esperado|identificaré partes y terminación", "Ordenar tareas|construiré una secuencia posible", "Material para cada parte|justificaré una propiedad", "Herramienta para cada acción|elegiré uso seguro y comprobaré el plan"),
    "TE01 OA 03": _spec("Elaboración segura de un objeto tecnológico", "sigue pasos mecánicamente sin comprobar medidas, uniones o seguridad", "papel, fibras, plástico limpio, material reutilizado, regla, tijera y adhesivo", "Construir un contenedor de tarjetas: medir con plantilla, cortar por línea, plegar, unir, probar capacidad y ajustar", "Preparar espacio y materiales|seguiré una secuencia segura", "Medir, marcar y cortar|controlaré precisión antes de separar", "Plegar, unir y terminar|aplicaré técnicas según material", "Construir y comprobar|elaboraré el objeto y corregiré una unión"),
    "TE01 OA 04": _spec("Prueba y explicación de resultados tecnológicos", "dice quedó bonito o feo sin probar contra el propósito", "prototipos, tarjetas de prueba, objetos de carga y pauta de conversación", "Probar si un marcador se mantiene, se retira sin dañar y ayuda a volver a la línea; registrar resultado antes de proponer cambio", "Criterios antes de probar|definiré qué debe ocurrir", "Prueba observable|usaré el objeto en condiciones acordadas", "Resultado y causa posible|explicaré con evidencia", "Mejora respetuosa|propondré un cambio y reconoceré autoría"),
    "TE01 OA 05": _spec("Dibujo digital para representar ideas", "confunde dominar botones con comunicar una idea o borra el trabajo ajeno", "software de dibujo disponible, dispositivo compartido y alternativa en papel", "Crear un plano simple del rincón de lectura con formas, color funcional, deshacer y guardado con nombre no identificable", "Entrar y reconocer herramientas|ubicaré lienzo, forma, color y deshacer", "Trazos y formas con intención|representaré partes de una idea", "Color, tamaño y posición|haré legible la representación", "Revisar sin empezar de cero|usaré deshacer y modificaré una decisión", "Guardar y compartir responsablemente|conservaré el archivo sin datos personales"),
    "TE01 OA 06": _spec("Uso de software educativo y creativo", "hace clic por ensayo sin comprender la tarea o comparte datos para avanzar", "software educativo sin cuenta infantil, simulador o libro digital y alternativa desconectada", "Explorar una actividad de clasificación: leer propósito, probar una opción, interpretar retroalimentación y explicar qué se aprendió", "Propósito y controles|identificaré qué aprender y cómo interactuar", "Explorar con una pregunta|probaré opciones de manera intencional", "Leer retroalimentación|usaré el resultado para ajustar", "Transferir y cerrar|explicaré aprendizaje, saldré y cuidaré datos"),

    "EN01 OA 01": _spec("Listening to rhymes, chants, songs, stories and dialogues", "tries to translate every word and stops following the text", "short traceable audio, picture cards, puppets and rhythm markers", "Listen to a four-line chant and a tiny dialogue; point to who speaks, join the repeated line and show the ending with a gesture", "Listen for the text type|I will notice rhyme, song, story or dialogue clues", "Join a repeated pattern|I will respond to a familiar line", "Follow characters and events|I will show who does what", "Use sound and image clues|I will combine more than one clue", "Show overall understanding|I will respond without translating every word"),
    "EN01 OA 02": _spec("Listening to familiar topics and communicative functions", "recognizes isolated nouns but misses the instruction or function", "classroom objects, house and city scenes, food cards and short audio", "Hear Put the red circle under the chair and She can swim; act, choose the image and explain which key words carried the meaning", "School instructions|I will follow a short action sequence", "People and abilities|I will identify introductions and can or can't", "Objects, possession and quantity|I will show whose and how many", "Places and location|I will locate people and objects", "Actions happening now|I will match an action to what I hear"),
    "EN01 OA 03": _spec("Evidence of listening comprehension", "copies another person's action without checking the oral clue", "mini-stories, object sets, sound cards and response boards", "Hear The zebra is in the kitchen. It is eating; select character, place and action, then contrast /s/ in sip with /z/ in zip", "Identify characters and objects|I will select from an oral clue", "Follow simple instructions|I will act in the stated order", "Notice frequent expressions|I will respond to a familiar chunk", "Distinguish key English sounds|I will use sound contrast to decide", "Combine evidence|I will justify a response with words I heard"),
    "EN01 OA 04": _spec("Listening strategies", "guesses once from the picture and does not revise after listening", "audio, title image, key-word tokens and prediction board", "Predict a story from one image, listen for three key words, revise the prediction and connect the event with known school routines", "Predict and keep it revisable|I will make a first idea", "Connect prior knowledge|I will activate useful topic words", "Use images without guessing only|I will match picture and sound", "Focus on key words|I will ignore nonessential unknown words", "Listen again and revise|I will change my idea with evidence"),
    "EN01 OA 05": _spec("Personal and creative response to listening", "retells every detail instead of responding to what was heard", "short audio, drawing materials, figures and role cards", "After a story about a lost lunchbox, draw the chosen solution, mime the character's feeling and use I like or I don't like with a reason in Spanish or supported English", "Connect safely to experience|I will notice a relevant connection", "Show meaning through drawing|I will represent one heard detail", "Respond with movement|I will act on an oral clue", "Dramatize a moment|I will preserve character and action", "Express a preference or feeling|I will link my response to the text"),
    "EN01 OA 06": _spec("Reading stories, rhymes, cards, instructions and information", "reads aloud mechanically or relies only on the illustration", "large-print short texts, greeting cards, instruction strips and word cards", "Read a three-step picture-supported instruction and a greeting card; identify purpose, character or action and the chunks I want and Here", "Recognize text and purpose|I will use layout and words", "Find the general idea|I will combine title, image and print", "Track characters and actions|I will locate explicit information", "Use familiar chunks|I will read known expressions as units", "Demonstrate understanding|I will respond with text evidence"),
    "EN01 OA 07": _spec("Reading familiar topics and functions", "matches a single word while ignoring word order or the communicative purpose", "topic scenes, captions, mini-dialogues and information cards", "Read The cat is under the table and What does she do? She is a cook; match location and occupation, then alter one word and reread", "Instructions and introductions|I will read who speaks and what to do", "Ability, feeling and possession|I will identify the function", "Quantity and description|I will match words to a scene", "Location and information questions|I will find the requested detail", "Read actions happening now|I will connect is plus action to the image"),
    "EN01 OA 08": _spec("Reading strategies", "predicts from pictures and does not return to print", "short illustrated text, cover cards, rereading pointers and retell frames", "Cover the final picture, predict, read two lines, uncover and revise; reread aloud to a partner and retell with first, next, last supports", "Predict from title and image|I will state a revisable idea", "Connect known words|I will activate useful vocabulary", "Match image and print|I will verify instead of guessing", "Reread for a purpose|I will return to a difficult line", "Draw or retell|I will reconstruct meaning with support"),
    "EN01 OA 09": _spec("Response to reading", "gives an unrelated preference without referring to the text", "brief text, figures, speech bubbles and response cards", "After reading a character chooses soup, select I like or I don't like, illustrate another choice and point to the sentence that prompted the response", "Text-to-self connection|I will connect one precise detail", "Illustrate an idea|I will preserve information from print", "Dramatize a scene|I will use character words or actions", "Write a supported reaction|I will complete a meaningful phrase", "Share an opinion|I will refer back to the text"),
    "EN01 OA 10": _spec("English sounds through chants, rhymes and dialogues", "repeats louder rather than adjusting mouth, airflow or voicing", "mirror, sound cards, short chant and respectful pronunciation recording", "Contrast we with a Spanish-like initial, three with tree as an approximation goal, and sip with zip by noticing lip shape, airflow and voice", "Hear and see /w/|I will shape rounded lips and glide", "Explore /th/ safely|I will notice tongue and airflow without ridicule", "Contrast /s/ and /z/|I will feel when the voice turns on", "Put sounds in a chant|I will keep rhythm and intelligibility", "Use a tiny dialogue|I will communicate without demanding native accent"),
    "EN01 OA 11": _spec("Brief classroom interaction and presentation", "recites a memorized line without listening or responding", "realia, picture prompts, dialogue frames and optional digital image", "Use How do you say ...? and I'm ... in a two-turn exchange, then present one classroom object with gesture and a learned phrase", "Enter classroom interaction|I will ask for language or clarification", "Take a conversational turn|I will listen and respond", "Use objects and gestures|I will support a brief message", "Prepare a mini-presentation|I will organize two connected ideas", "Interact after presenting|I will answer one predictable question"),
    "EN01 OA 12": _spec("Supported oral communication for familiar functions", "lists vocabulary without forming a communicative message", "topic cards, number line to twenty, location scene and action pictures", "Say I can jump, There are twelve apples, The book is on the desk and She is running in separate information-gap tasks", "Personal information with boundaries|I will share a safe chosen fact", "Ability and quantity|I will use can and numbers to twenty", "Animals, food, jobs and places|I will identify and describe", "Prohibition and requests|I will use a phrase for a real purpose", "Location and current action|I will answer where and what is happening"),
    "EN01 OA 13": _spec("Model-supported writing", "copies letter shapes without checking spacing, meaning or the image", "word bank, sentence frames, picture cards and pencil or keyboard", "Complete This is a __ and I like __ from a model, then change one meaningful word and reread to a partner", "Copy with purpose|I will preserve letters, spaces and meaning", "Complete a word or chunk|I will use picture and word bank", "Build a simple sentence|I will follow a model and choose content", "Check with a reader|I will reread and repair one part"),
    "EN01 OA 14": _spec("Image-based writing for familiar meanings", "labels unrelated items or combines memorized chunks in incompatible ways", "scene images, movable words, number cards and writing frame", "From a kitchen scene write two labels, I am happy, There are six apples, The cup is on the table and He is eating with graduated support", "Identify from an image|I will write an accurate label", "Express feeling and quantity|I will complete a meaningful sentence", "Describe location|I will use in, on or under", "Describe an action now|I will use is plus action with support", "Create and revise a picture caption|I will check image, words and spacing"),
}


LANGUAGE_CONTEXTS = {
    "LF": ("fortalecimiento y desarrollo de la lengua", "una mediación sostenida en la lengua indígena seleccionada por educador tradicional o hablante competente"),
    "LR": ("rescate y revitalización de la lengua", "una mediación que recupera expresiones disponibles y no fuerza fluidez inexistente en la comunidad"),
    "LS": ("sensibilización sobre la lengua", "una aproximación respetuosa que reconoce sonidos y palabras verificadas sin simular dominio lingüístico"),
}


def _add_language_context_sequences() -> None:
    themes = {
        "01": ("Textos orales de tradición indígena", "trata el texto como adorno o inventa palabras para completar lo que no conoce", "audio o interpretación autorizada, objetos culturales contextualizados y registro corporal", "Trabajar una canción, poema, adivinanza o juego lingüístico validado por la comunidad, conservando autoría, pronunciación y ocasión de uso", ("Entrar por la escucha completa|disfrutaré ritmo, voz y situación", "Reconocer una repetición|participaré en un tramo verificado", "Comprender con cuerpo y gesto|mostraré una idea del texto", "Relacionar sin apropiarse|conectaré una experiencia y volveré al texto", "Reescuchar con un propósito|notaré una palabra, sonido o imagen", "Compartir comprensión|responderé oral, corporal o visualmente")),
        "02": ("Sonidos propios de la lengua indígena", "juzga el sonido desde la ortografía castellana o ridiculiza una pronunciación en aprendizaje", "grabación o modelo competente, espejo, tarjetas de significado y mapa toponímico", "Escuchar y reproducir únicamente sonidos y palabras proporcionados por una fuente local competente, sin transcripciones improvisadas", ("Escuchar antes de repetir|distinguiré un sonido en contexto", "Observar cómo se produce|notaré articulación sin caricaturizar", "Relacionar sonido y significado|reconoceré una palabra verificada", "Contrastar con cuidado|evitaré traducir el sonido a letras castellanas", "Reproducir con apoyo|ensayaré respetando mi etapa de aprendizaje", "Usar en un contexto|participaré en una expresión breve validada")),
        "03": ("Palabras, frases, toponimia y antroponimia culturalmente significativas", "colecciona vocabulario sin contexto o atribuye una palabra a todos los pueblos", "fuente lingüística local, mapa, imágenes contextualizadas y fichas de uso", "Seleccionar con el educador tradicional palabras de saludo, territorio, naturaleza o vida cotidiana e identificar pueblo, significado y situación de uso", ("Palabra y situación|conoceré significado y ocasión de uso", "Toponimia con territorio|relacionaré un nombre con un lugar", "Nombre y memoria|comprenderé que la antroponimia porta historia", "Interacción breve cuidada|usaré una expresión solo en contexto verificado")),
        "04": ("Relatos, experiencia y conocimiento cultural", "reemplaza el relato por una anécdota propia o generaliza su contenido a todos los pueblos", "relato autorizado, imágenes pertinentes, organizador relato-experiencia y fuente registrada", "Escuchar un relato seleccionado localmente, identificar una información cultural explícita y establecer una conexión que ayude a comprenderla", ("Escuchar el relato completo|seguiré personajes, lugar y acontecimiento", "Recuperar información cultural|identificaré un detalle explícito", "Conectar con cuidado|relacionaré una experiencia sin reemplazar el relato", "Comunicar y reconocer límites|explicaré qué aprendí y qué debo preguntar")),
        "05": ("Símbolos de escritura ancestral", "copia un símbolo como decoración sin conocer origen, significado o permiso de uso", "reproducciones autorizadas, ficha de procedencia, soportes y registro de observación", "Observar un símbolo pertinente al pueblo y territorio, documentar fuente y significado disponible, y distinguir apreciar de reproducir", ("Mirar con procedencia|identificaré pueblo, soporte y fuente", "Forma y significado|describiré sin inventar interpretación", "Uso y resguardo|preguntaré cuándo corresponde reproducir", "Respuesta respetuosa|valoraré el símbolo sin apropiarlo")),
        "06": ("Tecnologías para escuchar lengua y conocer escritura ancestral", "usa cualquier resultado de internet como autoridad o graba a personas sin consentimiento", "recurso digital autorizado, audífonos compartidos, proyector y alternativa sin conexión", "Comparar un archivo de institución o comunidad identificada con un recurso sin procedencia y decidir cuál puede usarse", ("Fuente y permiso|comprobaré quién publica y para qué", "Escucha focalizada|reconoceré un sonido o expresión verificada", "Símbolo y soporte digital|observaré sin copiar fuera de contexto", "Reproducir con consentimiento|usaré audio o voz sin registrar personas", "Guardar la procedencia|comunicaré enlace, pueblo y responsable")),
    }
    counts = {"LF": {"01": 6, "02": 6, "03": 4, "04": 4, "05": 4, "06": 5}, "LR": {"01": 6, "02": 5, "03": 4, "04": 4, "05": 4, "06": 4}, "LS": {"01": 6, "02": 5, "03": 4, "04": 4, "05": 4, "06": 4}}
    labels = {"LF": "Lengua en uso", "LR": "Recuperar la lengua", "LS": "Primer acercamiento"}
    for context, (context_name, safeguard) in LANGUAGE_CONTEXTS.items():
        for number, (topic, misconception, materials, example, steps) in themes.items():
            selected = [f"{labels[context]} · {step}" for step in steps[: counts[context][number]]]
            while len(selected) < counts[context][number]:
                selected.append(f"Transferencia situada {len(selected) + 1}|aplicaré lo aprendido en una situación validada")
            SEQUENCES[f"LC01 OA {context}{number}"] = _spec(f"{topic} · contexto de {context_name}", misconception, materials, f"La clase requiere {safeguard}. {example}", *selected)


_add_language_context_sequences()


SEQUENCES.update({
    "LC01 OA 07": _spec("Territorio ancestral e identidad", "reduce territorio a una división administrativa o ubica comunidades sin fuente", "mapa autorizado, fotografías del paisaje y voces comunitarias con procedencia", "Describir un territorio mediante agua, relieve, caminos, nombres y prácticas significativas, distinguiendo territorio ancestral de dirección privada", "Paisaje y relaciones|observaré elementos significativos", "Toponimia y memoria|relacionaré nombres verificados con territorio", "Movilidad y continuidad|reconoceré cambios sin negar pertenencia", "Descripción situada|comunicaré rasgos con fuente", "Mapa respetuoso|representaré sin exponer sitios sensibles"),
    "LC01 OA 08": _spec("Memoria familiar y transmisión cultural", "exige relatos personales o trata la memoria oral como menos válida que la escrita", "relato autorizado, objetos-fuente ficticios y pauta de conversación no invasiva", "Analizar cómo una práctica, consejo o historia pasa entre generaciones; permitir trabajar con un caso provisto si no se desea compartir familia", "Memoria y conocimiento|reconoceré qué se transmite", "Personas y formas de enseñar|identificaré oralidad, observación y práctica", "Cambios y continuidad|compararé versiones sin jerarquizarlas", "Registro con consentimiento|comunicaré memoria sin apropiarme"),
    "LC01 OA 09": _spec("Territorio, historia e identidad de los pueblos indígenas", "habla de los pueblos solo en pasado o como una cultura homogénea", "línea temporal, mapa, fuentes comunitarias actuales y registro de procedencia", "Vincular un acontecimiento, un territorio y una práctica contemporánea del pueblo correspondiente para mostrar continuidad y transformación", "Pueblo y territorio|localizaré con una fuente pertinente", "Historia viva|reconoceré pasado y presente", "Identidad y diversidad interna|evitaré una descripción única", "Síntesis con evidencia|explicaré una relación entre territorio, historia e identidad"),
    "LC01 OA 10": _spec("Relación entre ser humano y naturaleza", "presenta una cosmovisión indígena como creencia genérica o recurso utilitario", "relato o testimonio autorizado, elementos naturales no extraídos y mapa del territorio", "Interpretar una relación de reciprocidad presentada por una fuente del pueblo correspondiente, evitando mezclar tradiciones de pueblos distintos", "Observar relaciones|identificaré seres y acciones", "Reciprocidad y cuidado|comprenderé una responsabilidad mutua", "Comparar sin jerarquizar|distinguiré perspectivas con respeto", "Compromiso situado|propondré cuidado coherente con la fuente"),
    "LC01 OA 11": _spec("Mensajes de la naturaleza en la cosmovisión", "inventa significados universales para animales, clima o astros", "relato validado, calendario local y registros de fenómenos", "Estudiar un mensaje de la naturaleza documentado para el pueblo —por ejemplo una señal estacional— y citar quién lo comunica y en qué contexto", "Atender al fenómeno|describiré antes de interpretar", "Fuente cultural|identificaré quién enseña el significado", "Contexto y decisión|relacionaré mensaje, tiempo y acción", "Comunicar sin generalizar|explicaré alcance y procedencia"),
    "LC01 OA 12": _spec("Eventos socioculturales y ceremoniales", "convierte una ceremonia en representación escolar o divulga aspectos reservados", "fuentes públicas o autorizadas, calendario y pauta de respeto", "Conocer un evento mediante información que la comunidad define como pública, distinguiendo observar, participar e imitar", "Nombre, tiempo y lugar|ubicaré el evento con fuente", "Propósito y participantes|reconoceré su importancia", "Público y reservado|respetaré límites de conocimiento y registro", "Aprendizaje sin escenificación|comunicaré lo autorizado"),
    "LC01 OA 13": _spec("Valores y principios personales y familiares en contexto cultural", "asigna el mismo valor a todas las familias o fuerza confesiones personales", "dilemas ficticios, relatos autorizados y tarjetas de acciones", "Examinar un caso de palabra empeñada, ayuda o respeto a mayores presentado por una fuente cultural y compararlo con acciones posibles", "Valor en una acción|distinguiré palabra y conducta", "Familias y contextos diversos|evitaré suponer una única práctica", "Dilema ficticio|elegiré una acción y anticiparé efecto", "Escuchar otra razón|revisaré sin atacar identidades", "Compromiso observable|formularé una acción respetuosa"),
    "LC01 OA 14": _spec("Producción e intercambio ancestral", "reduce la técnica a manualidad o separa producción de estación, territorio e intercambio", "materias primas de muestra responsable, secuencia fotográfica y fuente comunitaria", "Seguir el ciclo documentado de una producción: obtención responsable, preparación, elaboración, intercambio o consumo", "Tiempo y territorio|ubicaré cuándo y dónde ocurre", "Insumos y preparación|reconoceré procedencia y cuidado", "Proceso técnico|ordenaré acciones y herramientas", "Intercambio y uso|explicaré cómo circula y para qué sirve"),
    "LC01 OA 15": _spec("Patrimonio cultural de comunidad, territorio y pueblo", "llama patrimonio a cualquier objeto antiguo o divulga localizaciones sensibles", "inventario comunitario público, fotografías autorizadas y mapa general", "Distinguir patrimonio material, inmaterial y natural mediante ejemplos definidos por la comunidad y registrar medidas de resguardo", "Qué se valora|reconoceré patrimonio con voz comunitaria", "Material e inmaterial|compararé objeto, práctica y conocimiento", "Amenazas y cuidados|propondré resguardo pertinente", "Ficha patrimonial responsable|comunicaré sin exponer información sensible"),
    "LC01 OA 16": _spec("Ser humano, naturaleza y cosmos desde ciencia indígena", "presenta conocimiento ancestral como mito opuesto a ciencia o mezcla medicina, navegación y astros sin fuente", "testimonio autorizado, cielo o mapa, plantas solo ilustradas y registro de observación", "Analizar cómo una observación sostenida de astros, plantas o navegación orienta una práctica del pueblo, sin recomendar tratamientos médicos", "Observar patrones|identificaré evidencia acumulada", "Conocimiento y práctica|relacionaré observación con decisión", "Autoridad y límites|distinguiré saber cultural de indicación médica", "Explicación respetuosa|comunicaré relación entre persona, naturaleza y cosmos"),
    "LC01 OA 17": _spec("Expresiones de arte del pueblo originario", "copia motivos sagrados o fabrica una artesanía descontextualizada", "obra o práctica autorizada, ficha de procedencia y materiales permitidos", "Observar una expresión artística con mediación cultural, identificar material, función y decisión, y crear una respuesta propia sin copiar símbolos restringidos", "Obra, autoría y contexto|reconoceré procedencia y función", "Material y técnica|exploraré solo lo permitido", "Decisiones culturales y personales|distinguiré aprendizaje de apropiación", "Respuesta artística cuidada|crearé y explicaré sin imitar lo reservado"),
})


PROFILES = {
    "MU": {"name": "Música", "slug": "musica", "evidence": "interpretación, representación o explicación apoyada en una pista audible", "support": "Reduce duración o número de capas, ofrece pulso corporal, eco, notación visual y elección de voz, gesto o instrumento; conserva escucha, decisión musical y participación."},
    "EF": {"name": "Educación Física y Salud", "slug": "educacion-fisica-salud", "evidence": "desempeño motriz seguro observado con una pauta breve", "support": "Ajusta distancia, velocidad, implemento, superficie o forma de participación y ofrece demostración desde varios ángulos; conserva la habilidad, el autocuidado y la toma de decisión."},
    "OR": {"name": "Orientación", "slug": "orientacion", "evidence": "decisión o representación aplicada a un caso seguro y ficticio", "support": "Permite responder sobre personajes, usar apoyos visuales y pasar o participar de forma privada; nunca exige revelar experiencias, diagnósticos, familia o datos personales."},
    "TE": {"name": "Tecnología", "slug": "tecnologia", "evidence": "diseño, objeto o interacción digital probado contra un criterio", "support": "Ofrece plantilla, herramienta adaptada, pasos visibles y alternativa desconectada; conserva elección de diseño, uso seguro, prueba y explicación del resultado."},
    "EN": {"name": "Inglés (Propuesta)", "slug": "ingles-propuesta", "evidence": "respuesta comunicativa comprensible mediante acción, selección, oralidad, lectura o escritura", "support": "Preenseña pocos chunks, repite con ritmo natural, ofrece imagen, gesto, banco de palabras y ensayo coral o en pareja; retira una ayuda sin exigir acento nativo."},
    "LC": {"name": "Lengua y Cultura de los Pueblos Originarios Ancestrales", "slug": "lengua-cultura-pueblos-originarios-ancestrales", "evidence": "respuesta oral, corporal, visual o explicativa vinculada a una fuente cultural identificada", "support": "Trabaja con educador tradicional, hablante o fuente comunitaria competente; ofrece oralidad, observación y participación gradual sin inventar lengua, homogeneizar pueblos ni forzar exposición identitaria."},
}


def transversal_link(code: str, lesson_index: int, goal: str) -> list[dict[str, str]]:
    prefix = code[:2]
    pool = ATTITUDES.get(prefix)
    if not pool:
        return []
    digits = "".join(character for character in code.rsplit(" ", 1)[-1] if character.isdigit())
    number = int(digits or 0)
    item_code, label = pool[(number + lesson_index) % len(pool)]
    return [{"code": item_code, "type": "Actitud", "application": f"Se promueve {label} durante «{goal}» y se registra una acción o producción observable, sin calificar personalidad, identidad, cuerpo ni origen."}]


def _actions(prefix: str, data: dict, title: str, goal: str, index: int) -> tuple[str, str, str, str, str]:
    example = data["example"]
    misconception = data["misconception"]
    if prefix == "MU":
        return (f"Recibe al curso con un fragmento, silencio u objeto sonoro relacionado con «{title.lower()}». Cada estudiante responde primero con gesto o símbolo; luego se escucha una segunda vez para desafiar la idea «{misconception}».", f"Modela con escucha real, no solo explicación: {example}. Detén el sonido en un punto preciso, nombra la pista audible y muestra cómo esa pista sostiene la meta «{goal}».", f"En pequeños ensambles alternan intérprete, oyente y director de señal. Aplican «{title.lower()}» a un fragmento nuevo, comparan lo que efectivamente suena y repiten un tramo después de una devolución audible.", f"Cada estudiante crea, interpreta o representa un ejemplo breve para «{goal}». Debe marcar inicio y final y señalar la cualidad, patrón o decisión que una persona oyente puede comprobar.", f"Escucha o interpreta un microfragmento nuevo; responde a «{goal}» y señala el instante o rasgo audible que respalda la respuesta.")
    if prefix == "EF":
        return (f"Delimita zonas, demuestra la señal de alto y presenta un reto de baja intensidad sobre «{title.lower()}». El grupo identifica antes el riesgo asociado a «{misconception}» y propone cómo controlarlo.", f"Para «{title.lower()}», demuestra a velocidad lenta y desde dos ángulos: {example}. Nombra base de apoyo, trayectoria, mirada, fuerza o distancia pertinente y muestra también un error seguro para contrastar.", f"Trabajan en estaciones con pocos intentos y retroalimentación inmediata. Una pareja ejecuta «{title.lower()}» y otra observa un criterio; luego cambian rol y ajustan espacio o implemento sin competir por rapidez.", f"Cada estudiante demuestra «{goal}» en un recorrido o juego nuevo de «{title.lower()}». El docente registra control, seguridad y decisión, ofreciendo una variante equivalente cuando exista barrera de acceso.", f"Realiza una ejecución breve de «{title.lower()}» para «{goal}», autoevalúa con pulgar o escala visual y explica una decisión de seguridad o control antes de recuperar respiración e hidratarse.")
    if prefix == "OR":
        return (f"Presenta una viñeta ficticia sobre «{title.lower()}» y permite responder en privado, pasar o hablar desde el personaje. Separa hechos de juicios y hace visible el riesgo de que alguien «{misconception}».", f"Para «{title.lower()}», piensa en voz alta sin contar experiencias personales: {example}. Modela dos opciones, anticipa efectos, nombra un límite o red de apoyo y elige la que mejor protege dignidad, convivencia y seguridad.", f"En parejas usan títeres o tarjetas para resolver otro caso de «{title.lower()}». Deben escuchar una segunda perspectiva, proponer dos acciones y comprobar cuál responde mejor a la meta «{goal}»; nadie evalúa la vida privada de otro.", f"Cada estudiante resuelve individualmente un caso seguro y distinto de «{title.lower()}» para «{goal}» mediante dibujo, elección razonada o guion breve. Puede usar un caso provisto en vez de revelar información propia.", f"Ante una viñeta nueva de «{title.lower()}», elige una acción para «{goal}», explica su posible efecto e identifica a quién pediría ayuda si la primera estrategia no funciona.")
    if prefix == "TE":
        return (f"Presenta una necesidad, artefacto o pantalla vinculada con «{title.lower()}». Antes de manipular, cada estudiante dibuja qué espera que ocurra y detecta el problema «{misconception}» en una solución ficticia.", f"Modela «{title.lower()}» con el ciclo necesidad → decisión → acción → prueba: {example}. Usa la herramienta delante del grupo, verbaliza seguridad y autoría, y registra un resultado observable en vez de decir solo funciona.", f"En parejas ejecutan una tarea acotada de «{title.lower()}»: una persona construye o interactúa y otra coteja criterio y seguridad. Intercambian roles, prueban y cambian una sola variable.", f"Cada estudiante diseña, elabora, prueba o usa una herramienta en «{title.lower()}» para «{goal}» con un caso nuevo. Entrega el producto junto con la decisión tomada y el resultado de la prueba.", f"Prueba un producto o interacción breve de «{title.lower()}», responde si cumple «{goal}» con evidencia y dibuja o explica una mejora concreta que no borra la autoría de otra persona.")
    if prefix == "EN":
        return (f"Use a short image, object or line of English connected to «{title.lower()}». Students first respond by pointing, acting or choosing; the teacher notes who is relying on the shortcut «{misconception}» without public correction.", f"Model meaning before terminology: {example}. Think aloud in accessible Spanish when needed, then replay or reread the English clue and show exactly how it supports «{goal}».", f"Pairs complete an information gap about «{title.lower()}»: one listens, reads or speaks and the other acts, selects or completes. They switch roles, ask for repetition and change one word so meaning—not memorization—must guide the response.", f"Each student completes a fresh listening, speaking, reading or writing task for «{goal}». Gesture, picture or word bank may support access, but the final choice or message must be their own.", f"With one new prompt, demonstrate «{goal}» by acting, selecting, saying or writing. Point to the heard, read or visual clue and repair one part after feedback.")
    return (f"Presenta una fuente identificada —voz autorizada, relato, imagen, objeto o registro— vinculada con «{title.lower()}». Antes de interpretar, el curso reconoce pueblo, contexto y permiso de uso; contrasta el riesgo «{misconception}».", f"Modela una lectura culturalmente situada para «{title.lower()}»: {example}. Distingue dato de inferencia, cita la mediación o fuente y verbaliza qué no se sabe o no corresponde reproducir.", f"Con guía de educador tradicional, hablante competente o fuente comunitaria pertinente, grupos pequeños trabajan «{title.lower()}». Comparan una respuesta respetuosa con otra que generaliza, inventa o extrae de contexto y justifican la corrección.", f"Cada estudiante produce una respuesta de «{title.lower()}» para «{goal}» usando la fuente acordada y registrando procedencia. Puede expresarse oral, corporal, visualmente o por escrito sin declarar pertenencia ni compartir memoria familiar.", f"Ante otra fuente breve y trazable de «{title.lower()}», responde a «{goal}», nombra pueblo y contexto, y formula una pregunta honesta cuando la evidencia no permite concluir.")


def build_sequence(code: str) -> dict | None:
    data = SEQUENCES.get(code)
    if not data:
        return None
    prefix = code[:2]
    profile = PROFILES[prefix]
    lessons = []
    for index, step in enumerate(data["steps"]):
        title, goal = step.split("|", 1)
        opening, model, guided, independent, ticket = _actions(prefix, data, title, goal, index)
        lessons.append({
            "title": title, "purpose": f"Desarrollar {data['topic'].lower()} mediante «{title.lower()}», con una experiencia propia de {profile['name']} y evidencia verificable.", "goal": f"Hoy {goal}.",
            "opening": opening, "model": model, "guided": guided, "independent": independent, "ticket": ticket, "materials": data["materials"], "support": profile["support"],
            "extension": f"Introduce un cambio pertinente de audiencia, regla, entorno, fuente, material o función en «{data['topic'].lower()}»; pide anticipar el efecto, probarlo y explicar qué decisión se mantiene o cambia.",
            "evidence": f"{profile['evidence'].capitalize()} para la meta «{goal}», acompañada por la pista, criterio, prueba o fuente que permite verificarla.",
            "criteria": ["responde a la meta y conserva la demanda del OA", "usa una pista, técnica, fuente o criterio propio de la asignatura", "explica una decisión, respeta seguridad y revisa con evidencia"],
            "next_step": "Avanza solo si la evidencia es individual y pertinente. Si el error se repite, vuelve al contraste específico de esta clase, cambia una vía de acceso y recoge una segunda evidencia sin reducir el OA.",
            "short_version": "Conserva experiencia inicial, demostración disciplinar, un ensayo guiado, desempeño individual y ticket. Reduce turnos, extensión o materiales; no elimina seguridad, fuente, comunicación ni revisión.",
            "home_task": "Realiza una observación o práctica breve y opcional relacionada con la meta usando recursos disponibles; registra una decisión o pregunta. No requiere compra, internet, grabar personas ni revelar datos o identidad.",
            "complementary": [f"Recuperación: vuelve al ejemplo concreto de «{title.lower()}», ofrece una representación distinta y recoge un nuevo intento.", f"Taller de errores: contrasta la respuesta con «{data['misconception']}» y mejora una decisión usando evidencia.", f"Profundización: modifica una condición de «{data['topic'].lower()}», prueba el efecto y justifica el ajuste."],
            "difficulty_actions": [
                {"signal": "No inicia o imita sin comprender", "action": "Reduce información accesoria, ofrece dos formas legítimas de entrada y modela un ejemplo diferente.", "check": "Inicia una respuesta propia y señala qué debe observar, hacer o comunicar."},
                {"signal": data["misconception"].capitalize(), "action": "Detén la tarea sin exponer al estudiante, vuelve al contraste específico y solicita una pista antes de elegir.", "check": "Resuelve un caso nuevo manteniendo el criterio y explica qué cambió."},
                {"signal": "Completa la acción, pero no aporta evidencia", "action": "Pide una huella verificable —sonido, movimiento, fuente, palabra, prueba o decisión— y ofrece una frase de apoyo temporal.", "check": "Vincula su desempeño con una evidencia propia sin repetir literalmente el modelo."},
            ],
            "specialist_coordination": "El docente conduce el OA. Los apoyos profesionales o comunitarios pertinentes asesoran acceso, seguridad, lengua y contexto sin reemplazar la enseñanza, diagnosticar en clase, exponer información personal ni atribuirse saber cultural que no poseen.",
            "transversal": transversal_link(code, index, goal),
        })
    source = f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/{profile['slug']}/1-basico/{code.lower().replace(' ', '-')}"
    return {"topic": data["topic"], "pedagogical_explanation": f"La secuencia desarrolla {data['topic'].lower()} mediante experiencias disciplinares, práctica con retroalimentación y evidencia individual. Controla explícitamente el riesgo de que el estudiante {data['misconception']}.", "prerequisites": "Participar en una experiencia breve, atender una demostración y comunicar una primera respuesta por una vía accesible; no se exige dominio previo ni exposición de información privada.", "vocabulary": f"{data['topic'].lower()}, evidencia, decisión, práctica, seguridad, comunicar y revisar", "official_alignment": {"units": [f"Progresión anual de {profile['name']} de 1° básico"], "indicators": [f"Criterio interno derivado del OA: {step.split('|', 1)[1]}." for step in data["steps"][:3]], "source": source, "indicator_origin": "criterios internos derivados del OA; requieren contraste con el Programa de Estudio y contextualización profesional"}, "lessons": lessons}
