"""Specific first-grade Language and Communication sequences."""
from __future__ import annotations


def _s(title: str, goal: str, example: str) -> tuple[str, str, str]:
    return title, goal, example


ATTITUDES = (
    ("de Actitud LE01 OAA A", "interés activo y disfrute de la lectura"),
    ("de Actitud LE01 OAA B", "disposición para compartir ideas, experiencias y opiniones"),
    ("de Actitud LE01 OAA C", "expresión creativa oral y escrita"),
    ("de Actitud LE01 OAA D", "trabajo riguroso y perseverante según el propósito"),
    ("de Actitud LE01 OAA E", "reflexión sobre las propias ideas e intereses"),
    ("de Actitud LE01 OAA F", "empatía con personas y contextos diversos"),
    ("de Actitud LE01 OAA G", "respeto por opiniones distintas y valoración del diálogo"),
)


def attitude_link(oa_number: int, lesson_index: int, goal: str) -> dict[str, str]:
    code, attitude = ATTITUDES[(oa_number + lesson_index * 2) % len(ATTITUDES)]
    return {"code": code, "type": "Actitud", "application": f"Se promueve {attitude}. La evidencia se recoge durante la meta estudiantil «{goal}», sin calificar rasgos personales."}


SEQUENCES = {
    "LE01 OA 01": {
        "topic": "Textos escritos, autores, destinatarios y propósitos comunicativos",
        "explanation": "Leer comienza al comprender que alguien produjo un texto para comunicar algo a otra persona. La secuencia contrasta textos reales, hace inferir quién escribe y para qué, y evita reducir la alfabetización inicial al reconocimiento de letras.",
        "prerequisites": "Interpretar imágenes y participar en intercambios orales breves; no se exige decodificación convencional.",
        "vocabulary": "texto, mensaje, autor, destinatario, propósito, informar, invitar, recordar y entretener",
        "materials": "Nota, invitación, letrero, cuento y envase sin datos personales; sobres, tarjetas de propósito y papel.",
        "misconception": "confunde el objeto o la ilustración con el mensaje escrito",
        "steps": [
            _s("¿Dónde está el mensaje?", "distinguiré escritura, imagen y objeto", "Contrasta una señal escrita con un dibujo sin palabras y señala qué información aporta cada parte."),
            _s("Alguien escribió para alguien", "inferiré autor y destinatario usando pistas", "Lee una nota ficticia firmada por la bibliotecaria y piensa qué palabras revelan quién escribe y quién debe actuar."),
            _s("Un texto cumple un propósito", "decidiré si un texto informa, invita, recuerda o entretiene", "Compara una invitación de cumpleaños con un aviso de biblioteca y vincula forma, palabras y propósito."),
            _s("Elegir el texto adecuado", "seleccionaré un tipo de texto para una necesidad", "Ante la necesidad de recordar traer una botella, compara cuento, nota y cartel antes de escoger."),
            _s("Crear un mensaje con propósito", "produciré un mensaje para un destinatario definido", "Dicta o escribe un aviso breve, comprueba que otra persona entienda qué debe saber o hacer y revisa una palabra clave."),
        ],
    },
    "LE01 OA 02": {
        "topic": "Palabras como unidades de significado separadas por espacios",
        "explanation": "La noción de palabra escrita se construye conectando lo que se dice con lo que se ve. Las clases usan frases significativas, recuento oral y marcas de espacio antes de pedir copia o segmentación autónoma.",
        "prerequisites": "Comprender una oración oral breve y seguir el recorrido visual de izquierda a derecha con apoyo.",
        "vocabulary": "palabra, oración, espacio, inicio, final, separar, contar y significado",
        "materials": "Tiras de oraciones, tarjetas-palabra, palitos separadores, sobres y marcadores borrables.",
        "misconception": "cuenta letras o sílabas cuando se pregunta cuántas palabras hay",
        "steps": [
            _s("Una idea formada por palabras", "reconoceré palabras dentro de una oración oral y escrita", "Pronuncia «Ana salta alto», mueve una ficha por cada palabra y luego vincula tres tarjetas escritas."),
            _s("Los espacios marcan límites", "usaré espacios para localizar dónde termina una palabra y comienza otra", "Amplía «Mi gato duerme» y recorre con el dedo palabra, espacio, palabra, espacio, palabra."),
            _s("Reconstruir una oración", "ordenaré palabras separadas para recuperar un mensaje", "Desordena «La rana nada» y decide el orden leyendo el significado, no el largo de las tarjetas."),
            _s("Separar palabras pegadas", "insertaré espacios para que una oración pueda leerse", "Presenta «Elsolsale» y prueba cortes posibles hasta obtener tres unidades con significado."),
            _s("Escribir y comprobar espacios", "escribiré una oración breve con palabras reconocibles y separadas", "Dicta o escribe un mensaje de cuatro palabras, marca cada espacio con un arco y pide a otra persona que lo lea."),
        ],
    },
    "LE01 OA 04": {
        "topic": "Lectura de palabras mediante correspondencias letra-sonido y combinaciones silábicas",
        "explanation": "Decodificar exige mirar todas las letras, recuperar sus sonidos, combinarlos y comprobar si la palabra resultante tiene sentido. La progresión avanza desde sílabas directas hacia combinaciones indirectas, complejas y dígrafos sin promover adivinación por la imagen.",
        "prerequisites": "Combinar y segmentar fonemas y sílabas oralmente; reconocer varias letras y sus sonidos más frecuentes.",
        "vocabulary": "letra, sonido, sílaba, combinar, palabra, dígrafo, precisión y comprobar",
        "materials": "Letras móviles, tarjetas sin ilustración, ventanas de lectura, listas breves y oraciones decodificables.",
        "misconception": "adivina por la inicial o la ilustración sin procesar la palabra completa",
        "steps": [
            _s("Mirar, sonar y combinar", "leeré sílabas directas uniendo sonidos", "Modela /m/ /a/ → ma con letras móviles y contrasta con decir el nombre de las letras sin combinarlas."),
            _s("Palabras con sílabas directas", "leeré palabras completas recorriendo todas sus sílabas", "Cubre y descubre ma-pa; combina cada parte, une «mapa» y comprueba si coincide con la escritura."),
            _s("Sílabas indirectas y complejas", "leeré combinaciones donde la consonante cambia de posición", "Contrasta al con la y sol con los, señalando el orden exacto de letras y sonidos."),
            _s("Dígrafos que trabajan juntos", "reconoceré ch, ll, rr y qu como combinaciones relevantes", "Marca ch en «chile», qu en «queso» y ll en «llave» antes de combinar la palabra completa."),
            _s("Leer palabras dentro de una oración", "decodificaré palabras y comprobaré el sentido del mensaje", "Lee «El perro corre» sin apoyo de imagen, vuelve a la palabra difícil y relee toda la oración con sentido."),
        ],
    },
    "LE01 OA 05": {
        "topic": "Lectura oral precisa, autocorrección y respeto de puntos",
        "explanation": "La fluidez inicial no equivale a velocidad. Se construye al leer con precisión, agrupar progresivamente palabras, usar la puntuación y releer con propósito, en textos suficientemente accesibles.",
        "prerequisites": "Decodificar palabras frecuentes y reconocer punto seguido y punto aparte visualmente.",
        "vocabulary": "precisión, releer, autocorregir, pausa, punto seguido, punto aparte, frase y fluidez",
        "materials": "Textos breves legibles, puntero, copias con frases marcadas y registro de lectura sin cronómetro competitivo.",
        "misconception": "lee más rápido sacrificando precisión y comprensión",
        "steps": [
            _s("Precisión antes que rapidez", "leeré cada palabra mirando todas sus letras", "Lee una oración lentamente, comete un error ficticio, vuelve a la palabra y muestra que autocorregir es parte de leer."),
            _s("Releer para ganar continuidad", "releeré un texto breve con menos interrupciones", "Realiza tres lecturas del mismo pasaje: eco, pareja e individual; compara precisión y continuidad sin medir velocidad."),
            _s("El punto seguido organiza", "haré una pausa breve y conservaré la idea entre oraciones", "Marca con una barra el punto seguido y modela una pausa que no rompe completamente el tema."),
            _s("El punto aparte cambia el bloque", "distinguiré la pausa y organización de dos párrafos", "Compara punto seguido y aparte en un texto de dos párrafos y anticipa qué cambia en el segundo."),
            _s("Lectura preparada para una audiencia", "leeré un texto breve con precisión, pausas y autocorrección", "Elige un pasaje conocido, ensaya las palabras difíciles y léelo a una pareja que registra dos evidencias concretas."),
        ],
    },
    "LE01 OA 06": {
        "topic": "Estrategias de comprensión: conectar experiencias y visualizar",
        "explanation": "Comprender requiere construir una representación mental y contrastarla con el texto. Las conexiones personales solo son útiles cuando ayudan a interpretar información, no cuando reemplazan lo leído.",
        "prerequisites": "Escuchar o leer un texto breve y relatar una experiencia relacionada de forma comprensible.",
        "vocabulary": "comprender, conectar, experiencia, conocimiento, visualizar, pista, imaginar y comprobar",
        "materials": "Relato y texto informativo breves, hojas de visualización, lápices y organizador texto-me recuerda-me ayuda.",
        "misconception": "cuenta una experiencia extensa sin volver a la información del texto",
        "steps": [
            _s("Antes de leer: activar sin adivinar", "recordaré conocimientos útiles y formularé una anticipación revisable", "A partir del título «Una noche de lluvia», recupera qué se sabe de la lluvia y separa saber previo de predicción."),
            _s("Conexiones que ayudan", "relacionaré una experiencia con una parte precisa del texto", "Vincula la reacción de un personaje con una experiencia segura y explica qué permite entender mejor."),
            _s("Construir una imagen mental", "visualizaré usando palabras descriptivas del texto", "Lee sin mostrar imagen: «una casa pequeña bajo árboles altos»; dibuja y subraya las palabras que guiaron cada detalle."),
            _s("Revisar la visualización", "cambiaré mi imagen mental cuando el texto aporte información nueva", "Añade una segunda descripción que contradice un color supuesto y modela cómo se corrige el dibujo."),
            _s("Elegir y explicar una estrategia", "usaré conexión o visualización según lo que necesito comprender", "Ante dos fragmentos, decide qué estrategia ayuda más, aplícala y cita la pista textual que sostuvo la comprensión."),
        ],
    },
    "LE01 OA 07": {
        "topic": "Lectura independiente de poemas, historias breves y textos predecibles",
        "explanation": "El repertorio literario se amplía mediante elección, lectura repetida, conversación y comparación. Independencia significa participar con apoyos graduales, no enfrentar textos inaccesibles en silencio.",
        "prerequisites": "Explorar un libro, seguir una lectura compartida y comunicar una preferencia con una razón.",
        "vocabulary": "literatura, poema, historia, patrón, repetición, personaje, verso, elección y recomendar",
        "materials": "Selección diversa de poemas, historias breves y libros predecibles; señaladores y bitácora de lectura.",
        "misconception": "elige solo por la portada y abandona sin probar una vía de lectura",
        "steps": [
            _s("Explorar un repertorio", "reconoceré diferencias entre poema, historia y texto predecible", "Examina tres libros, localiza versos, personajes o frases repetidas y anticipa cómo se recorre cada texto."),
            _s("Leer un texto con patrón", "usaré la repetición para participar y anticipar con evidencia", "En una historia acumulativa, cubre la frase repetida, anticipa y luego comprueba palabra por palabra."),
            _s("Habitar una historia breve", "seguiré personajes, acciones y cambios en una narración", "Detente en tres momentos y registra quién actúa, qué cambia y qué pregunta queda abierta."),
            _s("Escuchar y releer poesía", "notaré ritmo, imágenes y palabras que producen un efecto", "Lee un poema dos veces; en la segunda, marca una palabra sonora y una imagen que apareció en la mente."),
            _s("Elegir, sostener y recomendar", "leeré un texto elegido y lo recomendaré con una razón", "Usa una prueba de tres páginas, elige continuar o cambiar justificadamente y prepara una recomendación sin contar todo el final."),
        ],
    },
    "LE01 OA 08": {
        "topic": "Comprensión profunda de narraciones familiares",
        "explanation": "Comprender una narración supone recuperar información explícita, inferir con pistas, ordenar acontecimientos, interpretar ilustraciones, conectar experiencias y formular una opinión fundamentada.",
        "prerequisites": "Escuchar una narración completa, reconocer personajes y relatar al menos dos acciones en orden.",
        "vocabulary": "personaje, ambiente, acontecimiento, explícito, inferir, pista, ilustración, experiencia y opinión",
        "materials": "Narración completa apropiada, secuencias de imágenes, tarjetas de preguntas y materiales simples de dramatización.",
        "misconception": "responde desde memoria general o experiencia personal sin usar una pista del relato",
        "steps": [
            _s("Quién, dónde y qué ocurre", "recuperaré información explícita de una narración", "Tras leer un episodio, vuelve a las líneas que nombran personaje, lugar y acción para responder qué, quién, dónde y cuándo."),
            _s("Ordenar causas y acciones", "reconstruiré la secuencia y explicaré por qué ocurre un hecho", "Ordena cuatro escenas y une causa-acción-consecuencia usando porque; vuelve al texto si dos órdenes parecen posibles."),
            _s("Inferir con pistas", "deduciré sentimientos o motivos usando texto e ilustración", "El personaje cierra la puerta y abraza su mochila; propone una inferencia y distingue pista de conclusión."),
            _s("Ilustración y palabras conversan", "explicaré qué agrega una ilustración a la historia", "Compara una página con y sin imagen y localiza un detalle que la ilustración muestra pero el texto no nombra."),
            _s("Recrear sin perder el sentido", "representaré un personaje o escena conservando rasgos del relato", "Prepara un títere o dramatización breve y exige dos decisiones justificadas por acciones o palabras del personaje."),
            _s("Opinar con fundamento", "formularé una opinión sobre la narración y la apoyaré con evidencia", "Responde si una decisión del personaje fue adecuada, cita un hecho y escucha una opinión diferente antes de revisar la propia."),
        ],
    },
    "LE01 OA 09": {
        "topic": "Disfrute, escucha y lectura habitual de poesía",
        "explanation": "La experiencia poética se sostiene en relectura, sonido, imagen, juego verbal y conversación estética. No se reduce a memorizar ni a buscar una moraleja única.",
        "prerequisites": "Escuchar un texto breve, repetir fragmentos y expresar qué palabra o imagen llamó la atención.",
        "vocabulary": "poema, verso, estrofa, ritmo, rima, repetición, imagen y tradición oral",
        "materials": "Poemas de autor y tradición oral con procedencia, copias ampliadas, tarjetas de versos e instrumentos sonoros opcionales.",
        "misconception": "busca solo palabras que riman y pierde el sentido o efecto del poema",
        "steps": [
            _s("Escuchar antes de explicar", "disfrutaré un poema completo y registraré una primera impresión", "Lee sin interrupciones, deja silencio y pide elegir una palabra, sonido o imagen que quedó resonando."),
            _s("Ritmo, repetición y rima", "notaré recursos sonoros y su efecto", "Relee marcando pulso suave; contrasta repetición con rima y pregunta qué sensación produce cada recurso."),
            _s("Imágenes que abren sentidos", "visualizaré una imagen poética sin exigir una única respuesta", "Ante «la luna peina el río», distingue lo literalmente posible de la imagen creada y acepta interpretaciones con pista."),
            _s("Poesía de tradición oral", "participaré en una ronda, rima o retahíla respetando su procedencia", "Presenta una pieza tradicional identificada, ensaya por eco y conversa sobre cuándo o con quién podría compartirse."),
            _s("Antología personal", "elegiré y recomendaré un poema por su efecto", "Selecciona entre tres poemas, copia o ilustra un verso breve permitido y explica por qué invitaría a otra persona a escucharlo."),
        ],
    },
    "LE01 OA 10": {
        "topic": "Comprensión de cartas, notas, instrucciones y artículos informativos",
        "explanation": "Los textos no literarios se leen según su propósito y organización. La secuencia trabaja información explícita e implícita, relación entre partes y opinión fundamentada sin tratar todos los géneros como un cuestionario idéntico.",
        "prerequisites": "Reconocer que un texto tiene propósito y localizar palabras o imágenes destacadas con apoyo.",
        "vocabulary": "carta, nota, instrucción, artículo, título, paso, información, inferir y opinión",
        "materials": "Carta y nota ficticias, instrucciones ilustradas, artículo breve, organizadores y materiales para ejecutar un procedimiento seguro.",
        "misconception": "lee fragmentos aislados sin considerar el propósito ni la estructura del género",
        "steps": [
            _s("Carta y nota: quién comunica", "identificaré emisor, destinatario y mensaje", "Compara una carta breve con una nota; localiza saludo, firma y acción esperada sin usar datos reales."),
            _s("Instrucciones que se pueden seguir", "ordenaré y ejecutaré pasos usando verbos y secuencia", "Desordena tres instrucciones para doblar papel, prueba el orden y vuelve a los verbos primero, luego y finalmente."),
            _s("Artículo para aprender", "localizaré tema e información explícita en un texto informativo", "Lee título, imagen y dos párrafos sobre picaflores; registra una idea por párrafo y evita copiar una oración completa."),
            _s("Inferir información no dicha", "deduciré una idea usando dos pistas del texto", "Si una nota pide botas y paraguas, infiere el tiempo esperado y señala las dos pistas que permiten concluirlo."),
            _s("Comparar géneros y propósitos", "elegiré el texto adecuado para una necesidad", "Decide si conviene nota, instrucción o artículo para tres situaciones y defiende cada elección."),
            _s("Opinar después de comprender", "formularé una opinión sobre una información y la justificaré", "Tras leer un artículo sobre recreos activos, opina sobre una propuesta citando un dato y diferenciándolo del gusto personal."),
        ],
    },
    "LE01 OA 11": {
        "topic": "Exploración de libros e ilustraciones para desarrollar gusto lector",
        "explanation": "El gusto lector se cultiva con acceso, elección, conversación y tiempo real para explorar. Las ilustraciones se leen como portadoras de significado y la preferencia se argumenta sin convertirla en control de lectura.",
        "prerequisites": "Manipular libros con cuidado y comunicar una preferencia mediante palabra, gesto o elección.",
        "vocabulary": "portada, título, autor, ilustrador, página, explorar, elegir, preferencia y recomendar",
        "materials": "Colección diversa de libros en buen estado, señaladores, canastos temáticos y bitácora de exploración.",
        "misconception": "hojea rápidamente o elige siempre el mismo formato sin observar contenido",
        "steps": [
            _s("Un libro ofrece pistas", "exploraré portada, título e ilustraciones antes de elegir", "Modela una exploración lenta: observa portada, abre tres páginas, formula una pregunta y decide si continuar."),
            _s("Leer ilustraciones", "describiré detalles y relaciones que una imagen comunica", "En una doble página sin texto, recorre personajes, acciones, dirección de miradas y cambios de color antes de inferir."),
            _s("Probar antes de decidir", "usaré una prueba breve para sostener o cambiar mi elección", "Explora tres páginas de dos libros y verbaliza: lo continúo porque… o lo cambio porque…"),
            _s("Conversación entre lectores", "compartiré un hallazgo sin contar todo el libro", "Muestra una página elegida, explica qué llamó la atención y formula una pregunta auténtica a otra persona."),
            _s("Mi recorrido lector", "registraré elecciones y reconoceré intereses que pueden cambiar", "Revisa tres registros de lectura, identifica una coincidencia y elige un libro diferente para ampliar el repertorio."),
        ],
    },
    "LE01 OA 12": {
        "topic": "Uso habitual, autónomo y respetuoso de la biblioteca",
        "explanation": "La biblioteca es una comunidad de lectura, no solo un lugar silencioso. La secuencia enseña orientación, elección, cuidado, préstamo y conversación con el equipo CRA o responsable disponible.",
        "prerequisites": "Explorar libros y seguir acuerdos simples de desplazamiento y cuidado.",
        "vocabulary": "biblioteca, CRA, colección, estante, catálogo, préstamo, devolución, autor y tema",
        "materials": "Biblioteca o rincón de aula, plano simple, señalética, fichas de préstamo ficticias y selección diversa.",
        "misconception": "elige solo por cercanía o cree que pedir ayuda significa no saber leer",
        "steps": [
            _s("La biblioteca y sus acuerdos", "reconoceré espacios, personas y acuerdos que permiten leer", "Recorre un plano, localiza devolución, consulta y lectura; explica para qué sirve cada acuerdo, no solo lo recites."),
            _s("Buscar por interés", "localizaré libros usando tema, autor o tipo de texto", "Piensa en voz alta una búsqueda sobre animales: observa señalética, pregunta y compara dos opciones."),
            _s("Elegir un libro posible", "combinaré interés y accesibilidad para elegir", "Aplica una prueba de portada, tres páginas y cantidad de apoyo; muestra que cambiar de libro es una decisión lectora válida."),
            _s("Escuchar y conversar en biblioteca", "participaré en una lectura compartida con una respuesta propia", "Tras una lectura del responsable, comparte una observación y una pregunta vinculadas al texto."),
            _s("Préstamo, cuidado y devolución", "seguiré el circuito de préstamo y recomendaré responsablemente", "Completa un préstamo ficticio, prepara el transporte seguro y ensaya cómo informar un daño sin ocultarlo."),
        ],
    },
    "LE01 OA 13": {
        "topic": "Escritura emergente para comunicar hechos, ideas y sentimientos",
        "explanation": "Experimentar con escritura implica producir mensajes con intención usando dibujos, letras, palabras conocidas y dictado al adulto como apoyos legítimos. La revisión se centra primero en si otra persona puede comprender.",
        "prerequisites": "Comunicar oralmente una idea y producir trazos, dibujos o algunas letras con intención.",
        "vocabulary": "escribir, comunicar, idea, hecho, sentimiento, mensaje, destinatario, releer y revisar",
        "materials": "Papeles variados, cuaderno, lápices, letras móviles, tarjetas de palabras útiles y buzón de aula.",
        "misconception": "cree que solo puede escribir si conoce la ortografía convencional de cada palabra",
        "steps": [
            _s("Escribir deja una idea", "produciré una marca, dibujo o palabra con intención comunicativa", "Escribe una nota emergente junto a un dibujo y explica qué parte del mensaje queda en cada recurso."),
            _s("Contar un hecho", "registraré algo ocurrido con orden comprensible", "Planifica qué pasó primero y después, dicta una frase y decide qué palabra intentará escribir autónomamente."),
            _s("Expresar una idea", "escribiré lo que pienso para que otra persona pueda responder", "Ante una pregunta segura del curso, completa «Yo pienso… porque…» con dibujo, letras o dictado parcial."),
            _s("Nombrar un sentimiento sin exponerse", "comunicaré un sentimiento en un caso ficticio", "Elige un personaje, escribe cómo se siente y añade la situación que permite comprenderlo, sin pedir revelaciones personales."),
        ],
    },
    "LE01 OA 14": {
        "topic": "Oraciones completas para transmitir mensajes comprensibles",
        "explanation": "Una oración completa comunica una idea que el destinatario puede reconstruir. Se trabaja oralidad previa, quién o qué, qué ocurre y detalles pertinentes antes de revisar mayúscula o punto.",
        "prerequisites": "Formular oralmente una idea breve y reconocer palabras separadas por espacios.",
        "vocabulary": "oración, mensaje, quién, qué ocurre, detalle, mayúscula, punto, releer y completar",
        "materials": "Imágenes narrativas, tarjetas de sujeto y acción, tiras de escritura, banco de palabras y lápices.",
        "misconception": "escribe una lista de palabras o fragmento que no permite reconstruir la idea",
        "steps": [
            _s("Una oración dice algo completo", "distinguiré una idea completa de un fragmento", "Contrasta «El perro» con «El perro duerme bajo la mesa» y pregunta qué información falta para comprender."),
            _s("Quién y qué ocurre", "construiré oralmente una oración antes de escribir", "A partir de una imagen, formula quién + acción, cambia el sujeto y observa cómo cambia el mensaje."),
            _s("Agregar un detalle útil", "ampliaré una oración sin perder claridad", "Transforma «La niña lee» en «La niña lee un cuento en el sillón» y decide qué detalle aporta información."),
            _s("Escribir para un destinatario", "escribiré una oración que otra persona pueda comprender sin explicación adicional", "Redacta una instrucción o noticia de aula de una oración y pruébala con un lector real."),
            _s("Releer y completar", "revisaré sentido, inicio, espacios y cierre", "Usa cuatro preguntas: ¿dice quién o qué?, ¿qué ocurre?, ¿se distinguen palabras?, ¿termina con punto?"),
        ],
    },
    "LE01 OA 15": {
        "topic": "Letra legible y separación de palabras para lectores reales",
        "explanation": "La legibilidad sirve a la comunicación y no debe confundirse con uniformidad estética. La secuencia enseña postura y trazo funcional, tamaño consistente, espacios y revisión desde la perspectiva del lector.",
        "prerequisites": "Trazar formas básicas y escribir o copiar palabras breves con una herramienta adecuada.",
        "vocabulary": "legible, trazo, tamaño, línea, espacio, palabra, lector y revisar",
        "materials": "Lápices de distintos agarres, papel con pautas opcionales, tarjetas separadoras y textos breves propios.",
        "misconception": "prioriza adornar o borrar repetidamente por sobre comunicar el mensaje",
        "steps": [
            _s("Escribir para que otro lea", "reconoceré rasgos que vuelven legible una palabra", "Compara dos versiones ficticias y analiza forma reconocible, tamaño y separación sin juzgar belleza."),
            _s("Trazos y postura funcional", "probaré una forma cómoda de escribir con control", "Modela apoyo del papel, presión suficiente y pausas; ofrece agarres sin imponer una postura única innecesaria."),
            _s("Tamaño y línea de escritura", "mantendré letras reconocibles dentro de un espacio", "Escribe una palabra demasiado variable, luego ajusta solo el rasgo que impide leerla."),
            _s("Espacios que ayudan al lector", "separaré palabras sin cortar una palabra", "Usa una tarjeta como separador en una oración y retírala gradualmente al releer."),
            _s("Prueba con un lector", "revisaré mi escritura según lo que otra persona logra leer", "Intercambia un mensaje breve; el lector subraya lo claro y encierra una parte para preguntar, sin reescribirla por el autor."),
        ],
    },
    "LE01 OA 16": {
        "topic": "Uso pertinente de vocabulario nuevo en la escritura",
        "explanation": "Aprender una palabra supone comprenderla en contexto, relacionarla con otras y usarla con precisión. Copiar vocabulario no garantiza incorporación: la palabra debe mejorar el mensaje escrito.",
        "prerequisites": "Comprender una palabra nueva explicada oralmente y producir una oración emergente.",
        "vocabulary": "vocabulario, significado, contexto, palabra nueva, preciso, elegir, reemplazar y revisar",
        "materials": "Texto leído, mural de palabras con ejemplos, tarjetas semánticas, cuadernos y dibujos de contexto.",
        "misconception": "inserta una palabra nueva en una oración donde no conserva su significado",
        "steps": [
            _s("Descubrir una palabra en contexto", "inferiré un significado inicial usando frase e ilustración", "Oculta la definición de «refugio», reúne pistas del párrafo y formula una hipótesis revisable."),
            _s("Precisar el significado", "compararé ejemplos y no ejemplos de una palabra", "Clasifica situaciones que son o no «enormes» y ajusta una definición accesible sin usar solo sinónimos vagos."),
            _s("Guardar una palabra para usarla", "registraré significado, ejemplo y dibujo propio", "Construye una tarjeta con palabra, frase del texto, explicación propia e imagen que no sea decorativa."),
            _s("Elegir la palabra pertinente", "usaré vocabulario nuevo para hacer más preciso un mensaje", "Compara «El animal fue a un lugar» con «El zorro buscó refugio» y analiza qué información aporta la palabra."),
            _s("Revisar el uso", "comprobaré que la palabra nueva conserva sentido en mi oración", "Sustituye la palabra por su explicación; si la oración deja de tener sentido, revisa contexto o elección."),
        ],
    },
    "LE01 OA 17": {
        "topic": "Comprensión y disfrute de obras literarias completas leídas por un adulto",
        "explanation": "Escuchar obras completas permite acceder a lenguaje y estructuras más complejas que la lectura autónoma inicial. La mediación protege continuidad, disfrute, conversación e interpretación sin fragmentar todo en preguntas.",
        "prerequisites": "Sostener atención compartida por períodos breves y comunicar una impresión sobre lo escuchado.",
        "vocabulary": "obra, narrador, cuento, poema, fábula, leyenda, personaje, episodio y escuchar",
        "materials": "Obras completas apropiadas y con procedencia, señaladores, imágenes selectivas y registro de escucha.",
        "misconception": "atiende solo para responder preguntas literales y pierde el hilo global o disfrute",
        "steps": [
            _s("Prepararse para una obra completa", "anticiparé género y sostendré una pregunta durante la escucha", "Presenta título, autor y género; formula una pregunta amplia y acuerda pocas pausas para no romper la experiencia."),
            _s("Seguir personajes y episodios", "recordaré cambios importantes sin narrar cada detalle", "Tras un tramo, resume en una frase qué quería el personaje y qué cambió; registra una pregunta pendiente."),
            _s("Escuchar lenguaje literario", "notaré una expresión, imagen o repetición significativa", "Relee una frase rica, deja que suene y conversa sobre el efecto antes de parafrasear."),
            _s("Comparar géneros", "reconoceré cómo cuento, poema, fábula o leyenda producen experiencias distintas", "Contrasta dos obras completas ya escuchadas por voz, estructura y relación con realidad o tradición."),
            _s("Conversar después del cierre", "interpretaré y disfrutaré la obra con evidencia", "Elige una escena memorable, explica por qué y escucha otra elección antes de ampliar la propia interpretación."),
        ],
    },
    "LE01 OA 18": {
        "topic": "Comprensión activa de explicaciones, instrucciones, relatos y anécdotas orales",
        "explanation": "Escuchar para comprender implica identificar propósito, construir imágenes, conectar experiencias, preguntar para aclarar y responder con información pertinente. La memoria literal no sustituye la comprensión.",
        "prerequisites": "Seguir un intercambio oral breve y pedir repetición cuando no comprende.",
        "vocabulary": "escuchar, propósito, explicación, instrucción, relato, anécdota, visualizar, aclarar y opinión",
        "materials": "Audios o lectura docente breve, objetos para seguir instrucciones, organizadores visuales y tarjetas de preguntas.",
        "misconception": "responde con una idea relacionada pero no con la información realmente escuchada",
        "steps": [
            _s("Escuchar con un propósito", "sabré qué información necesito obtener antes de escuchar", "Antes de una explicación sobre nidos, acuerda escuchar para responder dónde se construyen y con qué materiales."),
            _s("Conectar y visualizar", "construiré una imagen mental y la relacionaré con conocimientos útiles", "Escucha la descripción de un recorrido, dibújalo y distingue una pista escuchada de un detalle imaginado."),
            _s("Seguir instrucciones orales", "ejecutaré pasos en orden y pediré aclaración pertinente", "Entrega tres pasos para organizar tarjetas; modela detenerse y preguntar cuál tarjeta si una referencia es ambigua."),
            _s("Preguntar para aprender más", "formularé preguntas que agregan o aclaran información", "Contrasta «¿puedes repetir?» con «¿por qué el nido está alto?» y decide qué necesidad satisface cada pregunta."),
            _s("Responder preguntas abiertas", "organizaré una respuesta usando información escuchada", "Responde qué aprendiste y cómo lo sabes con una idea principal y un detalle de la explicación."),
            _s("Opinar sobre lo escuchado", "formularé una opinión pertinente y la justificaré", "Tras una anécdota ficticia, opina sobre una decisión usando un hecho escuchado, no una historia paralela."),
        ],
    },
    "LE01 OA 19": {
        "topic": "Curiosidad por palabras desconocidas y estrategias para averiguar significados",
        "explanation": "Un lector y oyente competente detecta cuándo una palabra impide comprender, formula una hipótesis, consulta contexto o fuente y vuelve al mensaje. Preguntar por una palabra es una estrategia, no una falla.",
        "prerequisites": "Reconocer que no comprende una parte y participar en una conversación sobre significados.",
        "vocabulary": "palabra desconocida, significado, contexto, pista, hipótesis, preguntar, diccionario y comprobar",
        "materials": "Textos breves, tarjetas con palabras, diccionario infantil o glosario, mural de hallazgos y notas adhesivas.",
        "misconception": "ignora la palabra o acepta la primera definición aunque no funcione en el contexto",
        "steps": [
            _s("Notar lo que no comprendo", "identificaré una palabra que necesita atención", "Lee una frase con «sigiloso», modela detenerse sin vergüenza y explica qué parte del mensaje queda incierta."),
            _s("Usar pistas del contexto", "formularé una hipótesis de significado", "En «el gato avanzó sigiloso y nadie lo oyó», relaciona acción y consecuencia para proponer una explicación provisional."),
            _s("Preguntar y consultar", "elegiré una fuente o persona para aclarar", "Compara preguntar al compañero, releer, mirar glosario y consultar diccionario; decide cuál es viable y por qué."),
            _s("Comprobar y guardar la palabra", "usaré el significado en otro ejemplo pertinente", "Sustituye «sigiloso» por la explicación, crea una situación nueva y registra palabra, significado y ejemplo."),
        ],
    },
    "LE01 OA 20": {
        "topic": "Experiencia teatral infantil, creatividad y familiarización con el género",
        "explanation": "Asistir a teatro implica preparación, atención a cuerpo, voz, espacio y conflicto, y conversación posterior. La experiencia puede ser presencial, escolar o registrada legalmente; no se reduce a un cuestionario.",
        "prerequisites": "Seguir una representación breve y distinguir actor o personaje con apoyo.",
        "vocabulary": "teatro, obra, escena, actor, personaje, público, escenografía, gesto, voz y aplauso",
        "materials": "Obra infantil autorizada o representación escolar, programa simple, plano del espacio y bitácora visual.",
        "misconception": "relata solo la historia e ignora cómo cuerpo, voz y espacio construyen la representación",
        "steps": [
            _s("Prepararnos como público", "anticiparé qué observar y acordaré una participación respetuosa", "Presenta título, espacio y acuerdos; distingue silencio atento de inmovilidad obligatoria y prevé apoyos sensoriales."),
            _s("Personaje construido con cuerpo y voz", "observaré cómo un actor comunica sin explicar todo", "Compara dos entradas del mismo personaje cambiando postura, ritmo y volumen; infiere rasgos desde lo observable."),
            _s("Espacio, objetos y sonidos", "explicaré cómo recursos escénicos ayudan a comprender", "Localiza un objeto, luz o sonido que cambió una escena y reconstruye qué información aportó."),
            _s("Conversar después de la obra", "compartiré una interpretación y escucharé otra", "Elige una escena, describe un recurso teatral y explica su efecto antes de opinar si resultó convincente."),
            _s("Recrear una posibilidad", "crearé una escena breve usando cuerpo, voz y espacio", "En grupo representa una situación de dos acciones con un objeto simbólico; el público identifica pistas sin adivinar la intención del autor."),
        ],
    },
    "LE01 OA 21": {
        "topic": "Conversaciones grupales con ideas, escucha y respeto de turnos",
        "explanation": "Conversar no es responder uno por uno al docente. La secuencia enseña a construir sobre ideas ajenas, expresar acuerdos o diferencias, pedir aclaración y distribuir la participación alrededor de textos y temas seguros.",
        "prerequisites": "Expresar una idea breve y esperar un turno con apoyos visibles.",
        "vocabulary": "conversar, idea, opinión, razón, turno, escuchar, responder, acuerdo, diferencia y aclarar",
        "materials": "Texto o tema común, tarjetas de movimientos conversacionales, objeto de turno opcional y registro del grupo.",
        "misconception": "espera su turno para repetir su propia idea sin responder a lo escuchado",
        "steps": [
            _s("Una conversación conecta voces", "distinguiré hablar por turno de construir una conversación", "Representa dos diálogos: respuestas aisladas al docente y estudiantes que se preguntan, enlazan y discrepan."),
            _s("Expresar una idea con razón", "comunicaré una opinión comprensible y pertinente", "Usa «Pienso… porque en el texto…» y separa razón de repetición de la opinión."),
            _s("Mostrar que escuché", "responderé a una idea ajena antes de agregar la propia", "Modela «Entendí que tú dices…; yo agregaría…» y permite corregir la paráfrasis."),
            _s("Disentir y preguntar con respeto", "expresaré una diferencia o duda sin atacar a la persona", "Transforma «estás mal» en una pregunta sobre evidencia o una alternativa con razón."),
            _s("Conversación autónoma breve", "participaré en un diálogo grupal equilibrado", "Grupos de cuatro conversan sobre una decisión de un personaje; registran conexiones, preguntas y voces aún no escuchadas."),
        ],
    },
    "LE01 OA 22": {
        "topic": "Convenciones sociales y fórmulas de cortesía en situaciones diversas",
        "explanation": "Las convenciones sociales son recursos para participar y cuidar vínculos, no guiones rígidos ni medidas de obediencia. Se eligen según contexto, interlocutor, intención y formas culturales pertinentes.",
        "prerequisites": "Participar en intercambios breves y reconocer emociones o necesidades en casos ficticios.",
        "vocabulary": "presentarse, saludar, preguntar, opinión, sentimiento, por favor, gracias, perdón, permiso y contexto",
        "materials": "Tarjetas de situaciones ficticias, títeres, tarjetas de expresiones y semáforo de intención-efecto.",
        "misconception": "repite una fórmula cortés sin escuchar la respuesta ni ajustar tono o contenido",
        "steps": [
            _s("Presentarse y presentar", "daré información suficiente y segura al conocer a alguien", "Compara una presentación sin nombre con otra que incluye nombre preferido y propósito, sin exigir datos privados."),
            _s("Saludar según la situación", "elegiré un saludo pertinente a persona y contexto", "Contrasta entrada al curso, llamada formal y encuentro entre amigos; observa palabras, tono y distancia."),
            _s("Preguntar y pedir permiso", "formularé una petición clara que admite respuesta", "Modela «¿Puedo usar el lápiz cuando termines, por favor?» y muestra que cortesía no obliga a aceptar."),
            _s("Expresar ideas y sentimientos", "comunicaré una necesidad sin acusar", "Transforma «tú siempre molestas» en «me cuesta escuchar; necesito más espacio» dentro de un caso ficticio."),
            _s("Agradecer, reparar y pedir perdón", "usaré fórmulas acompañadas de una acción coherente", "Distingue perdón automático de reconocer efecto y proponer reparación concreta."),
            _s("Elegir la respuesta social", "adaptaré un intercambio completo a una situación", "En estaciones, resuelve presentación, solicitud, desacuerdo y reparación; observadores registran claridad y respeto, no personalidad."),
        ],
    },
    "LE01 OA 23": {
        "topic": "Expresión oral coherente, descriptiva y audible sobre temas de interés",
        "explanation": "Hablar ante otros se construye planificando ideas, organizando un evento o información, usando detalles y vocabulario preciso, y ensayando voz y postura como recursos de comunicación, no como rasgos personales.",
        "prerequisites": "Relatar oralmente una experiencia o tema en dos o tres ideas relacionadas.",
        "vocabulary": "tema, inicio, secuencia, descripción, detalle, vocabulario, pronunciación, volumen, postura y audiencia",
        "materials": "Organizadores visuales, imágenes de apoyo, tarjetas de conectores, grabación opcional privada y pauta breve.",
        "misconception": "enumera detalles sin un hilo o memoriza un guion que no puede reconstruir",
        "steps": [
            _s("Elegir y delimitar un tema", "definiré de qué hablaré y qué quiero que la audiencia comprenda", "Transforma «los animales» en «cómo cuido a un perro durante un día» y elige tres ideas pertinentes."),
            _s("Organizar un evento", "narraré acciones en un orden que pueda seguirse", "Ordena inicio, hecho central y cierre de una experiencia ficticia usando primero, después y finalmente."),
            _s("Describir para hacer visible", "incorporaré frases descriptivas útiles", "Amplía «vi un pájaro» con tamaño, color, acción y lugar, retirando datos que no ayudan al tema."),
            _s("Vocabulario y pronunciación", "elegiré palabras precisas y ensayaré las difíciles", "Reemplaza palabras vagas, segmenta una palabra compleja, dilo lentamente y vuelve a integrarla en la frase."),
            _s("Presentar, escuchar y mejorar", "realizaré una presentación breve con voz y orientación adecuadas y revisaré una decisión", "Ensaya a distintas distancias sin imponer una postura única; presenta con apoyo visual y usa la devolución de la audiencia para mejorar un tramo."),
        ],
    },
    "LE01 OA 24": {
        "topic": "Uso pertinente de vocabulario nuevo en intervenciones orales",
        "explanation": "El vocabulario se consolida al oír, comprender y usar palabras en intercambios auténticos. La precisión importa más que insertar muchas palabras nuevas o corregir públicamente cada forma oral.",
        "prerequisites": "Participar en una conversación y explicar una palabra conocida mediante ejemplo.",
        "vocabulary": "vocabulario, significado, contexto, intervenir, pertinente, preciso, explicar y reformular",
        "materials": "Textos escuchados, mural de palabras, tarjetas de contexto, imágenes y objetos para conversación.",
        "misconception": "repite la palabra nueva sin comprenderla o la usa en una situación incompatible",
        "steps": [
            _s("Escuchar una palabra nueva", "notaré una palabra importante y conservaré su contexto", "Durante un relato, registra «agotado» junto a lo que hizo el personaje antes y después."),
            _s("Explicar con ejemplos", "construiré un significado accesible usando ejemplos y no ejemplos", "Compara agotado, cansado y dormido en situaciones concretas y evita definir con una sola palabra igualmente desconocida."),
            _s("Ensayar en conversación", "usaré la palabra nueva para aportar una idea pertinente", "En parejas, responde por qué un personaje está agotado y permite que el interlocutor pida aclaración."),
            _s("Reformular con precisión", "reemplazaré una expresión vaga por vocabulario aprendido", "Transforma «estaba muy así» en una frase precisa y comprueba que el significado original se conserva."),
            _s("Transferir a otro contexto", "usaré la palabra en una situación nueva y explicaré la relación", "Aplica «agotado» a una batería, una persona y una posibilidad incorrecta; justifica qué usos funcionan."),
        ],
    },
    "LE01 OA 25": {
        "topic": "Juego de roles para desarrollar lenguaje, autoestima y colaboración",
        "explanation": "Representar roles permite ensayar vocabulario, perspectivas, negociación y secuencias comunicativas en un espacio protegido. La evaluación observa lenguaje y colaboración, no talento actoral ni extroversión.",
        "prerequisites": "Participar en juego simbólico y acordar una acción simple con otra persona.",
        "vocabulary": "rol, personaje, situación, diálogo, acuerdo, turno, colaborar, improvisar y escena",
        "materials": "Tarjetas de rol y situación, objetos simbólicos seguros, telas y pauta de lenguaje y colaboración.",
        "misconception": "actúa sin escuchar a sus compañeros o convierte el rol en caricatura estereotipada",
        "steps": [
            _s("Un rol tiene propósito", "distinguiré persona, rol y acción comunicativa", "Compara cliente y bibliotecario: qué necesita cada uno, qué información posee y qué intercambio permite avanzar."),
            _s("Construir un personaje respetuoso", "elegiré voz, gesto y palabras sin caricaturizar identidades", "Crea un personaje desde intención y situación, no desde acentos, discapacidades o grupos culturales imitados."),
            _s("Improvisar escuchando", "responderé a lo que otro personaje realmente dice", "Ensaya una compra ficticia donde cambia el producto disponible; obliga a escuchar y ajustar la respuesta."),
            _s("Resolver juntos una escena", "acordaré turnos y decisiones para sostener una representación", "Un grupo planifica inicio, problema y cierre; cada rol debe aportar información necesaria."),
            _s("Representar y retroalimentar", "desempeñaré un rol y mejoraré un movimiento comunicativo", "El público identifica una frase que hizo avanzar la escena y formula una pregunta; el grupo repite un tramo mejorado."),
        ],
    },
    "LE01 OA 26": {
        "topic": "Recitación expresiva de poemas, rimas, canciones, trabalenguas y adivinanzas",
        "explanation": "Recitar con expresión combina comprensión, memoria apoyada, articulación, ritmo, entonación y presencia comunicativa. La confianza se construye con ensayo gradual y opciones de participación, no exposición forzada.",
        "prerequisites": "Repetir versos breves por eco y percibir cambios de ritmo o entonación.",
        "vocabulary": "recitar, verso, ritmo, entonación, expresión, articulación, pausa, audiencia y ensayo",
        "materials": "Selección breve con procedencia, texto ampliado, tarjetas de versos, pulso corporal y grabación opcional privada.",
        "misconception": "memoriza palabras a gran velocidad sin comunicar sentido ni articular con claridad",
        "steps": [
            _s("Comprender antes de recitar", "explicaré el sentido global y palabras clave del texto", "Lee una rima completa, reconstruye quién habla y qué ocurre antes de decidir cómo sonará."),
            _s("Ritmo y articulación", "mantendré un pulso que permita comprender las palabras", "Recita con palmas suaves, ralentiza una secuencia difícil y vuelve al ritmo sin competir por velocidad."),
            _s("Entonación y pausas", "usaré cambios de voz coherentes con sentido y puntuación", "Prueba el mismo verso como pregunta, sorpresa y secreto; elige la versión apoyada por las palabras."),
            _s("Ensayo con apoyos graduales", "recitaré usando texto, eco o pareja y retiraré una ayuda", "Ensaya primero en coro, luego por versos alternados y finalmente elige participación individual o compartida."),
            _s("Recital cuidado", "presentaré una pieza breve y reconoceré mi progreso expresivo", "Recita ante una audiencia acordada; recibe evidencia sobre claridad y expresión, y registra qué estrategia aumentó la confianza."),
        ],
    },
}


def build_language_sequence(code: str) -> dict | None:
    data = SEQUENCES.get(code)
    if not data:
        return None
    oa_number = int(code.rsplit(" ", 1)[-1])
    source = f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/lenguaje-comunicacion/1-basico/le01-oa-{oa_number:02d}"
    lessons = []
    for index, (title, goal, example) in enumerate(data["steps"]):
        lessons.append({
            "title": title,
            "purpose": f"Construir {data['topic'].lower()} mediante «{title.lower()}», haciendo visible cómo el lenguaje produce y comunica significado.",
            "goal": f"Hoy {goal}.",
            "opening": f"Presenta dos respuestas o textos breves relacionados con «{title.lower()}»: uno ayuda a comprender y otro contiene el problema «{data['misconception']}». Cada estudiante elige y explica una primera pista antes del modelado.",
            "model": example,
            "guided": f"Resuelven un caso semejante por turnos: primero señalan una pista oral, escrita o visual; después explican la decisión vinculada a la meta «{goal}». El docente retroalimenta significado y estrategia, no rapidez.",
            "independent": f"Cada estudiante produce una evidencia nueva de «{goal}» sin copiar el ejemplo. Puede leer, escribir, dibujar con rótulos o responder oralmente cuando esa vía conserva la demanda del OA.",
            "ticket": f"Ante un caso breve distinto, presenta una evidencia para la meta «{goal}»; señala la pista usada y revisa una decisión después de releer o escuchar nuevamente.",
            "materials": data["materials"],
            "support": "Anticipa vocabulario, reduce la extensión del texto sin cambiar su complejidad central, ofrece lectura compartida o dictado al adulto cuando corresponda y retira una ayuda a la vez.",
            "extension": f"Cambia destinatario, género, palabra, orden o punto de vista y explica cómo esa modificación afecta «{data['topic'].lower()}». Exige una decisión nueva, no más cantidad de lo mismo.",
            "evidence": f"Producción individual vinculada a «{goal}», acompañada por la pista textual, sonora, visual o comunicativa que sostuvo la decisión.",
            "criteria": ["comunica o comprende una idea pertinente al OA", "usa una pista específica del lenguaje oral, escrito o visual", "explica o revisa una decisión con propósito"],
            "next_step": "Avanza si la evidencia conserva significado y usa una pista pertinente; ante un patrón de error, forma un grupo breve para modelar otra vía y recoge una nueva evidencia individual.",
            "short_version": "Conserva el contraste inicial, el ejemplo específico, una práctica guiada, la producción individual y el ticket. Reduce cantidad o turnos, no la comprensión, producción ni revisión.",
            "home_task": "Comparte en casa un texto, palabra o intervención breve relacionada con la meta; registra qué comprendió la otra persona o qué cambiaste para comunicar mejor. No requiere internet ni impresión.",
            "complementary": ["Recuperación: vuelve a un ejemplo oral o visual, modela una sola pista y permite un nuevo intento con menor extensión.", "Taller de errores: compara dos respuestas ficticias, localiza qué ayuda al significado y mejora solo una decisión.", "Profundización: transforma destinatario, punto de vista o género y justifica el efecto en el mensaje."],
            "difficulty_actions": [
                {"signal": "No inicia o dice que no sabe", "action": "Ofrece dos opciones de entrada, relee o vuelve a decir la consigna y modela un ejemplo diferente.", "check": "Inicia una respuesta propia y puede señalar qué debe averiguar o comunicar."},
                {"signal": data["misconception"].capitalize(), "action": "Detén la respuesta, vuelve a una pista precisa del texto, sonido, imagen o situación y piensa en voz alta.", "check": "Corrige un caso nuevo explicando la pista, no solo cambiando la respuesta."},
                {"signal": "Responde, pero no puede justificar", "action": "Pregunta dónde lo vio, oyó o decidió y ofrece una frase de apoyo que luego se retira.", "check": "Vincula la respuesta con una evidencia pertinente en un segundo caso."},
            ],
            "specialist_coordination": "El docente conduce comprensión y producción; educación diferencial o fonoaudiología, cuando corresponda al plan del estudiante, asesora acceso y comunicación sin reemplazar la enseñanza, convertir variaciones lingüísticas en déficit ni diagnosticar durante la clase.",
            "transversal": [attitude_link(oa_number, index, goal)],
        })
    return {
        "topic": data["topic"],
        "pedagogical_explanation": data["explanation"],
        "prerequisites": data["prerequisites"],
        "vocabulary": data["vocabulary"],
        "official_alignment": {
            "units": ["Progresión anual de Lenguaje y Comunicación de 1° básico"],
            "indicators": [f"Criterio interno derivado del OA: {goal}." for _, goal, _ in data["steps"][:3]],
            "source": source,
            "indicator_origin": "criterios internos derivados del OA; requieren contraste con el Programa de Estudio",
        },
        "lessons": lessons,
    }
