"""Specific eighth-grade Mathematics and Language and Literature sequences."""
from __future__ import annotations

try:
    from grade_four_math_lessons import _lesson as math_lesson
    from grade_three_math_language_lessons import (
        _lesson as language_lesson,
        build_transversal_integration as transversal_integration,
    )
    from grade_seven_core_lessons import _classroom_voice, _p, _retarget_links
except ImportError:
    from scripts.grade_four_math_lessons import _lesson as math_lesson
    from scripts.grade_three_math_language_lessons import (
        _lesson as language_lesson,
        build_transversal_integration as transversal_integration,
    )
    from scripts.grade_seven_core_lessons import _classroom_voice, _p, _retarget_links


MATH = {
    1: _p("Multiplicación y división de números enteros", "adición y sustracción de enteros, valor absoluto y operaciones con naturales", "entero, factor, producto, cociente, signo, opuesto, comprobación", "fichas positivas y negativas, recta numérica y cambios ficticios de temperatura o nivel", "memorizar la regla de signos sin poder justificarla o confundir el signo del número con la operación", ["Construir productos de enteros con patrones", "Representar la división como operación inversa", "Justificar la regla de los signos", "Resolver problemas rutinarios y no rutinarios", "Comparar y comprobar procedimientos"]),
    2: _p("Multiplicación y división de números racionales", "enteros, fracciones, decimales y ubicación en la recta numérica", "racional, producto, cociente, recíproco, signo, equivalencia, estimación", "rectas numéricas, tiras fraccionarias y situaciones ficticias que combinan −1,5, 3/4 y −2", "operar primero valores absolutos y asignar el signo al azar o perder la unidad de referencia", ["Representar racionales y anticipar el signo", "Multiplicar racionales en distintas notaciones", "Dividir racionales e interpretar el cociente", "Resolver y comprobar problemas mixtos"]),
    3: _p("Potencias y potencias de potencias", "multiplicación reiterada, base natural y exponentes naturales", "potencia, base, exponente, producto, cociente, potencia de una potencia", "cubos encajables, diagramas de área y tarjetas como (2³)², 2³·2² y 2⁶", "multiplicar exponentes en cualquier producto o multiplicar la base por el exponente", ["Construir potencias de manera concreta", "Explicar productos y cocientes de potencias", "Formar una potencia de una potencia", "Comparar procedimientos y verificar exponentes"]),
    4: _p("Raíces cuadradas y estimación", "área de cuadrados, potencias de exponente dos y recta numérica", "raíz cuadrada, cuadrado perfecto, estimación, lado, área, intervalo", "cuadrados de 1, 4, 9, 16 y 25 unidades, papel cuadriculado y una recta de 0 a 10", "dividir el número por dos o creer que toda raíz cuadrada es un número natural", ["Relacionar área y raíz cuadrada", "Reconocer cuadrados perfectos", "Estimar raíces entre enteros", "Aplicar raíces en situaciones geométricas"]),
    5: _p("Variaciones porcentuales", "porcentaje de una cantidad, fracciones equivalentes y proporcionalidad", "porcentaje, aumento, disminución, variación, valor inicial, valor final, tasa", "cuadrículas de cien y precios o ahorros ficticios claramente rotulados como simulación", "sumar el porcentaje como si fueran unidades o aplicar aumentos y descuentos sucesivos sobre el mismo total", ["Representar aumentos y disminuciones", "Calcular el valor final desde el inicial", "Reconstruir una variación porcentual", "Resolver y evaluar situaciones sucesivas"]),
    6: _p("Operaciones y factorización de expresiones algebraicas", "términos semejantes, distributividad y área de rectángulos", "expresión, término, coeficiente, distributividad, factor común, factorización", "baldosas algebraicas y rectángulos de lados x+2, 2x y x−1", "sumar términos no semejantes o creer que factorizar cambia el valor de la expresión", ["Representar sumas y productos algebraicos", "Aplicar la distributividad", "Relacionar expresiones con áreas y volúmenes", "Extraer factor común y comprobar equivalencia"]),
    7: _p("Noción de función y cambio lineal", "tablas, pares ordenados, proporcionalidad y plano cartesiano", "función, entrada, salida, variable, regla, tabla, gráfica, cambio", "máquinas de entrada y salida, tablas y gráficas para y=2x, y=x+3 y relaciones no funcionales", "creer que cualquier tabla es función o confundir la regla con una lista de resultados", ["Reconocer dependencia entre variables", "Construir tablas desde una regla", "Representar funciones en el plano", "Comparar reglas y cambios", "Modelar una situación y justificar el dominio"]),
    8: _p("Modelación con ecuaciones lineales", "operaciones inversas, distributividad y equivalencia", "ecuación, incógnita, coeficiente, equivalencia, solución, modelar, comprobar", "balanzas y tarjetas para ax+b=c, a(x+b)=c y ax+b=cx+d", "trasponer términos sin conservar la igualdad o resolver símbolos sin volver al contexto", ["Traducir situaciones a ecuaciones", "Resolver ecuaciones de dos pasos", "Resolver con incógnita en ambos miembros", "Resolver ecuaciones con paréntesis", "Modelar, interpretar y comprobar"]),
    9: _p("Inecuaciones con coeficientes racionales", "orden en la recta, ecuaciones y operaciones con racionales", "inecuación, desigualdad, conjunto solución, intervalo, frontera, comprobar", "rectas numéricas y restricciones ficticias de capacidad, tiempo o presupuesto", "dar un único número como solución o invertir el signo sin relacionarlo con una multiplicación negativa", ["Interpretar desigualdades en contexto", "Resolver y representar inecuaciones", "Examinar el efecto de coeficientes negativos", "Comprobar valores y comunicar el conjunto solución"]),
    10: _p("Función afín y cambio constante", "función lineal, tablas, gráficas y ecuaciones", "función afín, pendiente, intercepto, cambio constante, traslación, interés simple", "planes ficticios con cargo fijo y costo por uso, tablas y planos cartesianos", "confundir pendiente con valor inicial o asumir proporcionalidad cuando la gráfica no pasa por el origen", ["Distinguir función lineal y afín", "Relacionar tabla, regla y gráfica", "Interpretar pendiente e intercepto", "Trasladar una función lineal", "Resolver y evaluar modelos afines"]),
    11: _p("Área y volumen de prismas y cilindros", "áreas de polígonos, circunferencia y redes de cuerpos", "prisma, cilindro, red, área lateral, área total, volumen, base, altura", "envases limpios, redes de prismas y cilindros de papel con medidas explícitas", "sumar aristas para hallar superficie o usar área de base sin multiplicar por la altura", ["Estimar superficie y volumen", "Desplegar redes y derivar el área", "Derivar el volumen desde capas", "Comparar prismas y cilindros", "Resolver problemas y controlar unidades"]),
    12: _p("Teorema de Pitágoras", "áreas de cuadrados, triángulos rectángulos y raíces cuadradas", "cateto, hipotenusa, triángulo rectángulo, cuadrado, teorema, distancia", "triángulos recortables 3-4-5 y cuadrados construidos sobre sus lados", "usar el teorema en cualquier triángulo o llamar hipotenusa al lado que se ve inclinado", ["Explorar áreas sobre los lados", "Explicar la relación pitagórica", "Calcular lados desconocidos", "Aplicar y verificar en problemas"]),
    13: _p("Traslaciones, rotaciones y reflexiones", "vectores, coordenadas y simetría", "transformación, vector, traslación, rotación, centro, ángulo, reflexión, eje", "figuras en un plano de −8 a 8, papel transparente y tarjetas de transformación", "describir solo la figura final sin precisar vector, centro, ángulo o eje", ["Describir traslaciones con vectores", "Construir reflexiones en los ejes", "Construir rotaciones desde un centro", "Relacionar reglas y coordenadas", "Comprobar invariantes"]),
    14: _p("Composición de transformaciones y simetrías", "transformaciones isométricas, coordenadas y propiedades de polígonos", "composición, isometría, simetría, teselación, polígono, poliedro", "diseños geométricos originales y secuencias de dos transformaciones sobre cuadrícula", "suponer que el orden de las transformaciones nunca altera el resultado", ["Componer dos transformaciones", "Comparar el efecto del orden", "Analizar simetrías de polígonos", "Crear y justificar un diseño geométrico"]),
    15: _p("Percentiles, cuartiles y diagramas de caja", "orden de datos, mediana y comparación de distribuciones", "percentil, cuartil, mediana, mínimo, máximo, rango intercuartílico, diagrama de caja", "dos conjuntos ficticios de tiempos de traslado con igual mediana y distinta dispersión", "interpretar un percentil como porcentaje obtenido o dibujar cajas sin ordenar los datos", ["Ubicar posiciones en datos ordenados", "Determinar cuartiles", "Construir diagramas de caja", "Interpretar población sobre y bajo un percentil", "Comparar distribuciones con cautela"]),
    16: _p("Evaluación crítica de gráficos", "frecuencias, porcentajes, escalas y tipos de gráfico", "escala, eje, intervalo, truncamiento, proporción, manipulación, fuente", "un mismo conjunto de datos en barras, líneas y sectores, incluida una escala truncada", "elegir el gráfico más vistoso o aceptar una diferencia exagerada por el eje", ["Comparar representaciones de los mismos datos", "Reconocer fortalezas y límites", "Detectar escalas manipuladoras", "Reconstruir una representación honesta", "Comunicar una evaluación crítica", "Diseñar y auditar un gráfico"]),
    17: _p("Principio combinatorio multiplicativo", "conteo sistemático, tablas, árboles y probabilidad simple", "combinación, etapa, opción, árbol, tabla, producto, evento compuesto", "tarjetas con 3 rutas, 2 horarios y 4 opciones de material para formar decisiones compuestas", "sumar opciones de etapas sucesivas o contar dos veces la misma combinación", ["Enumerar combinaciones concretas", "Organizar tablas y árboles regulares", "Explicar el principio multiplicativo", "Calcular probabilidades de eventos compuestos"]),
}


LANGUAGE = {
    1: _p("Trayectoria lectora autónoma", "selección de textos según preferencias, desafíos y propósitos", "propósito, criterio, catálogo, muestra, desafío, bitácora", "un catálogo diverso de obras completas, fragmentos autorizados y textos informativos con procedencia", "elegir solo por extensión o confundir autonomía con leer sin metas ni conversación", ["Reconocer propósitos y desafíos lectores", "Explorar y comparar opciones", "Justificar una selección", "Planificar una lectura sostenible", "Registrar avances y obstáculos", "Recomendar desde una experiencia situada"]),
    2: _p("Literatura y experiencia humana", "interpretación literaria con evidencia y conversación respetuosa", "experiencia humana, herencia cultural, perspectiva, dilema, contexto, evidencia", "obras o fragmentos de procedencia identificada sobre poder, justicia, pertenencia y transformación", "reducir la obra a una enseñanza única o exigir relatos autobiográficos al curso", ["Reconocer dimensiones de la experiencia", "Distinguir tema, situación y juicio", "Comparar perspectivas", "Relacionar obra y herencia cultural", "Conversar sin exponer intimidad", "Construir una reflexión fundamentada"]),
    3: _p("Análisis de narraciones y evolución de personajes", "conflicto, narrador, tiempo y caracterización", "conflicto, evolución, narrador, personaje tipo, símbolo, tópico, prejuicio, anacronía", "un relato original con conflicto, personaje cambiante, símbolo recurrente y hechos fuera de orden", "resumir la trama sin explicar evolución, recursos temporales o relación entre fragmento y totalidad", ["Delimitar conflictos y fuerzas", "Analizar evolución y relaciones", "Vincular fragmento y totalidad", "Distinguir narrador y autor", "Examinar tipos, símbolos y tópicos", "Analizar prejuicios y mundo actual", "Reconstruir tiempo y comparar textos"]),
    4: _p("Análisis de poemas: imagen, repetición y efecto", "lenguaje figurado, ritmo y lectura expresiva", "hablante, imagen, lenguaje figurado, repetición, ritmo, sonoridad, efecto", "poemas originales o de dominio público con imágenes sensoriales y repeticiones contrastadas", "enumerar recursos sin explicar su efecto o identificar al hablante con el autor", ["Escuchar y registrar primeras imágenes", "Analizar apelación a los sentidos", "Interpretar lenguaje figurado", "Examinar repeticiones estructurales", "Relacionar sonido y estado de ánimo", "Comparar poemas", "Construir una interpretación"]),
    5: _p("Texto dramático y representación teatral", "conflicto, personaje y lectura de diálogos", "acotación, diálogo, conflicto dramático, personaje tipo, símbolo, puesta en escena", "una escena original en papel y dos propuestas de puesta en escena con decisiones distintas", "confundir obra dramática con montaje teatral o explicar personajes sin atender acciones y dichos", ["Reconocer conflicto y estructura dramática", "Analizar acciones y dichos", "Examinar personajes tipo y símbolos", "Analizar prejuicios y creencias", "Distinguir texto y puesta en escena", "Comparar decisiones teatrales", "Interpretar el desenlace"]),
    6: _p("Epopeya, héroe y contexto", "relatos extensos, conflicto y búsqueda de información contextual", "epopeya, héroe, hazaña, invocación, comunidad, oralidad, contexto", "fragmentos de epopeyas de dominio público o versiones autorizadas con ficha de procedencia", "tratar toda aventura extensa como epopeya o juzgar al héroe sin considerar los valores de su contexto", ["Reconocer rasgos épicos", "Analizar héroe, conflicto y comunidad", "Examinar recursos de la narración", "Investigar contexto y transmisión", "Interpretar críticamente valores y límites"]),
    7: _p("Comedia teatral y crítica social", "género dramático, conflicto y recursos humorísticos", "comedia, equívoco, ironía, exageración, personaje tipo, crítica, puesta en escena", "una escena cómica original y un fragmento de dominio público con contexto identificado", "creer que comedia significa solo final feliz o reproducir estereotipos para provocar risa", ["Reconocer mecanismos de la comedia", "Analizar conflicto y equívoco", "Examinar personajes tipo sin naturalizarlos", "Relacionar humor y crítica", "Interpretar desde su contexto"]),
    8: _p("Interpretación literaria y visión de mundo", "análisis integrado de narración, poesía o drama", "interpretación, dilema, postura, visión de mundo, contexto histórico, evidencia", "dos pasajes literarios con un dilema y una ficha contextual breve de fuente verificable", "convertir una preferencia en interpretación o usar el contexto para reemplazar la evidencia textual", ["Formular una pregunta interpretativa", "Relacionar experiencia y evidencia sin autobiografía obligatoria", "Analizar un dilema", "Construir una postura", "Vincular obra y visión de mundo", "Revisar con contexto"]),
    10: _p("Lectura crítica comparada de medios", "hechos, opiniones, propósitos y recursos multimodales", "propósito, hecho, opinión, estereotipo, suficiencia, encuadre, fuente", "noticia, reportaje y publicación social ficticios sobre un mismo hecho con datos e imágenes contrastadas", "atribuir intenciones sin evidencia o comparar solo titulares sin revisar información y fuentes", ["Reconocer propósitos explícitos e implícitos", "Distinguir hechos y opiniones", "Examinar estereotipos y prejuicios", "Evaluar suficiencia de información", "Analizar imágenes, tablas y mapas", "Comparar fuentes", "Publicar una evaluación fundamentada"]),
    11: _p("Textos no literarios para contextualizar lecturas", "búsqueda acotada y relación entre fuentes", "contextualizar, antecedente, fuente, concepto, relación, límite", "una obra breve y dos fuentes informativas con autoría, fecha y alcances distintos", "usar el contexto para explicar por completo la obra o incorporar datos que no dialogan con el pasaje", ["Formular una necesidad de contexto", "Seleccionar información pertinente", "Relacionar fuente y pasaje", "Reconocer límites", "Comunicar una comprensión enriquecida"]),
    12: _p("Estrategias de comprensión y multimodalidad", "resumen, formulación de preguntas y lectura de relaciones entre modos", "propósito, resumen, pregunta, complementariedad, contradicción, imagen, sonido", "un reportaje multimodal original con texto, gráfico, imagen y breve transcripción sonora", "aplicar estrategias como lista mecánica o asumir que imagen y sonido solo decoran", ["Definir propósito", "Resumir relaciones centrales", "Formular preguntas productivas", "Analizar complementariedad", "Detectar tensión o contradicción", "Evaluar la estrategia utilizada"]),
    13: _p("Escritura creativa y decisiones de autor", "géneros diversos, audiencia y revisión", "tema, género, destinatario, voz, escena, imagen, borrador", "detonantes, restricciones y destinatarios ficticios para cuento, crónica, diario, carta o poema", "seguir una plantilla que borra la voz o corregir ortografía antes de desarrollar el texto", ["Elegir tema, género y destinatario", "Probar voz y forma", "Desarrollar un núcleo significativo", "Compartir y recibir preguntas", "Revisar para circular"]),
    14: _p("Escritura explicativa con fuentes", "organización temática, paráfrasis y referencias", "explicación, progresión, anáfora, ejemplo, fuente, referencia, recurso gráfico", "miniarchivo de tres fuentes sobre un fenómeno cultural o científico y una plantilla flexible de planificación", "pegar información por fuente sin construir progresión o usar imágenes que no explican", ["Delimitar tema y subtemas", "Seleccionar y parafrasear fuentes", "Desarrollar con hechos y ejemplos", "Construir progresión y referencias claras", "Integrar recursos gráficos", "Revisar cierre y referencias"]),
    15: _p("Escritura persuasiva breve", "tesis, evidencia y coherencia temática", "afirmación, audiencia, evidencia, razón, pertinencia, coherencia, cierre", "cartas al director y críticas literarias originales sobre asuntos escolares no sensibles", "acumular opiniones sin evidencia o cambiar de tema para intensificar el tono", ["Formular una afirmación precisa", "Seleccionar evidencia pertinente", "Relacionar razones y evidencia", "Sostener coherencia temática", "Revisar para una audiencia", "Publicar y justificar decisiones"]),
    16: _p("Proceso de escritura y adecuación al contexto", "planificación, borrador, revisión y edición", "registro, destinatario, propósito, cohesión, conector, concordancia, edición", "un borrador original con problemas reales de registro, organización, pronombres y concordancia", "corregir solo tildes o convertir toda revisión en sustitución por palabras más formales", ["Recopilar y organizar ideas", "Adecuar registro y persona", "Asegurar coherencia y cohesión", "Revisar oraciones y concordancia", "Editar ortografía y presentación", "Documentar cambios y publicar"]),
    17: _p("Oraciones complejas y coherencia temporal", "sujeto, predicado, conectores y tiempos verbales", "oración compleja, referente, sujeto, subordinación, tiempo verbal, coherencia", "pares de oraciones ambiguas y un párrafo con sujeto distante y saltos temporales", "creer que una oración larga es compleja o agregar conectores sin aclarar relaciones", ["Reconocer relaciones entre proposiciones", "Mantener referente claro", "Conservar coherencia temporal", "Ubicar y recuperar el sujeto", "Revisar oraciones en un texto"]),
    18: _p("Correferencia, elipsis y claridad", "pronombres, referentes y cohesión", "correferencia, deíctico, pronombre tónico, pronombre átono, nominalización, elipsis", "un texto original con referentes competidores, repeticiones y elipsis ambiguas", "reemplazar todo sustantivo por pronombres o eliminar repeticiones aunque se pierda el referente", ["Rastrear cadenas de referencia", "Usar pronombres tónicos y átonos", "Aplicar sustitución y nominalización", "Evaluar elipsis", "Revisar claridad y estilo", "Justificar decisiones de cohesión"]),
    19: _p("Modos verbales y efecto persuasivo", "tiempos verbales, intención y audiencia", "indicativo, subjuntivo, imperativo, posibilidad, certeza, exhortación", "tres versiones de una misma invitación que cambian únicamente el modo verbal", "asociar un modo a un único significado o cambiar el verbo sin revisar el efecto global", ["Reconocer modos en contexto", "Comparar certeza y posibilidad", "Analizar exhortación", "Seleccionar modo según propósito", "Reescribir y evaluar efectos", "Integrar modos en un texto persuasivo"]),
    20: _p("Ortografía y puntuación al servicio del lector", "reglas literales, acentuación y revisión", "ortografía literal, acentuación, punto, coma, raya, dos puntos, fuente de consulta", "un texto original con errores que alteran pausas, voces y relaciones entre ideas", "corregir por apariencia o usar comas donde se escucha cualquier pausa", ["Diagnosticar errores que afectan comprensión", "Aplicar reglas y consultar dudas", "Usar punto y coma con intención", "Puntuar diálogos y enumeraciones", "Editar y explicar decisiones"]),
    21: _p("Evaluación de textos orales y audiovisuales", "escucha activa, hechos, opiniones y recursos multimodales", "postura, contexto, hecho, opinión, prejuicio, punto de vista, montaje", "exposición y cápsula audiovisual originales con guion, imágenes y datos verificables", "evaluar solo fluidez o imagen sin reconstruir ideas, fuentes y puntos de vista", ["Identificar tema y conceptos", "Situar el contexto", "Distinguir hechos y opiniones", "Examinar prejuicios", "Comparar puntos de vista", "Analizar imagen, texto y sonido", "Responder con postura fundamentada"]),
    22: _p("Diálogo constructivo para debatir y explorar", "escucha, turnos y fundamentación", "foco, reformulación, pregunta, fundamento, acuerdo, desacuerdo, turno", "una controversia escolar ficticia con tres posiciones, evidencias y reglas de conversación", "repetir la propia postura, esperar turno sin escuchar o buscar acuerdo borrando diferencias", ["Preparar una postura provisional", "Escuchar y reformular", "Preguntar para profundizar", "Fundamentar y responder", "Negociar acuerdos parciales", "Evaluar y mejorar el diálogo"]),
    23: _p("Exposición investigada para una audiencia", "investigación, organización oral y apoyo visual", "audiencia, progresión, recapitulación, fuente, apoyo visual, muletilla", "dossier breve con datos y fuentes para una exposición de tres minutos", "leer diapositivas o agregar imágenes decorativas sin conexión con la explicación", ["Seleccionar información fidedigna", "Organizar una progresión", "Diseñar apoyo visual pertinente", "Ensayar claridad y vocabulario", "Exponer y responder preguntas", "Revisar desde evidencia de audiencia"]),
    24: _p("Registro, desacuerdo y recursos de la oralidad", "situación comunicativa, audiencia y escucha", "registro, contexto, destinatario, volumen, velocidad, dicción, cortesía", "transcripciones y audios originales de una misma idea en conversación, entrevista y exposición", "confundir registro adecuado con hablar siempre formalmente o suavizar tanto el desacuerdo que desaparece", ["Comparar oralidad y escritura", "Reconocer registros", "Adecuar vocabulario y estructura", "Cuidar la relación al disentir", "Ajustar voz y dicción", "Evaluar el efecto en la audiencia"]),
    25: _p("Investigación sobre lenguaje y literatura", "preguntas, fuentes, registro y síntesis", "pregunta, alcance, confiabilidad, categoría, bibliografía, hallazgo, límite", "miniarchivo con catálogo, artículo, entrevista ficticia y sitio sin autor para evaluar", "coleccionar enlaces sin responder una pregunta o descartar fuentes solo porque contradicen una idea", ["Delimitar pregunta y alcance", "Buscar con palabras clave", "Evaluar confiabilidad y suficiencia", "Descartar con criterio", "Organizar hallazgos y referencias", "Comunicar resultados y límites"]),
    26: _p("Síntesis y notas para aprender", "ideas principales, propósito y organización de información", "síntesis, idea principal, detalle, jerarquía, paráfrasis, organizador", "una explicación oral y dos textos breves sobre el mismo tema con información complementaria", "copiar frases completas o eliminar detalles indispensables para entender relaciones", ["Definir propósito de las notas", "Distinguir ideas y detalles", "Parafrasear con precisión", "Integrar fuentes", "Construir y comprobar una síntesis"]),
}


def _sequence(code: str, profile: dict, subject: str) -> dict:
    is_math = subject == "matematica"
    lessons = []
    for index in range(len(profile["focuses"])):
        if is_math:
            lesson = math_lesson(code, index, profile)
            _retarget_links(lesson, "MA04", "MA08")
        else:
            lesson = language_lesson(code, index, profile, "language")
            _retarget_links(lesson, "LE03", "LE08")
        _classroom_voice(lesson, profile, index, is_math)
        lessons.append(lesson)
    subject_name = "Matemática" if is_math else "Lengua y Literatura"
    return {
        "topic": profile["topic"],
        "pedagogical_explanation": (
            f"{profile['topic']} se construye desde {profile['prior'][0].lower() + profile['prior'][1:]}. "
            f"Cada clase cambia el problema, texto, representación y evidencia, y enfrenta la confusión «{profile['misconception']}»."
        ),
        "prerequisites": profile["prior"],
        "vocabulary": profile["vocabulary"],
        "official_alignment": {
            "units": [f"{subject_name} · progresión interna en {len(lessons)} clases"],
            "unit_origin": "Organización pedagógica interna derivada del eje y del OA; no se presenta como una unidad oficial del programa.",
            "indicators": [f"{focus}." for focus in profile["focuses"][:3]],
            "indicator_origin": "Criterios internos derivados del verbo, contenido y alcance del OA oficial.",
            "source": f"https://www.curriculumnacional.cl/curriculum/7o-basico-2o-medio/{subject}/8-basico/{code.lower().replace(' ', '-')}",
        },
        "lessons": lessons,
    }


def build_sequence(code: str) -> dict | None:
    if code.startswith("MA08 OA "):
        number = int(code.rsplit(" ", 1)[-1])
        return _sequence(code, MATH[number], "matematica") if number in MATH else None
    if code == "LE08 OA 09":
        return None  # Preserve the existing, hand-written seven-class pilot.
    if code.startswith("LE08 OA "):
        number = int(code.rsplit(" ", 1)[-1])
        return _sequence(code, LANGUAGE[number], "lengua-literatura") if number in LANGUAGE else None
    return None


def build_transversal_integration(item: dict) -> dict:
    return transversal_integration(item)


SEQUENCES = {
    **{f"MA08 OA {number:02d}": True for number in MATH},
    **{f"LE08 OA {number:02d}": True for number in LANGUAGE},
}
