"""Curated second-grade Visual Arts, Music and Physical Education sequences."""
from __future__ import annotations


def _steps(value: str) -> list[tuple[str, str, str]]:
    return [tuple(part.strip() for part in row.split("|", 2)) for row in value.split(";")]


ART_ATTITUDES = (
    ("de Actitud AR02 OAA A", "disfrute de expresiones artísticas diversas"),
    ("de Actitud AR02 OAA B", "disposición a expresar ideas y sentimientos visualmente"),
    ("de Actitud AR02 OAA C", "valoración y cuidado del patrimonio artístico"),
    ("de Actitud AR02 OAA D", "creatividad mediante experimentación y pensamiento divergente"),
    ("de Actitud AR02 OAA E", "colaboración y recepción de consejos pertinentes"),
    ("de Actitud AR02 OAA F", "valoración del trabajo riguroso y el esfuerzo"),
    ("de Actitud AR02 OAA G", "originalidad y respeto por el trabajo artístico ajeno"),
)
MUSIC_ATTITUDES = (
    ("de Actitud MU02 OAA A", "curiosidad y disfrute de sonidos y músicas"),
    ("de Actitud MU02 OAA B", "confianza progresiva al compartir música"),
    ("de Actitud MU02 OAA C", "comunicación de percepciones, ideas y sentimientos"),
    ("de Actitud MU02 OAA D", "valoración de estilos y expresiones musicales diversas"),
    ("de Actitud MU02 OAA E", "reconocimiento respetuoso de dimensiones espirituales o trascendentes sin imponer creencias"),
    ("de Actitud MU02 OAA F", "creatividad mediante juego, experimentación e imaginación"),
    ("de Actitud MU02 OAA G", "participación y colaboración respetuosa"),
)
PE_ATTITUDES = (
    ("de Actitud EF02 OAA A", "valoración de efectos positivos de la actividad física regular"),
    ("de Actitud EF02 OAA B", "interés por mejorar la propia condición física de manera progresiva"),
    ("de Actitud EF02 OAA C", "confianza para probar y ajustar habilidades motrices"),
    ("de Actitud EF02 OAA D", "participación activa mediante vías accesibles"),
    ("de Actitud EF02 OAA E", "participación equitativa de niñas y niños"),
    ("de Actitud EF02 OAA F", "respeto por la diversidad corporal sin comparaciones ni discriminación"),
    ("de Actitud EF02 OAA G", "colaboración y recepción de retroalimentación"),
    ("de Actitud EF02 OAA H", "esfuerzo personal, superación y perseverancia"),
)


AR = {
"AR02 OA 01": ("Creación visual desde entornos y obras diversas", "Observar formas, colores y detalles antes de dibujar o construir.", "observación, figura humana, paisaje, patrimonio, obra, punto de vista e interpretación", "Imágenes con procedencia, espejos opcionales, papeles, lápices, pinturas y material reutilizable limpio.", "copiar literalmente una imagen adulta o representar personas mediante estereotipos", _steps("Figura humana en acción|observaré postura y articulaciones para crear una figura con movimiento|Compara dos poses y construye una figura con líneas de acción, sin exigir proporciones adultas;Paisaje chileno desde un encuadre|seleccionaré un punto de vista y organizaré primer plano, fondo y horizonte|Observa costa, valle o cordillera en una fuente y crea otro encuadre sin copiarla;Personas y vida cotidiana|representaré una escena evitando roles y rasgos estereotipados|Elige una acción comunitaria y decide gestos, objetos y relaciones que la hagan comprensible;Patrimonio como punto de partida|transformaré un detalle patrimonial en una creación propia|Observa textura, forma o patrón de una obra o edificio chileno y úsalo sin reproducir símbolos ceremoniales;Obras de Chile y Latinoamérica|compararé decisiones visuales y tomaré una como inspiración declarada|Contrasta color, composición o materialidad de dos obras identificadas y crea una respuesta personal;Ventana al arte del mundo|crearé una obra que dialogue con una referencia sin imitar su estilo completo|Elige una decisión de una obra universal, cámbiala con un tema propio y explica la relación")),
"AR02 OA 02": ("Línea, color y forma geométrica en la creación", "Reconocer colores primarios y formas geométricas en el entorno.", "línea vertical, horizontal, diagonal, espiral, quebrada, color primario, secundario y forma geométrica", "Témperas o lápices, recipientes, pinceles, papeles, reglas opcionales y protección de mesas.", "usar los elementos como ejercicio decorativo sin relacionarlos con una intención visual", _steps("Líneas con dirección y carácter|usaré tipos de línea para producir recorrido o sensación|Crea caminos verticales, diagonales, espirales y quebrados que guíen la mirada de manera distinta;Mezclas secundarias|produciré colores secundarios desde pares de primarios y registraré la mezcla|Compara proporciones de amarillo y azul sin buscar un único verde correcto;Contrastes de color|elegiré colores para destacar, acercar o separar una forma|Diseña una señal visual donde una figura deba verse primero;Formas que construyen imágenes|combinaré formas geométricas para crear una figura no estereotipada|Transforma círculos, triángulos y rectángulos en una máquina o criatura propia;Composición integrada|coordinaré línea, color y forma para comunicar una intención|Crea una escena de calma o movimiento y explica qué decisión visual sostiene el efecto")),
"AR02 OA 03": ("Exploración de materiales, herramientas y procedimientos", "Usar lápiz, pintura, papel y tijera con cuidado básico.", "materialidad, herramienta, procedimiento, textura, unión, modelado, collage y prueba", "Arcilla o masa, cartón, papeles, textiles, elementos naturales caídos, pegamento y herramientas seguras.", "elegir materiales sólo por gusto o comenzar el producto final sin ensayar uniones y procedimientos", _steps("Modelar volumen y huella|exploraré presión, unión y textura en un material moldeable|Crea tres pruebas de huella y dos tipos de unión antes de modelar una forma expresiva;Reciclar con estructura|transformaré material limpio considerando resistencia y equilibrio|Construye un pequeño ser u objeto que se sostenga y registra qué unión falló;Papeles y textiles en collage|superpondré, recortaré y rasgaré para producir profundidad o contraste|Compone una emoción sin dibujar una cara, usando bordes, capas y texturas;Pintar con herramientas distintas|compararé marcas de pincel, esponja y herramienta improvisada segura|Crea un muestrario y elige dos huellas para una imagen intencionada;Dibujo digital o alternativa analógica|usaré capas, trazo o repetición para transformar una imagen propia|Crea una variante digital o con papel transparente, explica qué facilita y limita el medio")),
"AR02 OA 04": ("Apreciación y comunicación frente a obras de arte", "Expresar lo que una imagen hace sentir sin convertirlo en respuesta correcta.", "impresión, detalle, color, línea, forma, material, interpretación y pregunta", "Selección anual diversa de obras identificadas, reproducciones accesibles y materiales de respuesta.", "decir sólo me gusta/no me gusta o atribuir una intención al artista sin evidencia", _steps("Mirar antes de interpretar|describiré detalles visibles sin convertirlos aún en historia|Realiza un barrido de color, forma, gesto, material y espacio en una obra chilena;Sentir y sostener|comunicaré una impresión vinculándola con un elemento visual|Completa me produce… porque observo… y admite respuestas diferentes;Dos miradas posibles|compararé interpretaciones sin decidir que una emoción es obligatoria|Escucha dos lecturas de una obra latinoamericana y busca evidencia para cada una;Responder por otro medio|expresaré mi lectura con cuerpo, sonido, dibujo o palabras y explicaré la elección|Crea una respuesta breve a una obra universal sin copiar su imagen")),
"AR02 OA 05": ("Preferencias fundamentadas sobre trabajos de arte", "Reconocer decisiones propias y ajenas sin ordenar obras de mejor a peor.", "preferencia, criterio, lenguaje visual, decisión, retroalimentación, proceso y revisión", "Trabajos en proceso, etiquetas de autor y pauta breve de conversación.", "confundir preferencia con juicio universal o corregir la obra del compañero según el gusto propio", _steps("Nombrar lo que atrae la mirada|explicaré una preferencia usando color, línea, forma o material|Compara dos trabajos ficticios y reemplaza bonito por una observación visual precisa;Hablar del propio proceso|identificaré una decisión lograda y una que quiero revisar|Presenta prueba, cambio y resultado sin pedir que todos prefieran la versión final;Retroalimentar sin apropiarse|formularé una observación y una pregunta respetuosa|Usa veo, me pregunto, podrías probar, el autor decide si acepta la sugerencia;Curaduría con criterios|seleccionaré trabajos para una muestra y explicaré el criterio sin competir|Agrupa obras por contraste, textura o tema e incluye diversidad de soluciones")),
}


MU = {
"MU02 OA 01": ("Escucha y representación de cualidades y estructuras musicales", "Distinguir sonidos largos/cortos, fuertes/suaves y agudos/graves en contrastes claros.", "altura, timbre, intensidad, duración, pulso, acento, patrón, sección y representación", "Grabaciones autorizadas o interpretación docente, objetos sonoros, tarjetas y papel.", "confundir intensidad con altura o dibujar una historia sin representar lo escuchado", _steps("Cuatro cualidades del sonido|distinguiré altura, timbre, intensidad y duración en contrastes|Compara un golpe grave y breve con un sonido agudo y largo y representa cada rasgo;Pulso y acento|mantendré un pulso y reconoceré dónde algunos tiempos se destacan|Camina un pulso estable y marca acentos sin acelerar;Patrones que regresan|identificaré y representaré una secuencia sonora repetida|Escucha largo-corto-corto y crea una notación que otra persona pueda interpretar;Secciones musicales|reconoceré cambios y retornos entre partes|Levanta tarjetas A y B al escuchar una pieza breve y justifica un cambio")),
"MU02 OA 02": ("Expresión de sensaciones e ideas sugeridas por la música", "Escuchar una pieza breve y comunicar una impresión personal.", "sensación, emoción, idea, evidencia sonora, gesto, color, movimiento y contraste", "Músicas breves diversas, espacio de movimiento y materiales visuales.", "afirmar que una música tiene una emoción correcta o explicar sólo por letra y título", _steps("Una impresión con evidencia|relacionaré una sensación con algo que escuché|Completa me sugiere… porque cambia… usando intensidad, timbre o duración;Movimiento que responde|transformaré contraste musical en gesto, nivel o desplazamiento|Responde corporalmente a dos secciones sin representar personajes obligatorios;Imagen nacida del sonido|elegiré línea, color o forma para traducir una cualidad|Crea dos trazos para timbres diferentes y explica la correspondencia;Ideas distintas, escucha común|compararé respuestas expresivas respetando interpretaciones diversas|Observa dos dibujos de la misma pieza y encuentra la evidencia sonora de cada uno")),
"MU02 OA 03": ("Escucha abundante de músicas de contextos diversos", "Escuchar músicas variadas sin jerarquizar estilos ni culturas.", "tradición escrita, tradición oral, música popular, contexto, instrumento, voz y escucha apreciativa", "Selección legal y contextualizada de músicas breves; datos de obra, intérprete y procedencia.", "reconocer una cultura por un sonido aislado o usar exótico/primitivo como descripción", _steps("Escuchar sin etiquetar primero|describiré lo que oigo antes de conocer el contexto|Registra instrumentos, voces, pulso y cambios de una pieza breve;Tradición escrita|escucharé una pieza instrumental o vocal identificando una decisión musical|Compara dos secciones de una danza o pieza breve con información de autoría;Tradiciones orales|reconoceré música transmitida en comunidad respetando su procedencia|Escucha una ronda, canto tradicional o música de pueblo originario con fuente y contexto, sin imitar usos ceremoniales;Músicas populares|compararé timbres y patrones en una pieza infantil, jazz, rock o fusión|Construye una comparación auditiva sin declarar un estilo superior;Bitácora de veinte escuchas|registraré hallazgos a lo largo del año y elegiré una reescucha fundamentada|Ordena cuatro audiciones por un criterio musical y recomienda una citando lo audible")),
"MU02 OA 04": ("Canto al unísono y percusión coordinada", "Imitar patrones vocales y rítmicos breves cuidando la escucha.", "unísono, pulso, entrada, respiración, articulación, percusión, silencio y coordinación", "Canción adecuada y autorizada, percusión corporal e instrumentos revisados.", "cantar más fuerte para corregir desajuste o tocar continuamente sin escuchar al grupo", _steps("Una voz colectiva|cantaré al unísono cuidando entrada, respiración y final|Aprende una frase por eco y repítela sin competir por volumen;Pulso que sostiene|mantendré percusión corporal regular mientras canto|Alterna palmas y muslos con un canto conocido sin acelerar;Patrón instrumental|tocaré una secuencia breve respetando sonido y silencio|Ensaya un ostinato en instrumentos convencionales o fabricados y rota roles;Ensamble con señales|coordinaré canto, pulso y patrón siguiendo inicio, corte y dinámica|Interpreta una pieza breve y usa una pauta de escucha para ajustar una sección")),
"MU02 OA 05": ("Exploración e improvisación de ideas musicales", "Producir sonidos variados con voz, cuerpo y objetos seguros.", "exploración, improvisación, idea musical, timbre, duración, intensidad, patrón y contraste", "Voz, cuerpo, instrumentos y objetos sonoros seguros organizados por estaciones.", "hacer ruido simultáneo sin escuchar o creer que improvisar significa no acordar límites", _steps("Descubrir posibilidades|exploraré tres sonidos de una misma fuente sin dañarla|Investiga voz, papel o tambor y clasifica sonidos por timbre y duración;Pregunta y respuesta|improvisaré una respuesta que conserve o contraste un rasgo|Un compañero crea tres sonidos y otro responde manteniendo ritmo o cambiando timbre;Crear con una regla|improvisaré dentro de límites de duración, intensidad y turnos|Construye una idea de ocho pulsos con dos sonidos y un silencio;Seleccionar y recordar|elegiré una improvisación y crearé una forma de repetirla|Registra con símbolos propios, entrégala a otro grupo y revisa la notación")),
"MU02 OA 06": ("Presentación y comunicación del trabajo musical", "Compartir una interpretación breve con acuerdos de escucha y participación.", "ensayo, repertorio, audiencia, entrada, balance, presentación, retroalimentación y revisión", "Trabajo musical del curso, instrumentos, disposición segura y pauta breve.", "medir confianza por ausencia de nervios o asignar siempre roles visibles a las mismas personas", _steps("Elegir qué comunicar|definiré una pieza y qué necesita percibir la audiencia|Selecciona interpretación o creación y nombra un foco audible;Ensayar con propósito|detectaré una sección que requiere ajuste y probaré una solución|Graba o escucha desde fuera, cambia una entrada, balance o final y vuelve a probar;Roles equitativos|acordaré participación musical y tareas técnicas sin jerarquizarlas|Rota intérprete, señal, presentación y cuidado de instrumentos;Presentar y recoger evidencia|compartiré el trabajo y usaré retroalimentación sobre lo audible|La audiencia describe un rasgo escuchado y formula una pregunta, sin puntuar personas")),
"MU02 OA 07": ("Experiencias musicales y sonoras de la vida cotidiana", "Reconocer sonidos y músicas presentes en espacios cotidianos sin exigir relatos privados.", "paisaje sonoro, recuerdo, uso, contexto, fuente sonora, silencio y cuidado auditivo", "Mapa sonoro ficticio o del establecimiento, grabaciones propias autorizadas y tarjetas.", "reducir experiencia musical a gustos o pedir exposición de prácticas familiares", _steps("Mapa de sonidos cotidianos|identificaré fuentes sonoras y su ubicación o momento|Construye el paisaje de una escuela ficticia diferenciando señal, voz, música y ambiente;Músicas con funciones|describiré para qué aparece música en una situación|Compara juego, celebración, descanso y audiovisual sin asumir que todas las familias participan igual;Memoria sonora segura|comunicaré una experiencia real o inventada sin revelar información privada|Elige un sonido significativo y explica su timbre, duración y contexto;Cuidado y elección|reflexionaré sobre volumen, silencio y convivencia sonora|Analiza un patio ruidoso y propone una acción que cuide escucha sin eliminar el juego")),
}


EF = {
"EF02 OA 01": ("Locomoción, manipulación y estabilidad combinadas", "Desplazarse, detenerse y mantener equilibrio en superficies seguras.", "locomoción, manipulación, estabilidad, dirección, nivel, equilibrio, bote y recepción", "Conos, líneas, balones blandos, colchonetas y bases bajas revisadas.", "priorizar velocidad o altura sobre control, seguridad y progresión individual", _steps("Saltos alternados con control|saltaré de un pie al otro manteniendo dirección y caída estable|Recorre marcas cercanas, congela cada tercera caída y ajusta distancia;Botear mientras avanzo|coordinaré bote y caminata mirando el espacio disponible|Usa balón adecuado, cambia mano cuando sea accesible y conserva distancia de seguridad;Equilibrio en base baja|mantendré estabilidad y bajaré de forma controlada|Cruza una línea o banco muy bajo con apoyos progresivos y salida acordada;Suspender y girar con seguridad|probaré suspensión o giro en una estación supervisada|Sostén brevemente, libera con control y gira sobre eje sin empujar a otros;Rodar y combinar|realizaré una rodada o volteo progresivo y enlazaré dos habilidades|En colchoneta y con modelado, elige variante accesible y crea secuencia desplazamiento-equilibrio-rodada")),
"EF02 OA 02": ("Soluciones motrices a problemas de representación", "Seguir consignas espaciales simples y proponer más de una respuesta corporal.", "problema motor, agrupación, forma, símbolo, nivel, espacio y solución", "Tarjetas de figuras, cuerdas, conos y espacio demarcado.", "copiar al estudiante más rápido o tratar una única figura exacta como solución correcta", _steps("Agruparse con condiciones|resolveré una consigna de cantidad y espacio colaborando|Forma grupos de cuatro que ocupen dos niveles sin levantar compañeros;Dibujar con el cuerpo|representaré letras, números o símbolos usando líneas corporales|Crea una figura legible desde un punto acordado y explica el punto de vista;Transformar una forma|cambiaré una figura sin desarmar por completo el grupo|Pasa de triángulo a letra A conservando dos apoyos comunes;Comparar soluciones|probaré dos respuestas motrices y evaluaré estabilidad, claridad y seguridad|Observa representaciones distintas del mismo símbolo y mejora una según criterios")),
"EF02 OA 03": ("Juegos con oposición, colaboración y persecución", "Comprender reglas simples y detenerse ante una señal.", "juego, regla, oposición, colaboración, persecución, estrategia, espacio y juego limpio", "Petos o cintas, conos, balones blandos y tarjetas de reglas.", "confundir oposición con contacto brusco o excluir a quienes tienen distinto desempeño", _steps("Perseguir y escapar con límites|cambiaré dirección cuidando espacio y señal de detención|Juega en zonas amplias con toque suave acordado y pausas para mirar trayectorias;Cooperar por una meta|coordinaré acciones con otros sin que una persona haga todo|Transporta objetos con reglas que obliguen a rotar roles y maneras de desplazarse;Oposición sin contacto riesgoso|protegeré un espacio u objeto usando posición y anticipación|Intercepta pases con balón blando sin arrebatar de las manos;Elegir y adaptar un juego|compararé reglas y propondré un ajuste para participación equitativa|Modifica espacio, tiempo o implemento y comprueba si aumenta participación real")),
"EF02 OA 04": ("Habilidades motrices en entornos y rutas guiadas", "Reconocer límites, superficies y señales antes de moverse.", "entorno, ruta, mapa, símbolo, referencia, superficie, riesgo y adaptación", "Plano simple, señales, conos y materiales adecuados al entorno autorizado.", "trasladar el mismo movimiento a cualquier superficie sin observar riesgos", _steps("Leer una ruta motriz|interpretaré símbolos y referencias antes de iniciar|Sigue un plano del patio con caminar, saltar y rodear, comprobando cada estación;Adaptarse al entorno|ajustaré zancada, velocidad o apoyo según superficie y espacio|Compara pasto, arena simulada y piso regular sin realizar acciones riesgosas;Orientarse con señales|usaré puntos de referencia para elegir dirección|Encuentra estaciones mediante colores, flechas y referentes fijos, no siguiendo al grupo;Diseñar una ruta segura|crearé un recorrido con secuencia, límites y alternativa accesible|Otro equipo prueba el mapa y marca un símbolo ambiguo o un riesgo")),
"EF02 OA 05": ("Expresión corporal de ideas, sensaciones y emociones", "Explorar movimientos en distintos niveles, direcciones y ritmos sin imitar cuerpos ajenos.", "expresión corporal, espacio, nivel, dirección, ritmo, intensidad, gesto y secuencia", "Músicas autorizadas o pulsos, telas opcionales y espacio despejado.", "representar emociones con caricaturas fijas o evaluar expresividad por desinhibición", _steps("Calidades de movimiento|variaré peso, fluidez y velocidad para expresar contrastes|Explora pesado/liviano y continuo/cortado sin asignar emoción obligatoria;Espacio y trayectoria|usaré niveles y direcciones para transformar una idea|Representa crecer o buscar mediante recorridos distintos y explica elecciones;Ritmo e intensidad|ajustaré movimiento a cambios sonoros sin copiar una coreografía|Responde a pulso lento, rápido, fuerte y suave con seguridad espacial;Componer y compartir|crearé una secuencia breve con inicio, cambio y cierre|Presenta solo, en pareja o grupo y recibe descripciones de lo observado, no juicios personales")),
"EF02 OA 06": ("Actividad moderada y vigorosa mediante juegos y circuitos", "Distinguir reposo, esfuerzo moderado y esfuerzo vigoroso por sensaciones propias.", "intensidad, moderada, vigorosa, circuito, esfuerzo, pausa, recuperación y autorregulación", "Conos, cuerdas, pelotas, escala de esfuerzo visual y agua disponible.", "igualar mayor intensidad con mejor desempeño o exigir el mismo ritmo a todos", _steps("Reconocer intensidades|clasificaré esfuerzos usando respiración y posibilidad de hablar|Compara caminar activo, trotar y saltar sin comparar pulsos entre personas;Circuito con estaciones|mantendré actividad en tiempos breves y transiciones seguras|Rota por desplazamiento, lanzamiento, equilibrio y cuerda con variantes;Regular y recuperar|ajustaré ritmo y usaré pausas cuando las señales corporales lo indiquen|Ensaya bajar intensidad sin detener abruptamente y describe recuperación;Juego continuo e inclusivo|participaré en un juego que sostenga movimiento moderado o vigoroso|Modifica espacio y reglas para reducir filas y tiempos de eliminación")),
"EF02 OA 07": ("Actividad física regular en la vida cotidiana", "Reconocer juegos activos y oportunidades de movimiento accesibles.", "frecuencia, rutina, juego tradicional, caminata, cuerda, descanso y barrera", "Tarjetas de actividades, calendario ficticio y alternativas sin equipamiento.", "convertir cinco veces por semana en exigencia idéntica o responsabilizar al niño por barreras familiares", _steps("Muchas maneras de estar activo|clasificaré juegos y actividades por movimiento e intensidad|Compara luche, cuerda, caminata y juego de persecución con variantes accesibles;Frecuencia sin competencia|organizaré oportunidades semanales alternando actividad y recuperación|Diseña un calendario ficticio de cinco momentos breves sin registrar peso ni calorías;Barreras y alternativas|propondré opciones ante clima, espacio, tiempo o implementos|Transforma una caminata exterior en circuito seguro interior y una cuerda en secuencia sin salto;Plan personal o ficticio|elegiré actividades agradables, seguras y posibles|Crea una propuesta que incluya elección, apoyo adulto cuando corresponda y derecho a ajustar")),
"EF02 OA 08": ("Sensaciones y respuestas corporales al esfuerzo", "Nombrar sensaciones propias antes, durante y después de moverse.", "respiración, sudor, temperatura, color de piel, cansancio, habla, esfuerzo y recuperación", "Escala visual de esfuerzo, tarjetas de palabras y actividad breve regulable.", "tratar todas las respuestas como iguales o diagnosticar salud a partir de una clase", _steps("Antes y después|observaré cambios propios sin compararlos con los de otros|Registra respiración, temperatura percibida y habla antes y después de un juego;Respiración y habla|usaré la prueba del habla como señal aproximada de intensidad|Compara hablar cómodamente, por frases o con dificultad y reduce esfuerzo cuando corresponda;Sudor, calor y color|describiré respuestas normales reconociendo diversidad corporal|Analiza registros ficticios y evita usar rubor o sudor como medida universal;Recuperación y alerta|distinguiré cansancio esperable de señales para detenerse y avisar|Practica parar, ubicarse seguro y comunicar dolor, mareo o falta de aire inusual")),
"EF02 OA 09": ("Higiene, postura y alimentación alrededor de la actividad física", "Aplicar rutinas básicas de cuidado sin moralizar cuerpos o alimentos.", "higiene, postura, hidratación, colación, energía, recuperación, hábito y autocuidado", "Agua, jabón disponible, imágenes de posturas y tarjetas de colaciones posibles.", "presentar alimentos como buenos/malos o exigir una postura rígida idéntica todo el tiempo", _steps("Higiene después de moverse|aplicaré lavado de manos y cara en momentos pertinentes|Ordena una rutina que evite compartir toallas y desperdicie menos agua;Posturas que permiten moverse|ajustaré alineación y apoyos según la tarea|Compara transportar, sentarse y levantar un objeto liviano sin sostener posturas forzadas;Antes de la actividad|reconoceré hidratación y colación suficiente según indicaciones adultas|Evalúa casos ficticios evitando prescribir dietas o asumir disponibilidad familiar;Después y recuperación|elegiré agua, higiene, abrigo y descanso según la situación|Diseña una secuencia posterior a la clase con opciones realistas;Integrar una rutina saludable|explicaré el propósito de cada hábito y cuándo pedir apoyo|Resuelve un día ficticio de actividad identificando cuidado, barrera y adulto responsable")),
"EF02 OA 10": ("Roles, cooperación y trabajo en equipo", "Participar en una tarea colectiva respetando turnos y acuerdos.", "equipo, rol, colaboración, liderazgo, respeto, material, rotación y retroalimentación", "Tarjetas de roles, materiales de juego y pauta de observación de acciones.", "confundir liderazgo con mandar o asignar tareas por género o habilidad percibida", _steps("Roles que sostienen el juego|distinguiré iniciar, organizar, cuidar material y apoyar|Completa un desafío donde cada rol aporta y ninguno queda fijo;Rotar y aprender|asumiré un rol distinto sin jerarquizarlo|Cambia entre participante, encargado de material, observador de seguridad y señal;Liderar escuchando|coordinaré una decisión breve incorporando otra voz|El líder recoge dos propuestas antes de elegir y explica el criterio;Evaluar la cooperación|describiré acciones de equipo sin etiquetar personalidades|Usa observé que… ayudó porque… y propone un ajuste para la siguiente ronda")),
"EF02 OA 11": ("Comportamientos seguros en actividad física", "Detenerse, escuchar y reconocer límites antes de usar implementos.", "calentamiento, instrucción, supervisión, implemento, límite, distancia, riesgo y señal", "Implementos revisados, conos, colchonetas, señalética y botiquín institucional disponible.", "entender seguridad como inmovilidad u obedecer una instrucción que no se comprendió", _steps("Calentar mediante juego|prepararé articulaciones y atención con movimientos progresivos|Juega espejo en intensidad creciente y explica qué prepara cada acción;Escuchar y comprobar|repetiré una instrucción con mis palabras antes de iniciar|Usa muestra-señala-haz para una estación con dos condiciones de seguridad;Implementos supervisados|transportaré, usaré y devolveré material según su función|Detecta usos riesgosos de cuerda, balón y banco en casos ficticios;Límites y distancia|mantendré posición y trayectoria para evitar choques|Ajusta separación según desplazamiento y objeto utilizado;Decidir ante un riesgo|detendré la acción, avisaré y propondré una alternativa segura|Resuelve piso mojado, material dañado o dolor inesperado sin ocultarlo ni improvisar atención")),
}


def _attitude(code: str, lesson_index: int, goal: str) -> list[dict[str, str]]:
    number = int(code.rsplit(" ", 1)[-1])
    pool = ART_ATTITUDES if code.startswith("AR") else MUSIC_ATTITUDES if code.startswith("MU") else PE_ATTITUDES
    attitude_code, text = pool[(number + lesson_index * 2) % len(pool)]
    return [{"code": attitude_code, "type": "Actitud", "application": f"Se promueve {text} mientras el estudiante trabaja «{goal}»; se observa en decisiones disciplinares y nunca como rasgo fijo de personalidad."}]


def _lesson(code: str, index: int, stage: tuple[str, str, str], profile: tuple, discipline: str) -> dict:
    title, goal, challenge = stage
    topic, _, _, materials, misconception, _ = profile
    if discipline == "art":
        opening = (f"Presenta el referente o material sin mostrar un producto modelo: {challenge} Cada estudiante registra dos detalles y una posibilidad propia.", f"Organiza una observación silenciosa del desafío «{challenge}» y luego reúne preguntas sobre forma, color, material o punto de vista.")[index % 2]
        model = f"Realiza una prueba parcial y piensa en voz alta: {challenge} Muestra cómo una decisión visual cambia el efecto y conserva visible un intento que no funcionó."
        guided = (f"En un muestrario común exploran una variable de «{title.lower()}» y comparan efectos sin elegir una solución única.", f"Trabajan por estaciones de observación, material y composición para «{title.lower()}»; cada estudiante selecciona lo que sirve a su intención.", f"En parejas describen lo que ven en una prueba de «{title.lower()}» sin corregirla; el autor decide el siguiente cambio.")[index % 3]
        evidence = f"Trabajo visual propio sobre «{title.lower()}» acompañado por una decisión de proceso y una explicación con lenguaje visual."
        support = "Ofrece materiales de fácil manipulación, formatos de distinto tamaño, demostración técnica breve y posibilidad de explicar oralmente; no entrega una plantilla para copiar."
        extension = "Cambia material, escala, encuadre o audiencia y pide conservar la intención mediante una nueva decisión visual."
        coordination = "El docente conduce creación y apreciación; educación diferencial acuerda acceso a herramientas, postura, contraste o comunicación sin ejecutar la obra ni imponer una estética."
    elif discipline == "music":
        opening = (f"Escuchan o producen una vez el caso sin nombrar la respuesta: {challenge} Cada estudiante registra un rasgo audible con gesto o símbolo.", f"Presenta dos versiones breves del desafío «{challenge}» y pide anticipar qué se mantuvo y qué cambió antes de repetirlas.")[index % 2]
        model = f"Interpreta o reproduce un ejemplo distinto y verbaliza la escucha: {challenge} Aísla pulso, timbre, altura, intensidad, duración o forma según corresponda."
        guided = (f"Por eco y turnos practican «{title.lower()}», alternando interpretar y escuchar para ajustar un rasgo audible.", f"Usan tarjetas o notación inventada para representar «{title.lower()}» y comprueban si otro grupo puede reconstruirla.", f"Comparan dos audiciones o ejecuciones de «{title.lower()}», señalan evidencia sonora y ensayan una modificación.")[index % 3]
        evidence = f"Respuesta, representación o interpretación individual de «{title.lower()}» con un rasgo musical audible o localizable y una explicación breve."
        support = "Reduce la extensión, mantiene pulso visible, ofrece eco, gesto o notación gráfica y permite rol vocal, corporal o instrumental equivalente."
        extension = "Transforma una cualidad o sección manteniendo las demás y pide anticipar y describir el efecto audible."
        coordination = "El docente conduce escucha e interpretación y protege el cuidado auditivo; educación diferencial acuerda acceso sensorial, motor o gráfico sin reemplazar la decisión musical."
    else:
        opening = (f"Demuestra el recorrido o juego a velocidad de observación: {challenge} El grupo identifica meta, espacio, señal de detención y una condición de seguridad.", f"Plantea dos soluciones motrices al desafío «{challenge}». Cada estudiante anticipa cuál le ofrece más control y elige una primera variante accesible.")[index % 2]
        model = f"Ejecuta lentamente y nombra mirada, apoyos, trayectoria, fuerza y señal de seguridad: {challenge} Contrasta control con rapidez sin presentar un cuerpo ideal."
        guided = (f"Practican «{title.lower()}» en estaciones con tiempos breves, distancia suficiente y una variante de acceso; la retroalimentación se refiere a control y seguridad.", f"En parejas alternan ejecución y observación de un criterio de «{title.lower()}», sin comparar cuerpos ni resultados entre estudiantes.", f"Resuelven el foco «{title.lower()}» mediante dos recorridos o implementos y eligen cuál permite mejor control.")[index % 3]
        evidence = f"Desempeño motriz individual en «{title.lower()}» observado con control, seguridad y una autoexplicación o elección de ajuste."
        support = "Ajusta espacio, altura, distancia, velocidad, implemento o forma de participación; conserva la habilidad y ofrece práctica adicional sin exposición pública."
        extension = "Combina otra habilidad o cambia dirección, ritmo, implemento o regla manteniendo control y seguridad."
        coordination = "El docente conduce progresión y seguridad; educación diferencial acuerda variantes de acceso y señales, y salud escolar interviene sólo según protocolos, sin diagnosticar durante la clase."
    return {
        "title": title,
        "purpose": f"Desarrollar {topic.lower()} mediante «{title.lower()}», con decisiones observables, práctica progresiva y revisión.",
        "goal": f"Hoy {goal}.",
        "opening": opening,
        "model": model,
        "guided": guided,
        "independent": f"Realiza una versión nueva de «{title.lower()}» sin copiar la demostración; elige una estrategia o decisión, aplícala y revisa el resultado con el criterio trabajado.",
        "ticket": f"{challenge} Muestra o explica la decisión que permitió cumplir el criterio principal.",
        "materials": materials,
        "support": support,
        "extension": extension,
        "evidence": evidence,
        "criteria": ["responde al foco específico de la clase", "hace visible una decisión propia de la disciplina", "revisa el resultado usando un criterio observable"],
        "next_step": "Avanza cuando decisión, desempeño y explicación coinciden; si no, cambia una condición de acceso o modela otro ejemplo antes de repetir.",
        "short_version": "Conserva observación o preparación, modelado breve, práctica guiada, desempeño individual y cierre; reduce turnos, no el criterio disciplinar.",
        "home_task": "Observa o practica una versión breve y segura con materiales disponibles, o registra una idea mediante dibujo u oralidad. No requiere compras, internet ni exposición familiar.",
        "complementary": ["Recuperación: aísla una sola variable y vuelve luego a la combinación original.", f"Análisis de error: revisa un caso ficticio que muestra esta confusión: {misconception}.", "Transferencia: cambia material, sonido, espacio o regla y explica qué debió ajustarse."],
        "difficulty_actions": [
            {"signal": "Imita el resultado sin tomar una decisión", "action": "Ofrece dos alternativas y pide elegir una según el efecto, sonido o control buscado.", "check": "Puede mostrar qué eligió y para qué."},
            {"signal": misconception.capitalize(), "action": support, "check": "Resuelve un caso nuevo sin repetir la confusión."},
            {"signal": "Se inhibe o evita participar", "action": "Reduce exposición, ofrece rol o variante equivalente y permite ensayo privado antes de compartir.", "check": "Participa en una vía accesible y produce evidencia propia."},
        ],
        "specialist_coordination": coordination,
        "transversal": _attitude(code, index, goal),
    }


def _build(code: str, table: dict, discipline: str, axis: str) -> dict | None:
    profile = table.get(code)
    if not profile:
        return None
    topic, prior, vocabulary, _, misconception, stages = profile
    slug = {"art": "artes-visuales", "music": "musica", "pe": "educacion-fisica-salud"}[discipline]
    return {
        "topic": topic,
        "pedagogical_explanation": f"{topic} se desarrolla mediante experiencias propias de la disciplina y no mediante una plantilla genérica. La secuencia parte de {prior[0].lower() + prior[1:]} y enfrenta la confusión «{misconception}».",
        "prerequisites": prior,
        "vocabulary": vocabulary,
        "official_alignment": {
            "units": [f"Eje {axis} · organización interna en {len(stages)} clases"],
            "unit_origin": "Organización interna derivada del eje y del OA; no se presenta como unidad oficial del programa de estudio.",
            "indicators": [f"{goal[0].upper() + goal[1:]}." for _, goal, _ in stages[:3]],
            "indicator_origin": "Criterios de progresión internos derivados del verbo, contenido y alcance del OA oficial",
            "source": f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/{slug}/2-basico/{code.lower().replace(' ', '-')}",
        },
        "lessons": [_lesson(code, index, stage, profile, discipline) for index, stage in enumerate(stages)],
    }


def build_sequence(code: str) -> dict | None:
    if code in AR:
        return _build(code, AR, "art", "Expresar, crear, apreciar y responder")
    if code in MU:
        return _build(code, MU, "music", "Escuchar, interpretar, crear y reflexionar")
    if code in EF:
        return _build(code, EF, "pe", "Habilidades motrices, vida activa y seguridad")
    return None


def build_transversal_integration(item: dict) -> dict:
    code = item["oa_code"]
    text = item["oa_text"].split("Unidad de Currículum", 1)[0].strip().rstrip(".")
    if "AR02" in code:
        context, decision = "una experiencia de creación o apreciación visual", "decisión visual o de proceso"
    elif "MU02" in code:
        context, decision = "una experiencia de escucha, interpretación o creación musical", "decisión musical audible"
    else:
        context, decision = "una tarea motriz segura y accesible", "decisión de movimiento, regulación o colaboración"
    lessons = []
    for phase, _ in item["phases"]:
        lessons.append({
            "title": f"{phase}: actitud en acción disciplinar",
            "purpose": f"Integrar «{text}» dentro de {context}, sin convertir la actitud en charla aislada ni calificación de personalidad.",
            "goal": f"Hoy haré visible una {decision} y explicaré cómo aportó a mi aprendizaje.",
            "opening": f"Contrasta dos respuestas a {context}: una sólo nombra la actitud y otra la muestra mediante una acción. El curso localiza la evidencia.",
            "model": f"Modela una {decision} que manifieste «{text}» y señala su efecto en el trabajo, la escucha, la seguridad o la revisión.",
            "guided": "Realizan una tarea breve en parejas o grupos, marcan una acción observable y reciben retroalimentación sobre esa acción, nunca sobre el cuerpo o la personalidad.",
            "independent": f"Cada estudiante completa una nueva versión de {context}, identifica su decisión y explica cómo la actitud influyó en ella.",
            "ticket": "Señala una evidencia propia de la actitud y completa: esta acción ayudó porque…",
            "materials": "Materiales del OA disciplinar anfitrión y una tarjeta con la actitud expresada como acción observable.",
            "support": "Ofrece dos ejemplos, una frase inicial y una vía equivalente de participación; conserva la decisión disciplinar.",
            "extension": "Transfiere la actitud a otro OA de la asignatura y compara cómo cambia su manifestación concreta.",
            "evidence": "Producción o desempeño disciplinar con una marca y explicación atribuible al estudiante.",
            "criteria": ["resuelve una tarea disciplinar pertinente", "hace visible la actitud mediante una acción", "explica su efecto sin usar etiquetas personales"],
            "next_step": "Integra nuevamente si depende del apoyo; cambia el contexto cuando la acción aparece con autonomía.",
            "short_version": "Conserva tarea, acción observable, evidencia individual y cierre; reduce repetición, no la integración.",
            "home_task": "Explica o dibuja un ejemplo seguro de la actitud dentro de una actividad artística, musical o motriz; no requiere materiales comprados.",
            "complementary": ["Clasificar evidencia y no evidencia de la actitud.", "Revisar un caso que confunde actitud con obediencia o talento.", "Transferir la acción a otro eje."],
            "difficulty_actions": [
                {"signal": "Nombra la actitud, pero no la aplica", "action": "Pide señalar una decisión concreta dentro de la tarea.", "check": "La evidencia queda localizada."},
                {"signal": "Evalúa talento, cuerpo o personalidad", "action": "Reformula la observación como acción modificable y vinculada al OA.", "check": "La retroalimentación describe qué hizo y qué puede probar."},
                {"signal": "La actitud desplaza el contenido", "action": "Recupera el criterio disciplinar y usa la actitud como medio.", "check": "El ticket demuestra contenido e integración."},
            ],
            "specialist_coordination": "El docente mantiene el OA disciplinar como foco; profesionales de apoyo acuerdan una barrera, una variante y una evidencia sin diagnosticar ni reducir la tarea.",
        })
    return {"generated_for": "2-basico", "lessons": lessons}
