"""Curated second-grade Language, Science and History sequences.

The compact profiles below are deliberately disciplinary: every lesson has a
different focus and concrete challenge, while the builders add the stable
planning contract shared by the repository.
"""
from __future__ import annotations


def _steps(value: str) -> list[tuple[str, str, str]]:
    return [tuple(part.strip() for part in row.split("|", 2)) for row in value.split(";")]


LANGUAGE_ATTITUDES = (
    ("de Actitud LE02 OAA A", "interés activo por leer y descubrir lo que ofrece un texto"),
    ("de Actitud LE02 OAA B", "disposición a compartir ideas, experiencias y opiniones"),
    ("de Actitud LE02 OAA C", "expresión creativa mediante lenguaje oral y escrito"),
    ("de Actitud LE02 OAA D", "trabajo riguroso y perseverante al revisar una producción"),
    ("de Actitud LE02 OAA E", "reflexión respetuosa sobre ideas e intereses propios"),
    ("de Actitud LE02 OAA F", "empatía con personas y personajes en su contexto"),
    ("de Actitud LE02 OAA G", "respeto por opiniones diversas y valoración del diálogo"),
)

SCIENCE_SKILLS = (
    ("de Habilidad CN02 OAH a", "formular una predicción o inferencia a partir de una observación"),
    ("de Habilidad CN02 OAH b", "explorar y clasificar materiales siguiendo una pregunta dada"),
    ("de Habilidad CN02 OAH c", "medir y registrar datos cuidadosamente"),
    ("de Habilidad CN02 OAH d", "seguir instrucciones para usar materiales con seguridad"),
    ("de Habilidad CN02 OAH e", "comparar y comunicar observaciones, mediciones y explicaciones"),
)
SCIENCE_ATTITUDES = (
    ("de Actitud CN02 OAA A", "curiosidad por los seres vivos y eventos del entorno"),
    ("de Actitud CN02 OAA B", "trabajo riguroso y perseverante"),
    ("de Actitud CN02 OAA C", "cuidado y protección del ambiente"),
    ("de Actitud CN02 OAA D", "responsabilidad y colaboración flexible"),
    ("de Actitud CN02 OAA E", "compromiso con la actividad física y el autocuidado"),
    ("de Actitud CN02 OAA F", "respeto de normas que resguardan la seguridad"),
)

HISTORY_SKILLS = (
    ("de Habilidad HI02 OAH a", "ordenar acontecimientos en una secuencia temporal"),
    ("de Habilidad HI02 OAH b", "usar vocabulario de pasado, presente y futuro"),
    ("de Habilidad HI02 OAH c", "identificar una continuidad y un cambio"),
    ("de Habilidad HI02 OAH d", "leer o comunicar información mediante plano, mapa o globo"),
    ("de Habilidad HI02 OAH e", "orientarse con posición relativa, referentes y puntos cardinales"),
    ("de Habilidad HI02 OAH f", "obtener información explícita de una fuente dada"),
    ("de Habilidad HI02 OAH g", "formular una opinión justificada"),
    ("de Habilidad HI02 OAH h", "conversar respetando turnos y otros puntos de vista"),
    ("de Habilidad HI02 OAH i", "presentar un tema con apoyo oral, visual o escrito"),
)
HISTORY_ATTITUDES = (
    ("de Actitud HI02 OAA A", "trabajo riguroso, perseverante y abierto a revisión"),
    ("de Actitud HI02 OAA B", "valoración de la dignidad de todos los trabajos"),
    ("de Actitud HI02 OAA C", "igualdad de derechos y participación de mujeres y hombres"),
    ("de Actitud HI02 OAA D", "igualdad de derechos sin discriminación"),
    ("de Actitud HI02 OAA E", "participación solidaria y responsable"),
    ("de Actitud HI02 OAA F", "pertenencia reflexiva al entorno, la comunidad y el país"),
    ("de Actitud HI02 OAA G", "actuación cotidiana conforme a virtudes ciudadanas"),
    ("de Actitud HI02 OAA H", "valoración de la democracia y el resguardo de derechos"),
    ("de Actitud HI02 OAA I", "valoración de la vida en sociedad"),
)


L = {
"LE02 OA 01": ("Lectura de palabras con combinaciones complejas", "Leer sílabas directas y reconocer sonidos frecuentes.", "hiato, diptongo, grupo consonántico, sílaba, sonido y autocorrección", "Tarjetas de palabras, tiras con oraciones y un texto breve preparado por el docente.", "adivinar por la primera sílaba y omitir letras que cambian el sonido", _steps("Vocales que viajan juntas o separadas|distinguiré al leer palabras con diptongo e hiato|Lee aire, río, cuidado y maíz, marca golpes de voz y comprueba en una oración;Grupos consonánticos sin perder sonidos|leeré palabras con bl, br, cl, cr, dr, fl, fr, gl, gr, pl, pr, tr|Contrasta plato/pato y fruta/ruta dentro de avisos breves;Ce-ci y que-qui|usaré la combinación escrita que corresponde al sonido|Completa y lee una nota sobre Cecilia y Quique: cocina, queso, quince;Ge-gi, gue-gui|distinguiré cuándo la u permite conservar el sonido de g|Lee gigante, guitarra, guerra y guiso, explica por qué cambia la escritura;Güe-güi y lectura en contexto|leeré la diéresis y autocorregiré sin perder el sentido|Resuelve un párrafo sobre un pingüino bilingüe y justifica dos autocorrecciones")),
"LE02 OA 02": ("Fluidez al leer en voz alta con sentido", "Leer oraciones breves siguiendo de izquierda a derecha.", "precisión, frase, punto seguido, punto aparte, ritmo y autocorrección", "Texto breve ampliado, copias individuales, lápiz y pauta de escucha.", "confundir fluidez con velocidad y continuar aunque una palabra cambie el sentido", _steps("Precisión antes que rapidez|leeré una frase completa pronunciando cada palabra|Compara una lectura precisa de El tren cruza el puente con otra que omite cruza;Frases que caben en una respiración|agruparé palabras que expresan una idea|Marca unidades de sentido en La gata pequeña / duerme junto al fuego;El punto pide una pausa|respetaré punto seguido y punto aparte|Ensaya un texto de dos párrafos y diferencia la pausa que continúa de la que cambia de idea;Autocorregir y continuar|volveré a una palabra cuando el sentido se rompa|Modela una equivocación en camino/camión, corrígela y retoma la frase completa;Lectura para una audiencia|leeré un texto breve de manera comprensible para otra persona|Prepara y lee un aviso escolar, el oyente reconstruye dos datos para comprobar claridad")),
"LE02 OA 03": ("Estrategias para comprender mientras se lee", "Recordar información explícita de relatos breves.", "conexión, visualización, pregunta, pista, comprensión y verificación", "Relato breve, texto informativo, notas adhesivas o tiras de papel y lápices.", "contar una experiencia propia sin volver al texto o formular preguntas que el texto ya respondió", _steps("Lo que ya sé ayuda a entrar|conectaré una idea del texto con un conocimiento útil|Antes de leer sobre picaflores, activa lo que sabes y luego tacha conexiones que no ayudan;Construir una película mental|visualizaré detalles que el texto sí entrega|Dibuja la escena de una plaza después de una descripción y etiqueta tres pistas textuales;Preguntas durante la lectura|formularé preguntas que orienten mi comprensión|Detén un relato antes del conflicto y separa preguntas respondibles de preguntas para seguir leyendo;Elegir la estrategia adecuada|decidiré si necesito conectar, visualizar o preguntar|Lee tres fragmentos y justifica qué estrategia aclara cada uno;Explicar cómo comprendí|mostraré una respuesta y la estrategia que me permitió construirla|Responde una pregunta inferencial sobre un relato nuevo y señala las pistas y la estrategia")),
"LE02 OA 04": ("Exploración de un repertorio literario diverso", "Escuchar y comentar cuentos y poemas adecuados a la edad.", "cuento, poema, fábula, leyenda, narrador, imaginación y preferencia", "Selección legal de textos del aula o biblioteca, fichas de recomendación y cuaderno lector.", "elegir sólo por la portada o llamar cuento a cualquier texto literario", _steps("Reconocer familias de textos|distinguiré cuento, poema, fábula y leyenda por sus rasgos|Compara comienzos de cuatro textos y encuentra una pista de género en cada uno;Entrar a un cuento|seguiré personajes, deseo y dificultad en un cuento|Lee un cuento de autor y registra qué quiere el personaje y qué se lo impide;Escuchar la música de un poema|notaré imágenes, repeticiones y sonidos en un poema|Lee dos veces un poema breve y marca un verso que hace imaginar o escuchar algo;Una fábula y una leyenda|compararé lo que explica o enseña cada tradición|Contrasta una fábula animal con una leyenda local sin reducirlas a una moraleja;Recomendar con razones|elegiré un texto para una persona y justificaré mi elección|Escribe o graba una recomendación que mencione género, un rasgo y el posible lector")),
"LE02 OA 05": ("Comprensión profunda de narraciones", "Reconocer personajes y acciones principales en relatos breves.", "secuencia, información explícita, inferencia, personaje, ambiente, sentimiento y opinión", "Narración breve legal, tarjetas de escenas, organizador y materiales de dibujo.", "inventar información sin pista textual o confundir rasgo físico con sentimiento", _steps("Lo que dice y lo que sugiere|distinguiré información explícita de una inferencia|En Ana escondió el paraguas mojado, separa lo dicho de lo que puede inferirse con cautela;Acciones en orden|reconstruiré inicio, problema, acciones y desenlace|Ordena escenas mezcladas y enlázalas con primero, luego, porque y finalmente;Conocer a un personaje|describiré rasgos físicos y sentimientos con pistas|Contrasta cómo se ve un personaje con lo que siente a partir de acciones y palabras;El ambiente sostiene la historia|recrearé el lugar usando detalles del texto|Construye un plano o dibujo del ambiente y etiqueta cada elemento con su pista;Texto y experiencia en diálogo|conectaré una situación del relato con una experiencia sin reemplazarlo|Escribe una semejanza y una diferencia entre el problema del personaje y una situación conocida;Opinar con fundamento|formularé una opinión sobre una decisión del personaje|Elige si una acción fue acertada y sostén la opinión con un hecho del relato")),
"LE02 OA 06": ("Encuentro habitual con poemas", "Escuchar poemas, rimas y juegos de tradición oral.", "verso, estrofa, ritmo, repetición, imagen poética y tradición oral", "Poemas autorizados o de dominio público, tarjetas de versos y cuaderno de poemas.", "buscar sólo rima y dejar de atender a las imágenes o emociones del poema", _steps("Un poema se mira y se escucha|reconoceré versos, estrofas y repeticiones|Explora la forma gráfica y sonora de un poema breve sin convertirlo en lista de definiciones;Imágenes hechas de palabras|visualizaré una imagen sugerida por un verso|Dibuja dos interpretaciones posibles de una comparación y vuelve a las palabras;Ritmo sin carrera|leeré siguiendo repeticiones y pausas|Ensaya un poema coral cuidando entradas, silencios y volumen;Poemas de autor y tradición oral|compararé dos poemas por voz, tema y forma|Contrasta una ronda tradicional con un poema de autor sin declarar uno superior;Bitácora de disfrute|registraré qué poema quiero releer y por qué|Elige un poema, copia sólo un verso breve permitido y explica qué efecto produjo")),
"LE02 OA 07": ("Comprensión de textos no literarios", "Distinguir textos que informan, indican o comunican algo.", "propósito, destinatario, información explícita, inferencia, ilustración, símbolo y opinión", "Carta, nota, instrucciones y artículo breve creados para la clase; símbolos impresos.", "leer todos los formatos igual o tratar la ilustración como adorno", _steps("¿Para qué fue escrito?|identificaré el propósito de carta, nota, instrucción y artículo|Clasifica cuatro textos por lo que permiten hacer y señala una evidencia de formato;Datos que están y datos que infiero|extraeré información explícita e implícita|Lee una nota de reunión y deduce qué debe llevar una familia usando dos pistas;Imágenes que agregan información|integraré palabras, ilustraciones y símbolos|Interpreta una instrucción con flechas y pictogramas y detecta qué se pierde sin ellos;Seguir instrucciones y comprobar|ejecutaré una secuencia sin alterar su orden|Arma una figura de papel con instrucciones creadas por el docente y marca el paso ambiguo;Leer un artículo para aprender|organizaré información de un artículo breve|Completa tema, tres datos y una pregunta pendiente tras leer sobre un animal chileno;Opinar desde el texto|daré una opinión sobre un aspecto y la apoyaré con información|Responde si el aviso cumple su propósito y cita un elemento que ayuda o estorba")),
"LE02 OA 08": ("Construcción de una vida lectora", "Elegir entre algunos textos y sostener momentos breves de lectura.", "elección, hábito, propósito, exploración, abandono justificado y recomendación", "Biblioteca de aula, registro lector simple y variedad de formatos accesibles.", "medir gusto lector por cantidad o exigir terminar un libro que no resulta accesible", _steps("Explorar antes de elegir|usaré portada, índice y primeras páginas para elegir|Explora tres libros durante dos minutos y registra qué señal orientó tu elección;Preparar un tiempo de lectura|organizaré lugar, texto y propósito para leer|Ensaya una rutina breve que reduzca interrupciones sin convertirla en premio o castigo;Registrar sin competir|anotaré una huella personal de mi lectura|Dibuja una escena, pregunta o palabra que quieras conservar sin resumir todo;Cambiar o persistir con razones|decidiré si continúo, releo o cambio de texto|Examina un caso donde el texto es demasiado difícil y distingue reto de barrera;Compartir un hallazgo|recomendaré una lectura desde mi experiencia|Realiza una conversación de un minuto que no revele el final y dé una razón concreta")),
"LE02 OA 09": ("Uso autónomo y cuidadoso de la biblioteca", "Reconocer cómo se organizan y cuidan libros de uso común.", "biblioteca, catálogo, sección, autor, título, préstamo y cuidado común", "Biblioteca escolar o de aula, libros, señalética y fichas de búsqueda.", "buscar sólo por color o considerar el cuidado como obediencia sin relación con otros lectores", _steps("Leer la biblioteca como un mapa|ubicaré secciones y señales para orientar una búsqueda|Recorre o simula la biblioteca y dibuja una ruta desde la entrada a dos secciones;Buscar con una pista|encontraré un libro usando título, autor o tema|Resuelve búsquedas con fichas incompletas y decide qué dato sirve en cada caso;Elegir y registrar|seleccionaré un libro pertinente y completaré su préstamo|Compara dos opciones para un propósito y registra los datos que permiten devolverlas;Cuidar para compartir|aplicaré acciones de cuidado y explicaré a quién benefician|Analiza libros con daños ficticios, propone prevención y practica una devolución ordenada")),
"LE02 OA 10": ("Búsqueda de información en una fuente dada", "Localizar títulos, imágenes y datos en textos informativos breves.", "pregunta de investigación, fuente, palabra clave, dato, sección y registro", "Fuente previamente seleccionada y segura, organizador de búsqueda y lápices.", "copiar todo el texto o responder con conocimientos previos sin consultar la fuente", _steps("Una pregunta que se puede investigar|transformaré un tema amplio en una pregunta acotada|Convierte animales en ¿cómo se protege el huemul del frío? y verifica que la fuente pueda responder;Recorrer una fuente|usaré título, subtítulos e imágenes para ubicar una sección|Modela un barrido de página sin leer linealmente todo el capítulo;Registrar datos pertinentes|anotaré información que responde a la pregunta|Separa tres datos útiles de dos curiosos pero irrelevantes y registra con palabras propias;Comunicar y mostrar la fuente|responderé la pregunta indicando de dónde obtuve la información|Elabora una ficha con respuesta breve, dibujo explicativo y título de la fuente")),
"LE02 OA 11": ("Curiosidad y estrategias para descubrir palabras", "Reconocer cuándo una palabra impide o enriquece la comprensión.", "palabra desconocida, contexto, familia de palabras, diccionario, significado y comprobación", "Textos breves, tarjetas, diccionario infantil disponible y mural de palabras.", "saltar toda palabra desconocida o aceptar el primer significado del diccionario", _steps("Detectar una palabra que importa|marcaré palabras desconocidas que afectan mi comprensión|Lee un párrafo y justifica cuál palabra conviene investigar primero;Pistas alrededor de la palabra|propondré un significado usando el contexto|Infiere frondoso en un texto que menciona muchas ramas y sombra;Familias y partes de palabras|usaré semejanzas con palabras conocidas|Relaciona mar, marino y submarino, explica qué ayuda y qué no basta;Comprobar y volver al texto|consultaré una fuente y elegiré el significado pertinente|Busca banco en un diccionario infantil y decide qué acepción sirve en dos oraciones")),
"LE02 OA 12": ("Escritura frecuente para crear y expresar", "Escribir oraciones sobre experiencias e ideas propias.", "propósito, destinatario, voz, detalle, poema, diario, carta y recado", "Cuaderno, papeles de formatos diversos, imágenes inspiradoras y buzón de aula.", "copiar un modelo cambiando pocas palabras o creer que creatividad impide revisar", _steps("Un recado que sí llega|escribiré un mensaje breve con destinatario y dato necesario|Redacta un recado para devolver un libro indicando qué, cuándo y para quién;Una entrada de diario|narraré un momento desde mi propia voz|Escribe sobre un hallazgo pequeño incluyendo cuándo ocurrió y cómo te hizo sentir;Carta con propósito|escribiré a alguien para contar, pedir o agradecer|Elige destinatario y propósito, revisa si saludo, cuerpo y despedida ayudan;Poema de observación|crearé imágenes con palabras a partir de algo cotidiano|Observa una hoja o piedra y compone versos sin exigir rima;Carpeta de autor|seleccionaré y mejoraré un texto para compartir|Elige una producción, explica por qué la conservas y realiza una mejora que cuide tu voz")),
"LE02 OA 13": ("Narraciones con inicio, desarrollo y desenlace", "Relatar oralmente una experiencia en orden comprensible.", "personaje, situación inicial, problema, acción, consecuencia y desenlace", "Secuencias de imágenes, tarjetas narrativas, organizador de tres momentos y lápices.", "enumerar hechos sin relación causal o resolver el problema de forma repentina", _steps("Un personaje quiere algo|crearé un inicio que presente personaje y situación|Inicia un cuento sobre una niña que quiere recuperar una semilla llevada por el viento;El problema pone la historia en marcha|plantearé una dificultad relacionada con el inicio|Compara un problema conectado con otro que pertenece a otra historia;Acciones y consecuencias|desarrollaré dos acciones donde una cambie la siguiente|Usa porque, pero y entonces para evitar una lista de sucesos;Un desenlace preparado|cerraré el conflicto sin agregar un problema nuevo|Propón dos desenlaces y elige el que responde a las acciones anteriores;Revisar la historia completa|comprobaré coherencia entre inicio, desarrollo y final|Intercambia el texto, reconstruye la secuencia del compañero y ajusta el punto confuso")),
"LE02 OA 14": ("Artículos informativos para enseñar a otros", "Comunicar por escrito datos verdaderos sobre un tema conocido.", "tema, subtema, dato, título, oración temática, fuente e ilustración", "Fuente breve dada, organizador, hojas y recursos para una ilustración rotulada.", "mezclar opinión con dato sin distinguirlos o copiar frases completas de la fuente", _steps("Tema y pregunta del lector|definiré qué enseñará mi artículo|Acota el tema agua a cómo llega agua potable a la escuela;Datos en grupos|agruparé información relacionada en subtemas|Clasifica tarjetas sobre hábitat, alimentación y aspecto de un animal;Un párrafo que informa|escribiré oraciones conectadas sobre un subtema|Modela una oración temática y dos datos sin repetir la misma idea;Título e imagen que aportan|agregaré apoyos que ayuden a comprender|Compara títulos vagos y precisos, crea una ilustración con rótulo informativo;Publicar después de comprobar|revisaré claridad y exactitud para una audiencia|Entrega el artículo a un lector que marca qué aprendió y qué pregunta conserva")),
"LE02 OA 15": ("Letra clara y separación entre palabras", "Escribir palabras y oraciones legibles con apoyo de pauta.", "legibilidad, tamaño, dirección, espacio, palabra, oración y lector", "Pauta amplia o cuaderno disponible, lápices y tiras de oraciones.", "copiar muchas veces sin identificar qué dificulta la lectura o valorar estética sobre legibilidad", _steps("Escribir para que otro lea|identificaré qué hace legible una oración|Compara dos mensajes ficticios y señala letras o espacios que cambian el sentido;Espacios que separan ideas|dejaré un espacio reconocible entre palabras|Reconstruye lacasatieneunpatio y decide dónde termina cada palabra;Tamaño y apoyo en la línea|mantendré letras reconocibles y orientadas|Practica sólo las uniones que un lector no pudo distinguir en una frase propia;Ritmo de copia con sentido|copiaré una oración por unidades breves sin perder palabras|Lee, tapa, escribe y comprueba una frase, evitando copiar letra por letra;Una versión legible|reescribiré un mensaje a partir de una necesidad real de lectura|Produce una invitación breve y comprueba con un compañero que todos los datos se leen")),
"LE02 OA 16": ("Planificación de la escritura a partir de ideas", "Conversar y dibujar antes de escribir un texto.", "propósito, audiencia, idea, selección, imagen, conversación y organizador", "Imágenes sugerentes, organizadores flexibles, notas adhesivas y lápices.", "anotar todas las ideas sin seleccionar o confundir planificar con escribir el texto final", _steps("Mirar más de una vez|generaré ideas observando detalles de una imagen|Observa una plaza bajo la lluvia y registra personas, acciones, sonidos y una pregunta;Conversar para ampliar|recogeré una idea nueva sin perder mi propósito|En parejas, uno pregunta y el autor decide qué sugerencia le sirve;Elegir y ordenar|seleccionaré ideas para inicio, desarrollo y cierre|Mueve notas antes de escribir y elimina una idea atractiva que desvía el texto;Un plan listo para usar|comprobaré que mi plan responde a propósito y audiencia|Explica el plan oralmente, el oyente identifica qué texto recibirá y para qué")),
"LE02 OA 17": ("Proceso de escritura, revisión y edición", "Escribir un borrador breve con comienzo y cierre reconocibles.", "borrador, propósito, oración, mayúscula, punto, vocabulario, concordancia y edición", "Texto propio en proceso, lápices de dos colores y pauta breve de revisión.", "corregir sólo presentación o reemplazar la voz del autor por la del adulto", _steps("Escribir el primer borrador|convertiré mi plan en oraciones completas|Redacta sin detenerte en cada error y deja marcas donde falta una palabra;Releer como autor|comprobaré si el texto transmite la idea que quería|Subraya la oración más clara y encierra el lugar donde un lector podría perderse;Oraciones con límites claros|usaré mayúscula inicial y punto final para organizar ideas|Separa un párrafo continuo y explica por qué cada punto cierra una idea;Palabras más precisas|reemplazaré repeticiones por vocabulario pertinente|Mejora El perro era lindo sin acumular adjetivos ni cambiar el hecho;Sugerir sin apropiarse|usaré una sugerencia de un par y decidiré otra|Aplica el protocolo entiendo, pregunto, sugiero, el autor conserva la decisión final;Editar para publicar|corregiré concordancia, ortografía trabajada y presentación|Prepara una versión final y señala tres cambios que mejoraron la comprensión")),
"LE02 OA 18": ("Vocabulario nuevo en la escritura", "Recordar y explicar palabras encontradas en textos compartidos.", "significado, contexto, matiz, vocabulario activo, pertinencia y revisión", "Banco de palabras del curso, textos leídos y borradores propios.", "insertar una palabra porque suena difícil aunque no encaje en la oración", _steps("Recuperar una palabra en contexto|explicaré una palabra nueva con el sentido del texto original|Vuelve a cauteloso en un relato y reconstruye qué acciones mostraban su significado;Elegir por precisión|seleccionaré una palabra que diga exactamente lo que necesito|Compara caminó, avanzó y se arrastró para una escena de cansancio;Probar la palabra en otra oración|usaré vocabulario nuevo sin copiar el ejemplo|Escribe una oración nueva con refugio y verifica que conserve el sentido;Integrar al borrador|mejoraré un texto con una palabra pertinente|Sustituye una expresión vaga y lee ambas versiones a un compañero;Explicar la decisión|justificaré qué aporta la palabra elegida|Muestra el antes y después de una oración y explica el matiz añadido")),
"LE02 OA 19": ("Artículos, sustantivos y adjetivos al servicio del sentido", "Reconocer nombres de personas, animales, lugares y cosas.", "artículo, sustantivo, adjetivo, grupo nominal, precisión y reemplazo", "Tarjetas de palabras, textos breves y objetos o imágenes para describir.", "memorizar etiquetas sin observar cómo cambia la información de una frase", _steps("Nombrar en una oración|identificaré sustantivos por la función que cumplen|En La niña guarda semillas, cambia niña y semillas y observa qué información se reemplaza;Artículos que acompañan|probaré artículos y notaré cambios de género y número|Contrasta el puente, los puentes y una puente, decide qué combinaciones usa el texto;Adjetivos que precisan|agregaré una característica relevante, no una lista decorativa|Distingue taza roja de taza grande cuando hay que elegir una entre varias;Combinar y reemplazar|transformaré grupos de palabras conservando concordancia|Cambia la bicicleta antigua por las bicicletas nuevas y explica todos los ajustes;Escribir para un lector|usaré estas palabras para volver inequívoca una descripción|Redacta una pista que permita identificar una imagen entre cuatro semejantes")),
"LE02 OA 20": ("Concordancia de género y número", "Distinguir una y varias entidades en frases sencillas.", "género, número, singular, plural, concordancia y terminación", "Tarjetas de grupos nominales, imágenes y tiras para editar.", "cambiar sólo el sustantivo y dejar artículo o adjetivo sin concordar", _steps("Singular y plural cuentan|identificaré si una expresión nombra uno o varios|Empareja una flor amarilla con unas flores amarillas y marca las palabras que cambian;Palabras que concuerdan|ajustaré artículo, sustantivo y adjetivo como un conjunto|Transforma el gato negro en las gatas negras explicando cada cambio;Género sin estereotipos|reconoceré formas gramaticales sin asociarlas a capacidades|Revisa pares como el deportista/la deportista y evita inferir roles por género;Editar concordancia|corregiré discordancias que dificultan la lectura|Repara Los casa pequeñas tiene patio y justifica cada modificación")),
"LE02 OA 21": ("Ortografía y puntuación para facilitar la comprensión", "Usar mayúscula inicial y punto final en oraciones breves.", "ce-ci, que-qui, ge-gi, gue-gui, güe-güi, r-rr-nr, mayúscula, punto e interrogación", "Tarjetas, oraciones con errores ficticios, diccionario de aula y texto propio.", "corregir por memoria visual sin leer el contexto o agregar signos sólo al final", _steps("Familias ce-ci y que-qui|elegiré la combinación que conserva el sonido|Completa un aviso con Cecilia, cocina, quince y queso y léelo para comprobar;Ge-gi, gue-gui y güe-güi|usaré u o diéresis cuando el sonido lo requiere|Clasifica palabras de una noticia sobre un pingüino y una guitarra;R fuerte en distintas posiciones|distinguiré r, rr y nr al escribir palabras conocidas|Contrasta caro/carro, alrededor y enredo dentro de oraciones con sentido;Mayúsculas que orientan|usaré mayúscula al iniciar y en nombres propios|Edita una postal a Valdivia donde nombres comunes y propios están mezclados;Puntos para separar ideas|cerraré cada oración sin fragmentar una misma idea|Puntúa un párrafo breve y lee las pausas para comprobar;Preguntar y exclamar con dos signos|encerraré preguntas y exclamaciones completas|Convierte afirmaciones de un diálogo en preguntas y exclamaciones que cambian la entonación")),
"LE02 OA 22": ("Escucha y disfrute de obras literarias completas", "Escuchar relatos leídos por un adulto y responder sobre ellos.", "escucha, anticipación, episodio, personaje, imagen, interpretación y disfrute", "Obra completa con permiso de uso, espacio de escucha y materiales de respuesta opcional.", "interrumpir la obra para evaluar cada detalle o confundir escuchar con permanecer inmóvil", _steps("Prepararse para escuchar|anticiparé sin exigir que la historia confirme mi idea|Observa título e ilustración, registra una posibilidad y déjala abierta;Seguir el hilo|recordaré personajes y cambios importantes mientras escucho|Usa tres símbolos personales para marcar sorpresa, duda y conexión sin copiar;Imaginar con la voz de otro|representaré una escena a partir de palabras escuchadas|Dibuja o modela el ambiente antes de ver ilustraciones y etiqueta una pista;Conversar después de la obra|compartiré una interpretación y escucharé otra|Compara dos explicaciones de una decisión del personaje;Volver a un pasaje|elegiré un fragmento para releer y explicaré su efecto|Solicita una relectura breve y señala qué comprendiste o disfrutaste de otro modo")),
"LE02 OA 23": ("Comprensión activa de textos orales", "Escuchar instrucciones y relatos breves sin perder el propósito.", "propósito, información explícita, inferencia, conexión, pregunta, aclaración y opinión", "Audios o lectura docente, objetos para seguir instrucciones y organizador de escucha.", "responder desde la experiencia sin atender lo escuchado o esperar al final para aclarar una instrucción", _steps("Escuchar con un propósito|identificaré para qué habla una persona|Contrasta una explicación, una instrucción y una anécdota sobre el mismo tema;Conectar sin desviarse|relacionaré lo escuchado con una experiencia que ayude a comprender|Escucha sobre una feria y aporta una conexión que aclare un dato, no una historia paralela;Preguntar para aclarar|formularé una pregunta sobre información faltante o confusa|Después de una instrucción incompleta, distingue pregunta útil de pregunta ya respondida;Información dicha e inferida|responderé usando palabras escuchadas y pistas|Deduce por qué se suspendió un paseo a partir de un anuncio meteorológico;Seguir instrucciones|ejecutaré una secuencia oral y pediré repetición cuando sea necesario|Construye una figura con cuatro pasos escuchados y marca dónde solicitaste aclaración;Opinar sobre lo escuchado|formularé una opinión apoyada en un dato oral|Escucha dos propuestas para el recreo y elige una citando una razón entregada")),
"LE02 OA 24": ("Experiencia y lenguaje del teatro infantil", "Reconocer personajes, acciones y espacios en representaciones.", "obra, escenario, personaje, diálogo, gesto, voz, público y escena", "Representación presencial o grabada autorizada, entradas simbólicas y bitácora visual.", "reducir la experiencia a resumir el argumento o evaluar sólo vestuario y escenografía", _steps("Antes de la función|formularé expectativas y acuerdos de público respetuoso|Distingue acuerdos que cuidan la experiencia de reglas que exigen inmovilidad absoluta;Mirar cómo se cuenta|observaré cómo voz, gesto y espacio construyen una escena|Durante una escena, registra un cambio de voz o posición que alteró el sentido;Reconstruir una escena|ordenaré acciones y explicaré el conflicto observado|Usa tres cuadros para mostrar qué cambió desde el inicio al final;Explorar expresivamente|probaré otra manera de representar una acción|Representa la misma frase con dos intenciones y compara el efecto;Conversar como público|opinaré sobre una decisión escénica con evidencia|Explica cómo un gesto, sonido u objeto ayudó —o no— a comprender")),
"LE02 OA 25": ("Conversaciones que construyen ideas", "Respetar turnos y responder de manera relacionada.", "tema, turno, foco, opinión, pregunta, aclaración, empatía y desacuerdo", "Texto o tema común, objeto de turno opcional y pauta visual de conversación.", "esperar turno sólo para repetir la propia idea o tratar desacuerdo como falta de respeto", _steps("Entrar en el mismo tema|aportaré una idea relacionada con lo que se conversa|Distingue aportes conectados de cambios abruptos en una charla sobre un cuento;Expresar y explicar una opinión|diré qué pienso y agregaré una razón|Practica Estoy de acuerdo porque… y No coincido porque… sin evaluar a la persona;Preguntar para comprender|formularé preguntas que aclaren una idea ajena|Transforma ¿por qué? en preguntas precisas sobre una decisión del personaje;Escuchar de forma visible|retomaré una idea de otra persona antes de responder|Usa Si te entendí… y permite que el compañero confirme o corrija;Empatía sin suponer|reconoceré una emoción o perspectiva preguntando con cuidado|Analiza un caso ficticio y evita decir yo sé exactamente cómo te sientes;Sostener una conversación|participaré en un diálogo breve con foco, turnos y cierre|Realiza un círculo de cuatro personas, cada aporte debe conectar con uno anterior")),
"LE02 OA 26": ("Convenciones sociales para interactuar con respeto", "Saludar, presentarse y pedir algo en situaciones conocidas.", "saludo, presentación, petición, permiso, agradecimiento, disculpa, tono y contexto", "Tarjetas de situaciones ficticias y apoyos de frases flexibles.", "repetir fórmulas de cortesía sin atender al tono, la situación o la respuesta del otro", _steps("Presentarse y presentar|daré información pertinente al iniciar un encuentro|Simula recibir a una estudiante nueva sin exigir información privada;Pedir y preguntar|formularé una petición clara y respetuosa|Compara pásame eso con ¿me prestas el lápiz azul, por favor?;Agradecer y responder|cerraré un intercambio reconociendo la ayuda|Practica varias respuestas posibles sin imponer una única fórmula;Disculparse y reparar|reconoceré una acción y propondré cómo repararla|Distingue perdón automático de una disculpa que nombra el daño ficticio;Elegir según contexto|adaptaré palabras y tono a una situación|Representa cómo pedir información a un compañero, a secretaría y a un grupo")),
"LE02 OA 27": ("Exposición oral coherente y articulada", "Contar un hecho breve en orden y con volumen audible.", "tema, apertura, secuencia, detalle, vocabulario, volumen, pronunciación y postura", "Tarjetas de apoyo visual, objetos o imágenes y pauta de ensayo.", "memorizar palabra por palabra o compensar falta de organización hablando más fuerte", _steps("Elegir y acotar el tema|definiré de qué hablaré y qué dejaré fuera|Convierte animales en cómo cuida su nido el chincol;Ordenar la información|prepararé apertura, dos ideas y cierre|Usa tres tarjetas que permitan hablar sin leer un párrafo;Describir para hacer visible|incorporaré una frase descriptiva pertinente|Compara tiene plumas con tiene plumas grises y una mancha rojiza;Ensayar voz y cuerpo|ajustaré volumen, pronunciación y postura para una audiencia|Ensaya a dos distancias y pide al oyente repetir la idea central;Presentar y responder|expondré con apoyo y contestaré una pregunta|Realiza una presentación de un minuto, el público registra una idea aprendida")),
"LE02 OA 28": ("Vocabulario nuevo en intervenciones orales", "Usar palabras aprendidas al conversar sobre un texto.", "significado, contexto, precisión, reformulación, vocabulario activo y escucha", "Banco visible de palabras, textos escuchados y tarjetas de conversación.", "insertar palabras nuevas de manera forzada o corregir al hablante interrumpiendo su idea", _steps("Recordar desde el texto|explicaré una palabra nueva mediante la situación donde apareció|Recupera refugio a partir de un relato de animales y formula una explicación cotidiana;Ensayar oralmente|probaré la palabra en una frase propia y aceptaré reformulación|En parejas, usa frágil y permite que el oyente pregunte qué quieres decir;Elegir la palabra precisa|compararé palabras cercanas antes de hablar|Decide entre mirar, observar y vigilar en tres situaciones;Integrar en una conversación|usaré vocabulario nuevo para aportar al tema|Conversa sobre un texto usando una palabra del banco sólo si mejora la idea;Evaluar el efecto|explicaré qué volvió más clara una intervención|Compara dos grabaciones o reconstrucciones y señala el aporte de la palabra")),
"LE02 OA 29": ("Juego de roles para ampliar lenguaje y colaboración", "Representar personajes en situaciones ficticias y seguras.", "rol, personaje, situación, diálogo, acuerdo, improvisación y equipo", "Tarjetas de roles no estereotipados, objetos neutros y espacio delimitado.", "caricaturizar identidades o concentrar todas las decisiones en quien habla más", _steps("Construir un rol|definiré qué sabe, quiere y puede hacer mi personaje|Crea a quien atiende una veterinaria y a quien trae un ave encontrada, sin imitar identidades reales;Dialogar desde una situación|responderé a lo que otro personaje dice|Improvisa una consulta donde cada turno debe cambiar o aclarar algo;Cambiar de rol|probaré otra perspectiva sin convertirla en burla|Intercambia funciones y registra qué información nueva necesitaste;Crear en equipo|acordaremos inicio, dificultad y cierre de una escena|Presenta una escena breve donde todos los roles aportan a resolver el problema")),
"LE02 OA 30": ("Recitación expresiva y confiada", "Repetir y disfrutar rimas, canciones, trabalenguas y adivinanzas.", "entonación, ritmo, articulación, volumen, pausa, expresión y audiencia", "Selección breve autorizada o tradicional, tarjetas y espacio de ensayo.", "medir confianza por ausencia de errores o exigir exposición individual sin alternativa", _steps("Escuchar el ritmo|identificaré repeticiones, pausas y sonidos antes de memorizar|Marca palmas suaves en una rima y descubre dónde el ritmo pide pausa;Articular sin correr|pronunciaré con claridad un trabalenguas a velocidad controlada|Divide Tres tristes tigres en grupos y aumenta el ritmo sólo si conserva sonidos;Entonar para comunicar|cambiaré voz y gesto según el sentido|Recita una adivinanza probando dos entonaciones y compara qué pista destaca;Recitar para una audiencia|presentaré solo, en pareja o en coro y evaluaré claridad|Elige una vía de participación, ensaya y recoge del público qué palabras se comprendieron")),
}


S = {
"CN02 OA 01": ("Clasificación de animales vertebrados", "Reconocer animales y algunas partes visibles de su cuerpo.", "vertebrado, mamífero, ave, reptil, anfibio, pez, cubierta corporal y respiración", "Imágenes verificadas de animales, tarjetas de rasgos y organizadores de clasificación.", "clasificar por hábitat o tamaño usando un solo rasgo superficial", _steps("La columna como criterio|reconoceré qué significa vertebrado usando modelos e imágenes|Compara un esqueleto de pez, ave y perro y localiza la estructura común;Mamíferos y aves|distinguiré mamíferos y aves con más de una característica|Clasifica murciélago, pingüino y delfín evitando decidir por vuelo o ambiente;Reptiles, anfibios y peces|compararé cubierta corporal y respiración|Examina lagartija, rana y pez en una tabla de rasgos;Una clave de clasificación|clasificaré un animal nuevo y justificaré cada decisión|Construye una clave simple y úsala con cinco animales chilenos")),
"CN02 OA 02": ("Animales sin columna vertebral y comparación", "Observar animales pequeños sin dañarlos y describir rasgos visibles.", "invertebrado, insecto, arácnido, crustáceo, segmento, patas, antena y exoesqueleto", "Imágenes ampliadas, lupas opcionales y modelos; no se requiere capturar animales.", "llamar insecto a todo animal pequeño o suponer que no tener columna significa no tener sostén", _steps("Buscar evidencia de ausencia|compararé modelos con y sin columna vertebral|Contrasta un caracol con un pez y registra qué estructura se observa o no;Insectos|identificaré cabeza, tórax, abdomen y seis patas|Clasifica hormiga, araña y ciempiés contando estructuras, no por semejanza general;Arácnidos y crustáceos|compararé número de patas, antenas y cubierta|Examina araña y jaiba mediante imágenes ampliadas;Vertebrados e invertebrados|construiré una comparación usando criterios comunes|Completa una matriz de sostén, cubierta, patas y respiración y clasifica un caso nuevo")),
"CN02 OA 03": ("Ciclos de vida de animales", "Reconocer que los animales nacen, crecen y cambian.", "ciclo de vida, etapa, nacimiento, crecimiento, reproducción, metamorfosis y hábitat", "Tarjetas de ciclos verificadas de mamífero, ave, insecto y anfibio.", "ordenar por tamaño de la imagen o creer que todos los animales cambian del mismo modo", _steps("Etapas que vuelven a comenzar|ordenaré un ciclo y explicaré por qué no es una fila cerrada|Ordena nacimiento, crecimiento y adulto en un perro y conecta al nuevo nacimiento;Ave y mamífero|compararé dos ciclos con crías de aspecto semejante al adulto|Contrasta gallina y gato sin confundir huevo con una etapa universal;Metamorfosis|describiré cambios de rana y mariposa sin saltar etapas|Ordena huevo, larva/oruga, pupa o renacuajo y adulto según cada caso;Ciclo y hábitat|relacionaré una etapa con el ambiente que necesita|Explica por qué renacuajo y rana adulta usan el agua de manera distinta")),
"CN02 OA 04": ("Hábitats y necesidades de los animales", "Reconocer que los animales encuentran alimento, agua y refugio en su ambiente.", "hábitat, luminosidad, humedad, temperatura, refugio, supervivencia y evidencia", "Fotografías de hábitats, termómetro opcional y tarjetas de condiciones.", "emparejar animal y paisaje sólo por color o afirmar que un hábitat es una casa construida", _steps("Un hábitat ofrece condiciones|identificaré recursos y condiciones en un ambiente|Examina una poza y un matorral: registra agua, refugio, luz y temperatura aproximada;Luz y humedad|compararé microambientes cercanos sin capturar seres vivos|Observa bajo una piedra sin mover organismos y un sector soleado;Temperatura y supervivencia|explicaré cómo una condición limita o favorece a un animal|Compara una lagartija al sol y una lombriz en suelo húmedo sin atribuir intención humana;Elegir con evidencia|justificaré qué hábitat satisface necesidades de un animal|Decide entre tres ambientes para una rana chilena citando dos condiciones")),
"CN02 OA 05": ("Animales nativos amenazados y protección", "Distinguir animales nativos de mascotas y especies de otros lugares.", "nativo, endémico, peligro de extinción, amenaza, hábitat, protección y acción", "Fichas verificadas de fauna chilena y mapas simples; evita imágenes sensacionalistas.", "culpar a una persona aislada o proponer tener animales silvestres como mascotas", _steps("Nativo no significa común|identificaré animales propios de Chile con una fuente|Ubica huemul, picaflor de Arica y zorro de Darwin en fichas y mapa;¿Qué significa estar en peligro?|distinguiré población amenazada de un animal herido|Interpreta un caso donde quedan pocos hábitats disponibles;Amenazas al hábitat|relacionaré una amenaza concreta con sus efectos|Construye una cadena entre basura, agua contaminada y alimentación de fauna;Medidas que sí ayudan|propondré una acción viable y explicaré su mecanismo|Evalúa no alimentar fauna, cuidar senderos y denunciar comercio ilegal con ayuda adulta")),
"CN02 OA 06": ("Actividad humana, animales y hábitats", "Reconocer cambios humanos visibles en ambientes cercanos.", "actividad humana, impacto, hábitat, contaminación, ruido, fragmentación y mitigación", "Fotografías antes/después, casos ficticios locales y organizador causa-efecto.", "afirmar que toda actividad humana es dañina o confundir acción con efecto", _steps("Observar cambios sin adivinar|describiré diferencias entre dos imágenes del mismo lugar|Compara una ribera antes y después de una construcción separando observación de inferencia;Cadenas de efectos|conectaré una actividad con un cambio y una consecuencia para animales|Relaciona luces nocturnas con conducta de aves mediante un caso dado;Impactos positivos y negativos|compararé acciones humanas por su efecto|Contrasta retirar basura, plantar especies nativas y circular fuera de senderos;Comunicar una propuesta|explicaré un problema, evidencia y medida posible|Crea un mensaje para la comunidad que evite culpas generales y explique cómo ayuda la acción")),
"CN02 OA 07": ("Órganos y estructuras fundamentales del cuerpo", "Ubicar partes externas y reconocer que el cuerpo tiene estructuras internas.", "corazón, pulmón, estómago, esqueleto, músculo, ubicación y función", "Silueta corporal, modelos o imágenes anatómicas simples y estetoscopio opcional.", "ubicar órganos por dibujos simbólicos o afirmar que cada estructura trabaja aislada", _steps("Un mapa interior aproximado|ubicaré corazón, pulmones y estómago respetando posiciones relativas|Coloca tarjetas en una silueta y contrasta con un esquema simple;Corazón y pulmones|explicaré cómo participan al llevar oxígeno y mover sangre|Siente pulso y respiración en reposo sin convertirlo en prueba médica;Estómago|relacionaré este órgano con la transformación del alimento|Sigue un recorrido simplificado desde boca a estómago evitando decir que allí termina todo;Esqueleto y músculos|modelaré cómo sostén y movimiento trabajan juntos|Construye una articulación con cartón y elásticos y explica límites del modelo")),
"CN02 OA 08": ("Actividad física, músculos y corazón", "Reconocer cambios corporales normales después de moverse.", "actividad física, músculo, corazón, pulso, respiración, hábito, descanso y seguridad", "Espacio despejado, cronómetro opcional, escala de percepción y agua disponible.", "igualar beneficio con agotamiento o comparar rendimiento entre estudiantes", _steps("Antes y después de movernos|observaré pulso y respiración sin competir|Registra palabras o símbolos antes y después de caminar un minuto;Músculos en acción|identificaré músculos que se contraen durante movimientos simples|Compara ponerse de puntillas, empujar pared y levantar brazos;El corazón responde|explicaré por qué aumenta el latido durante la actividad|Usa un modelo de reparto de oxígeno y evita decir que el corazón se cansa de modo dañino;Un hábito posible|propondré actividad segura, frecuente y adaptada|Diseña una semana con juegos activos, pausas y descanso sin metas de peso o apariencia")),
"CN02 OA 09": ("Propiedades y cambios del agua", "Explorar agua con recipientes y normas de seguridad.", "escurrir, recipiente, disolver, transparente, inodoro, evaporar, congelar y temperatura", "Agua potable para experimentar, recipientes transparentes, sal, azúcar, arena, cucharas y bandejas.", "concluir que todo sólido desaparece al mezclarlo o probar sustancias para identificarlas", _steps("El agua escurre y toma forma|observaré qué cambia y qué se conserva al trasvasar|Pasa igual volumen entre vaso y bandeja y distingue forma de cantidad;Transparente e inodora|describiré propiedades sin usar el gusto|Compara agua limpia con agua coloreada y aprende que transparente no significa siempre potable;Disolver no es desaparecer|compararé sal, azúcar y arena en igual volumen|Mezcla por el mismo tiempo, deja reposar y registra qué se observa;Evaporación|investigaré qué condiciones aceleran la pérdida de agua|Compara dos paños húmedos en condiciones seguras cambiando sólo ventilación o superficie;Congelación y retorno|describiré cambios por temperatura y reversibilidad|Observa registros preparados de agua antes y después del congelador, deja derretir y compara")),
"CN02 OA 10": ("Estados sólido, líquido y gaseoso del agua", "Reconocer hielo y agua líquida como la misma sustancia en estados distintos.", "sólido, líquido, gas, vapor de agua, forma, volumen, temperatura y cambio", "Hielo, agua, recipientes y fotografías de vapor/condensación; adulto maneja fuentes de calor.", "llamar humo a todo gas visible o creer que el frío se convierte en agua", _steps("Agua sólida|describiré forma y comportamiento del hielo|Compara cubos en recipientes distintos sin probarlos ni mantenerlos en la mano;Agua líquida|explicaré por qué toma la forma del recipiente y puede escurrir|Trasvasa un volumen marcado y registra forma y nivel;Vapor y gas|reconoceré que el vapor de agua puede estar aunque no siempre se vea|Observa a distancia una demostración adulta y diferencia nube de gotitas y gas invisible;Comparar y transformar|organizaré evidencia de cambios entre estados|Completa un diagrama hielo-agua-vapor indicando calentamiento o enfriamiento")),
"CN02 OA 11": ("Ciclo del agua y cuidado del recurso", "Reconocer lluvia, nubes y agua en ambientes cercanos.", "evaporación, condensación, precipitación, acumulación, ciclo, recurso y cuidado", "Modelo en bolsa sellada o recipiente transparente, diagrama y casos de uso cotidiano.", "dibujar el ciclo como flechas memorizadas sin explicar procesos o creer que el agua se crea en las nubes", _steps("Agua que cambia y circula|seguiré una gota por distintos lugares y estados|Relata el recorrido desde océano a nube, lluvia, río y océano sin señalar un inicio único;Evaporación y condensación|distinguiré subir como vapor de formar gotitas|Observa un modelo cerrado y etiqueta dónde ocurre cada cambio;Precipitación y acumulación|explicaré cómo el agua vuelve y se reúne|Compara lluvia, nieve y granizo y ubica ríos, lagos, suelo y mar;Agua preciada|propondré cuidados cuyo efecto pueda explicar|Evalúa cerrar la llave, reparar filtraciones y no contaminar cursos de agua")),
"CN02 OA 12": ("Observación del tiempo atmosférico", "Describir el tiempo del día con observaciones directas.", "tiempo atmosférico, precipitación, viento, temperatura, nubosidad, registro y cambio", "Calendario meteorológico, cinta para viento, termómetro disponible e imágenes.", "confundir tiempo atmosférico con estación o inferir temperatura sólo por ropa usada", _steps("Mirar con criterios|describiré nubosidad, precipitación y viento sin decir sólo bonito o feo|Completa un registro del patio con símbolos y una frase observable;Precipitaciones distintas|distinguiré lluvia, granizo y nieve por su forma y condiciones|Clasifica imágenes verificadas sin manipular hielo como si fuera granizo;Viento y temperatura|usaré indicadores e instrumentos para describir|Compara movimiento de cintas y lectura de termómetro a la sombra;Cambios durante el año|compararé registros de fechas distintas sin generalizar desde un día|Construye una afirmación prudente con cuatro semanas de datos")),
"CN02 OA 13": ("Instrumentos para medir el tiempo atmosférico", "Usar marcas y unidades simples para comparar observaciones.", "instrumento, termómetro, pluviómetro, veleta, medición, escala, dirección y registro", "Botella preparada por adulto, regla, veleta simple, termómetro seguro y tabla.", "fabricar un objeto decorativo sin calibrarlo o mover el instrumento entre mediciones", _steps("¿Qué queremos medir?|relacionaré cada pregunta con un instrumento|Empareja temperatura-termómetro, lluvia-pluviómetro y dirección-veleta;Construir un pluviómetro|armaré y marcaré un recipiente estable con ayuda adulta|Define cero, marcas regulares y ubicación abierta, no recolecta agua para beber;Leer temperatura|registraré el valor sin sostener ni alterar el termómetro|Compara lecturas a sombra y sol explicando por qué la ubicación debe mantenerse;Veleta y estación local|usaré dirección de viento y organizaré un registro|Construye o usa una veleta, fija referentes cardinales y presenta datos de varios días")),
"CN02 OA 14": ("Tiempo atmosférico, estaciones y seres vivos", "Reconocer cambios estacionales observables sin asumir que son iguales en todo Chile.", "estación, temperatura, precipitación, horas de luz, ser vivo, ambiente y patrón", "Registros de localidades chilenas, fotografías fechadas y organizadores comparativos.", "aplicar el modelo de cuatro estaciones de otra región a todo Chile o explicar un patrón con un solo día", _steps("Una estación no es un tipo de día|distinguiré tiempo diario de patrón estacional|Compara un día frío de primavera con varios registros del invierno;Chile tiene contrastes|compararé estaciones en dos localidades usando datos|Examina Arica y Punta Arenas sin usar caliente/frío como única descripción;Respuestas de seres vivos|relacionaré cambios de luz, agua o temperatura con plantas y animales|Analiza floración, migración o cambios de actividad con evidencia dada;Explicar un patrón local|construiré una explicación que conecte estación, tiempo y efecto|Usa una tabla mensual para explicar un cambio y declarar qué datos faltan")),
}


H = {
"HI02 OA 01": ("Modos de vida de pueblos originarios precolombinos", "Reconocer que distintos pueblos habitaron diversos territorios antes de la llegada española.", "pueblo, precolombino, territorio, nómada, sedentario, vivienda, tecnología y fuente", "Mapa físico de Chile, imágenes y fuentes breves identificadas; evita disfraces o imitaciones ceremoniales.", "hablar de todos los pueblos como uno solo o describirlos únicamente en pasado", _steps("Territorios diversos|ubicaré pueblos en relación con paisajes y recursos|Relaciona aimara, mapuche, chango y selk'nam con fuentes y zonas sin convertir fronteras actuales en límites exactos;Moverse o permanecer|distinguiré vida nómada y sedentaria sin jerarquizarlas|Compara movilidad changa y aldeas agrícolas a partir de vivienda y actividades;Tecnologías para vivir|explicaré cómo herramientas y viviendas respondían al medio|Analiza embarcación, terraza de cultivo y vivienda usando forma, material y uso;Actividades y organización|describiré trabajos y roles sin aplicar estereotipos actuales|Lee fuentes que muestran labores diversas de mujeres, hombres, niñas y niños y señala límites;Una descripción con fuentes|presentaré el modo de vida de un pueblo conectando territorio, recursos y cultura|Construye un panel con mapa, tres rasgos y dos fuentes claramente identificadas")),
"HI02 OA 02": ("Continuidades y cambios en pueblos indígenas actuales", "Distinguir pasado y presente sin tratar a pueblos indígenas como desaparecidos.", "continuidad, cambio, presente, precolombino, cultura, idioma, comunidad y fuente", "Fuentes históricas y actuales con fecha y autor, mapa y testimonios públicos autorizados.", "suponer que conservar cultura significa no cambiar o hablar por una comunidad desde una sola fuente", _steps("Dos momentos, un mismo pueblo|ubicaré fuentes en pasado precolombino y presente|Ordena imágenes y textos mapuche, aimara o rapa nui por fecha sin juzgar autenticidad;Continuidades|identificaré una práctica o conocimiento que permanece con transformaciones|Sigue lengua, tejido o celebración usando dos fuentes y evita afirmar que todo sigue igual;Cambios con contexto|describiré un cambio y posibles condiciones históricas|Compara vivienda o transporte y distingue evidencia de explicación tentativa;Voces actuales|reconoceré que una fuente contemporánea expresa una perspectiva|Lee un testimonio público breve y formula qué sabemos y qué no;Comparación respetuosa|comunicaré continuidades y cambios sin congelar identidades|Completa una tabla antes-ahora-permanece/cambia y revisa generalizaciones")),
"HI02 OA 03": ("Aportes y carácter mestizo de la sociedad chilena", "Reconocer que la vida cotidiana reúne herencias de distintos pueblos.", "aporte, pueblo originario, español, mestizaje, lengua, alimento, tradición y evidencia", "Tarjetas de palabras, alimentos y prácticas con fuentes; mapa y organizador.", "asignar cada costumbre a un origen puro o presentar mestizaje como proceso sin conflicto", _steps("Palabras con historias|rastrearé palabras de origen indígena y español usadas en Chile|Investiga cancha, choclo o charquicán en una fuente dada y evita etimologías inventadas;Alimentos y técnicas|distinguiré producto, preparación e intercambio cultural|Analiza papa, trigo y formas de cocinar sin etiquetar un plato completo con un único origen;Tradiciones que se transforman|describiré un aporte y su cambio al encontrarse con otros|Examina una fiesta o práctica cotidiana mediante fuentes de distintas fechas;Sociedad mestiza y diversa|explicaré mestizaje con ejemplos y reconoceré su complejidad|Construye una explicación con dos aportes, una combinación y una pregunta pendiente")),
"HI02 OA 04": ("Aportes de inmigrantes a la diversidad chilena", "Reconocer que personas migran por razones diversas y participan en comunidades.", "migración, inmigrante, aporte, diversidad, comunidad, generación y fuente", "Mapas, biografías públicas breves y fuentes sobre aportes; sin solicitar historias familiares.", "reducir grupos a comidas típicas o atribuir un aporte a todas las personas de un origen", _steps("Migrar es una experiencia diversa|distinguiré origen, destino y razón sin generalizar|Lee dos biografías ficticias basadas en contextos históricos y ubica recorridos;Aportes en trabajo y conocimiento|reconoceré contribuciones en oficios, ciencias, comercio y artes|Relaciona una institución o práctica con fuentes que explican quiénes participaron;Encuentros culturales|explicaré cómo una práctica se adapta en Chile|Examina palabras, arquitectura o alimentos diferenciando origen y transformación;Diversidad con nombres y fuentes|presentaré un aporte evitando estereotipos|Crea una ficha con persona o comunidad, época, evidencia, aporte y límite de la fuente")),
"HI02 OA 05": ("Patrimonio cultural de Chile y la región", "Reconocer relatos, fiestas, comidas, edificios y lugares valorados por comunidades.", "patrimonio, tangible, intangible, tradición, memoria, comunidad, región y protección", "Fotografías y relatos con procedencia, mapa regional y fichas de análisis.", "creer que patrimonio es sólo antiguo o decidir su valor sin considerar a la comunidad", _steps("¿Qué vuelve patrimonial a algo?|distinguiré objeto común de bien o práctica valorada colectivamente|Compara una receta familiar, un monumento y una canción preguntando quién los valora y transmite;Patrimonio tangible|describiré una construcción o sitio y su relación con la historia|Lee una fotografía y una placa de un sitio regional sin inferir más de lo visible;Patrimonio intangible|reconoceré saberes y prácticas que viven al realizarse|Analiza tradición oral, oficio o fiesta evitando convertirla en espectáculo;Patrimonio cercano|investigaré una expresión regional con fuentes dadas|Ubica, describe y pregunta por un ejemplo de la región sin exigir exposición familiar;Cuidar con la comunidad|propondré una medida que respete uso, acceso y significado|Evalúa restaurar, señalizar, registrar o regular visitas según un caso")),
"HI02 OA 06": ("Lectura y dibujo de planos simples", "Usar derecha, izquierda, cerca y lejos con un referente explícito.", "plano, vista superior, referencia, símbolo, leyenda, ruta y posición relativa", "Plano del aula o escuela, objetos, papel cuadriculado y tarjetas de símbolos.", "dibujar objetos de frente o usar derecha e izquierda sin señalar desde dónde se observa", _steps("Mirar desde arriba|interpretaré objetos representados en vista superior|Empareja mesa, silla y puerta con símbolos vistos desde arriba;Referencias y posición|ubicaré un lugar respecto de un punto acordado|Describe la biblioteca a la derecha de la entrada y comprueba cambiando el referente;Símbolos y leyenda|crearé símbolos simples y los explicaré en una leyenda|Reduce detalles de patio, baño y escalera sin perder distinción;Dibujar y seguir una ruta|elaboraré un plano que otra persona pueda usar|Traza una ruta segura desde sala a patio, un compañero la sigue y marca ambigüedades")),
"HI02 OA 07": ("Ubicación de Chile y Sudamérica", "Distinguir globo terráqueo y mapa como representaciones de la Tierra.", "globo, mapa, Chile, Santiago, región, capital regional, límite y punto cardinal", "Globo, mapas políticos y físicos actualizados y rosa de los vientos.", "confundir tamaño del dibujo con tamaño real o ubicar Santiago como si fuera todo Chile", _steps("Del globo al continente|ubicaré Sudamérica y Chile en dos representaciones|Compara forma, orientación y lo que se distorsiona entre globo y mapa;Chile, región y ciudades|distinguiré país, región, capital nacional y capital regional|Construye una secuencia espacial desde Sudamérica hasta la localidad;Países limítrofes|describiré ubicación relativa usando norte, este y noreste cuando corresponda|Ubica Perú, Bolivia y Argentina respecto de Chile con apoyo de rosa de vientos;Otros países sudamericanos|comunicaré relaciones espaciales sin memorizar una lista aislada|Resuelve pistas como al este de Chile y al norte de Argentina verificando en mapa")),
"HI02 OA 08": ("Paisajes de las zonas norte, centro y sur", "Observar elementos naturales y humanos en paisajes chilenos.", "zona, paisaje, relieve, cordillera, costa, desierto, valle, volcán, archipiélago y fuente", "Mapa físico, fotografías fechadas y fichas de vocabulario geográfico.", "clasificar por una postal estereotipada o confundir zona geográfica con región administrativa", _steps("Leer un paisaje|separaré elementos naturales y humanos sin suponer la zona|Describe una foto con costa, ciudad y cerros antes de clasificar;Zona norte|usaré desierto, altiplano, valle y costa con ejemplos localizados|Compara Arica, altiplano y valle del Elqui sin decir que todo el norte es desierto;Zona centro|reconoceré valles, costa, cordillera y ciudades en combinación|Ubica un paisaje mediterráneo y explica qué elementos no bastan por sí solos;Zona sur|distinguiré lagos, volcanes, islas, fiordos y bosques según ubicación|Contrasta Araucanía, Chiloé y Patagonia con mapa y fotos;Clasificar con más de una fuente|justificaré la zona probable y reconoceré incertidumbre|Resuelve tres casos usando fotografía, mapa y descripción, indica la pista decisiva")),
"HI02 OA 09": ("Patrimonio natural de Chile y la región", "Reconocer paisajes, flora y fauna característicos de distintos lugares.", "patrimonio natural, paisaje, flora, fauna, parque nacional, región y conservación", "Mapa, fichas oficiales de áreas protegidas e imágenes con procedencia.", "creer que patrimonio natural no incluye presencia o cuidado humano o elegir sólo por belleza", _steps("Naturaleza valorada y cuidada|explicaré por qué un lugar o especie puede ser patrimonio|Compara un humedal urbano y un parque remoto preguntando valor, amenaza y comunidad;Flora y fauna característica|relacionaré especies con un ambiente sin usarlas como decoración|Ubica araucaria, flamenco y huemul mediante fuentes y hábitats;Parques nacionales|identificaré qué protegen y qué normas orientan la visita|Lee un mapa y señalética de un área protegida;Patrimonio regional|presentaré un ejemplo cercano con ubicación, rasgo y cuidado|Construye una ficha regional y propone una acción respetuosa y verificable")),
"HI02 OA 10": ("Pueblos originarios en el mapa de Chile", "Reconocer zonas norte, centro y sur en un mapa.", "ubicación, zona norte, centro, sur, territorio, pueblo, mapa y escala", "Mapa mudo de Chile, mapas históricos aproximados y fichas con fuentes.", "dibujar territorios como fronteras rígidas actuales o ubicar pueblos sólo donde hoy vive más población", _steps("El mapa es una representación|leeré título, orientación y leyenda antes de ubicar|Compara mapa político actual con uno de áreas culturales aproximadas;Pueblos de la zona norte|ubicaré aimara, atacameño/licanantay y diaguita con referencias|Relaciona altiplano, oasis y valles usando áreas amplias, no puntos exactos;Centro y centro-sur|ubicaré pueblos como picunche y mapuche reconociendo movilidad y amplitud|Usa ríos y cordilleras como referencias sin fijar límites absolutos;Sur y territorios australes|ubicaré chono, kawésqar, yagán y selk'nam según fuentes|Completa un mapa con leyenda y una nota que explique que los territorios cambiaron")),
"HI02 OA 11": ("Geografía y recursos en modos de vida originarios", "Reconocer agua, temperatura y vegetación como características de un lugar.", "recurso, necesidad, agua, temperatura, vegetación, alimentación, abrigo, vivienda y relación", "Mapas físicos, fuentes de objetos y viviendas, fotografías y organizador causal.", "explicar decisiones culturales como respuesta automática al ambiente o pensar que un recurso determina toda la vida", _steps("Necesidades y posibilidades|distinguiré necesidad de recurso y práctica cultural|Relaciona abrigo con lana, pieles o fibras sin afirmar una única solución;Agua y alimentación|explicaré cómo disponibilidad de agua influye sin determinar por completo|Compara oasis agrícola y canales del sur mediante fuentes;Temperatura y abrigo|conectaré clima, materiales disponibles y tecnologías|Analiza textiles andinos y viviendas australes respetando diferencias;Vegetación y vivienda|usaré evidencia para explicar selección de materiales|Contrasta madera, piedra, totora o piel según lugar y fuente;Una relación, no una receta|elaboraré una explicación que incluya ambiente, conocimiento y decisión humana|Resuelve un caso con mapa, recurso y objeto, indicando otra explicación posible")),
"HI02 OA 12": ("Respeto, responsabilidad, tolerancia y empatía en acción", "Reconocer acciones que cuidan a otras personas y espacios comunes.", "respeto, responsabilidad, tolerancia, empatía, derecho, acuerdo y consecuencia", "Casos ficticios, tarjetas de decisiones y acuerdos del curso.", "evaluar rasgos personales en vez de acciones observables o confundir tolerar con aceptar daño", _steps("Respeto en acciones concretas|distinguiré cortesía, cuidado y respeto de derechos|Analiza interrupciones, uso de materiales y nombres preferidos en casos ficticios;Responsabilidad reparable|asumiré un encargo y reconoceré qué hacer si no lo cumplo|Diseña un plan para materiales comunes que incluya reparación, no castigo humillante;Tolerancia y límites|respetaré diferencias sin aceptar discriminación o agresión|Compara desacuerdo, burla y daño, decide cuándo pedir ayuda adulta;Empatía que pregunta|consideraré otra perspectiva sin hablar por la persona|Reformula una respuesta que supone sentimientos en una que pregunta y ofrece apoyo;Proyecto de convivencia|aplicaré una acción y evaluaré su efecto en el grupo|Prueba durante una semana un acuerdo y recoge evidencia sin calificar personalidades")),
"HI02 OA 13": ("Honestidad en juegos y trabajo escolar", "Distinguir verdad, error y engaño en situaciones ficticias.", "honestidad, verdad, regla, error, consecuencia, reconocer y reparar", "Historias ficticias, reglas de juegos y tarjetas de alternativas.", "entender honestidad como confesar públicamente asuntos privados o castigar el error involuntario", _steps("Error no es trampa|distinguiré equivocación de acción deliberada|Compara mover una ficha por confusión con ocultar una jugada sabiendo la regla;Decir la verdad con cuidado|comunicaré lo ocurrido sin inventar ni exponer información privada|Practica frases sobre un material roto en un caso ficticio;Reconocer y reparar|propondré una reparación relacionada con la acción|Evalúa devolver, reponer, corregir o pedir ayuda según distintos casos;Reglas justas y honestidad|aplicaré reglas conocidas y aceptaré revisión|Juega una ronda breve, registra una duda y resuélvela consultando la regla común")),
"HI02 OA 14": ("Normas para seguridad, aprendizaje e inclusión", "Comprender que una norma responde a una necesidad compartida.", "norma, riesgo, evacuación, accesibilidad, turno, espacio común, patrimonio y explicación", "Planos de evacuación, señaléticas y casos ficticios de aula y comunidad.", "obedecer sin comprender el propósito o proponer reglas que excluyen para mantener orden", _steps("Norma, riesgo y consecuencia|explicaré qué riesgo reduce una norma|Relaciona cruzar por paso habilitado con visibilidad y conducta vial;Evacuación y emergencia|aplicaré una ruta y reconoceré instrucciones adultas|Lee el plano escolar sin simular una emergencia no autorizada;Accesibilidad e inclusión|identificaré barreras y normas que permiten participar|Analiza rampa bloqueada, zona de silencio y turnos flexibles;Ambiente de aprendizaje|propondré acuerdos que cuiden voz, materiales y participación|Revisa si una regla ayuda a aprender o sólo controla conductas;Patrimonio y ambiente|explicaré una norma de cuidado para un espacio visitado|Diseña señalética con acción, razón y alternativa accesible")),
"HI02 OA 15": ("Servicios e instituciones que benefician a la comunidad", "Reconocer necesidades que se resuelven de manera comunitaria.", "servicio, transporte, comunicación, mercado, institución, patrimonio y beneficio común", "Mapa local, fotografías de servicios y casos ficticios de necesidades.", "confundir servicio con edificio o pensar que sólo beneficia a quien paga directamente", _steps("Necesidad y servicio|relacionaré una necesidad con el servicio que ayuda a resolverla|Empareja trasladarse, comunicar, abastecerse y proteger patrimonio con redes, no sólo lugares;Transporte y comunicación|compararé cómo conectan personas, bienes e información|Sigue el recorrido de una carta y de un producto hasta una localidad;Mercado e intercambio|reconoceré trabajos y reglas que permiten abastecimiento|Analiza una feria destacando productores, transporte, vendedores y consumidores sin jerarquizar oficios;Instituciones de patrimonio|explicaré cómo museo, biblioteca, archivo o parque protege y comparte|Resuelve un caso de objeto histórico, documento y especie nativa eligiendo apoyo pertinente")),
"HI02 OA 16": ("Cuidado compartido de los espacios públicos", "Distinguir espacio público, común y privado en contextos cercanos.", "espacio público, bien común, derecho, responsabilidad, uso, cuidado y participación", "Fotografías de espacios, plano local y casos ficticios.", "atribuir el cuidado sólo a autoridades o proponer prohibir usos en lugar de compatibilizarlos", _steps("¿De quién es el espacio público?|explicaré por qué pertenece y beneficia a muchas personas|Compara plaza, patio escolar, vivienda y comercio sin usar sólo quién limpia;Usos diversos|reconoceré que distintas personas necesitan usar el mismo lugar|Analiza juegos, descanso, movilidad y accesibilidad en una plaza;Problema, causa y efecto|describiré un deterioro sin culpar a un grupo|Examina basura, ruido o mobiliario dañado con evidencia y preguntas;Acciones personales y colectivas|distinguiré cuidado cotidiano, organización y labor municipal|Clasifica acciones según quién puede realizarlas y qué coordinación requieren;Propuesta para un lugar|diseñaré una acción participativa, segura y evaluable|Crea un plan para patio o plaza con consulta, tarea, responsable y señal de mejora")),
}


def _transversal(code: str, lesson_index: int, goal: str) -> list[dict[str, str]]:
    number = int(code.rsplit(" ", 1)[-1])
    if code.startswith("LE"):
        c, text = LANGUAGE_ATTITUDES[(number + lesson_index - 1) % len(LANGUAGE_ATTITUDES)]
        return [{"code": c, "type": "Actitud", "application": f"Se promueve {text} mientras el estudiante trabaja «{goal}»; se observa en una decisión comunicativa, no como rasgo de personalidad."}]
    skills, attitudes = (SCIENCE_SKILLS, SCIENCE_ATTITUDES) if code.startswith("CN") else (HISTORY_SKILLS, HISTORY_ATTITUDES)
    sc, st = skills[(number * 2 + lesson_index) % len(skills)]
    ac, at = attitudes[(number + lesson_index * 2) % len(attitudes)]
    return [
        {"code": sc, "type": "Habilidad", "application": f"Se observa al {st} durante «{goal}» y se conserva una evidencia localizable en la producción."},
        {"code": ac, "type": "Actitud", "application": f"Se promueve {at} mediante decisiones propias de la tarea; no se califica obediencia, rapidez ni personalidad."},
    ]


def _lesson(code: str, index: int, stage: tuple[str, str, str], profile: tuple, discipline: str) -> dict:
    title, goal, challenge = stage
    topic, _, _, materials, misconception, _ = profile
    if discipline == "language":
        opening = (
            f"Lee o escucha sin explicación previa este caso: {challenge} Registra una primera respuesta y una palabra o rasgo que la sostiene.",
            f"Presenta dos respuestas posibles al desafío «{challenge}». Cada estudiante elige provisionalmente una y anota qué necesitaría comprobar.",
            f"Entrega el fragmento, formato o situación central: {challenge} Un ensayo oral breve permite detectar qué necesita modelado.",
        )[index % 3]
        model = f"Piensa en voz alta con un ejemplo distinto al que resolverán: {challenge} Señala qué parte del texto permite decidir y corrige una interpretación plausible pero débil."
        guided = (
            f"En lectura compartida anotan una variación de «{title.lower()}» y vuelven a palabras, signos o rasgos concretos antes de acordar una respuesta.",
            f"Ordenan o clasifican ejemplos breves del foco «{title.lower()}», explican el criterio a otra pareja y revisan un caso discutible.",
            f"Ensayan oralmente una respuesta o producción de «{title.lower()}»; un compañero indica qué comprendió y el autor decide una mejora.",
            f"Comparan dos versiones del desafío de «{title.lower()}» y justifican cuál cumple mejor el propósito y qué tomarían de la otra.",
        )[index % 4]
        evidence = f"Producción o interpretación individual vinculada a «{title.lower()}», con una pista textual o decisión de escritura explicada."
        support = "Anticipa vocabulario, segmenta el texto, permite ensayo oral y ofrece una frase inicial o lectura compartida; retira el apoyo antes de la evidencia individual."
        extension = "Cambia audiencia, propósito o fragmento y pide explicar qué debe modificarse; evita aumentar sólo la cantidad de copia."
        coordination = "El docente conduce la comprensión o producción; educación diferencial acuerda acceso al texto, apoyo visual, lectura compartida o respuesta oral sin entregar la interpretación ni reducir el propósito comunicativo."
    elif discipline == "science":
        opening = (
            f"Muestra el fenómeno, imagen o conjunto sin nombrar la conclusión: {challenge} Cada estudiante registra observo/pienso y una pregunta.",
            f"Plantea dos predicciones razonables para este caso: {challenge} El curso elige provisionalmente qué evidencia permitiría distinguirlas.",
            f"Entrega un registro incompleto relacionado con «{title.lower()}». Antes de completarlo, cada estudiante identifica qué dato falta y por qué importa.",
        )[index % 3]
        model = f"Separa pregunta, predicción, observación y explicación usando este caso: {challenge} Nombra qué se observa directamente y qué se infiere."
        guided = (
            f"En equipos con roles rotativos observan o clasifican un caso de «{title.lower()}»; registran individualmente antes de construir la tabla común.",
            f"Repiten o analizan una comparación controlada del foco «{title.lower()}», mantienen una condición y revisan si los datos apoyan la predicción.",
            f"Construyen un modelo sencillo de «{title.lower()}», señalan qué representa cada parte y anotan al menos una limitación del modelo.",
            f"Interpretan registros de dos grupos sobre «{title.lower()}», buscan coincidencias y diferencias y deciden si hace falta repetir la observación.",
        )[index % 4]
        evidence = f"Registro individual de «{title.lower()}» con observación o dato, comparación y conclusión prudente que responda la pregunta."
        support = "Reduce variables, ofrece una tabla con dibujos y palabras, modela una observación sin explicar el resultado y permite dictado al adulto conservando la decisión científica."
        extension = "Propone un caso que no encaja a primera vista, pide una nueva predicción y exige señalar qué dato adicional permitiría decidir."
        coordination = "El docente conduce la indagación y la seguridad; educación diferencial ajusta manipulación, campo visual, registro o comunicación sin sustituir la observación ni afirmar diagnósticos."
    else:
        opening = (
            f"Proyecta la fuente, mapa o caso sin entregar su interpretación: {challenge} Cada estudiante anota qué ve, de dónde parece provenir y una pregunta.",
            f"Presenta dos afirmaciones sobre el desafío «{challenge}». El curso marca cuál tiene respaldo visible y qué evidencia le falta a la otra.",
            f"Ubica el caso «{title.lower()}» en un mapa, línea de tiempo o situación común antes de explicarlo: {challenge}",
        )[index % 3]
        model = f"Interroga una fuente, mapa o caso identificando qué muestra, de cuándo o dónde es y qué no permite concluir: {challenge} Distingue evidencia de interpretación."
        guided = (
            f"En parejas completan observar-preguntar-concluir con una fuente sobre «{title.lower()}» y tachan cualquier afirmación que exceda lo que la fuente permite.",
            f"Trabajan en estaciones con mapa, imagen y texto breve sobre «{title.lower()}»; conectan dos fuentes y conservan una pregunta abierta.",
            f"Ordenan, ubican o comparan evidencias del foco «{title.lower()}», y otra pareja intenta reconstruir el criterio utilizado.",
            f"Analizan un caso ciudadano o histórico de «{title.lower()}», distinguen personas, acciones y consecuencias y revisan una generalización.",
        )[index % 4]
        evidence = f"Explicación, mapa o decisión individual sobre «{title.lower()}», apoyada en una fuente, relación espacial o razón ciudadana explícita."
        support = "Ofrece mapa ampliado, línea de tiempo, vocabulario visual o dos fuentes seleccionadas; permite respuesta oral o gráfica, pero mantiene la comparación y la justificación."
        extension = "Agrega una fuente con otra perspectiva o escala y pide revisar la conclusión, señalando continuidad, cambio, ubicación o consecuencia."
        coordination = "El docente conduce el trabajo con fuentes y evita estereotipos; educación diferencial facilita lectura de mapas, organización temporal o expresión sin proporcionar la conclusión histórica o cívica."
    return {
        "title": title,
        "purpose": f"Construir comprensión de {topic.lower()} mediante el foco «{title.lower()}», haciendo visible el razonamiento disciplinar y su revisión.",
        "goal": f"Hoy {goal}.",
        "opening": opening,
        "model": model,
        "guided": guided,
        "independent": f"Resuelve una versión nueva del desafío de {title.lower()} sin copiar el modelo; explica una decisión y comprueba con el texto, dato, fuente o criterio trabajado.",
        "ticket": f"{challenge} Responde en forma breve y marca la evidencia que sostiene tu decisión.",
        "materials": materials,
        "support": support,
        "extension": extension,
        "evidence": evidence,
        "criteria": ["responde al foco específico de la clase", "usa evidencia disciplinar pertinente", "explica una decisión y revisa una posible confusión"],
        "next_step": "Avanza cuando la evidencia y la explicación coinciden; si no, identifica si la dificultad está en el acceso, el concepto o la justificación y reenseña con un ejemplo diferente.",
        "short_version": "Conserva desafío específico, modelado breve, una práctica conjunta, evidencia individual y ticket; reduce repeticiones, no la demanda del OA.",
        "home_task": "Recupera un ejemplo cotidiano seguro relacionado con la clase y explícalo mediante dibujo, nota u oralidad. No requiere internet, impresión, compras ni revelar información familiar.",
        "complementary": [
            "Recuperación: vuelve a un caso con menos elementos, conserva la misma relación y retorna después al desafío original.",
            f"Análisis de error: corrige un caso ficticio que muestra esta confusión: {misconception}.",
            "Transferencia: cambia una condición o incorpora una nueva evidencia y revisa la conclusión inicial.",
        ],
        "difficulty_actions": [
            {"signal": "Responde antes de examinar la evidencia", "action": "Pide señalar primero la palabra, dato, rasgo, fuente o ubicación que usará.", "check": "La respuesta nueva cita una evidencia pertinente."},
            {"signal": misconception.capitalize(), "action": support, "check": "Resuelve un caso nuevo sin repetir la confusión y explica la diferencia."},
            {"signal": "Completa la actividad, pero no explica", "action": "Solicita comparar con una alternativa y nombrar el criterio decisivo.", "check": "La explicación permite reconstruir la decisión."},
        ],
        "specialist_coordination": coordination,
        "transversal": _transversal(code, index, goal),
    }


def _build(code: str, table: dict, discipline: str, axis: str) -> dict | None:
    profile = table.get(code)
    if not profile:
        return None
    topic, prior, vocabulary, _, misconception, stages = profile
    subject_slug = {"language": "lenguaje-comunicacion", "science": "ciencias-naturales", "history": "historia-geografia-ciencias-sociales"}[discipline]
    return {
        "topic": topic,
        "pedagogical_explanation": f"{topic} exige una progresión de desempeños observables, no una actividad repetida. La secuencia parte de {prior[0].lower() + prior[1:]} y enfrenta explícitamente la confusión «{misconception}».",
        "prerequisites": prior,
        "vocabulary": vocabulary,
        "official_alignment": {
            "units": [f"Eje {axis} · organización interna en {len(stages)} clases"],
            "unit_origin": "Organización interna derivada del eje y del OA; no se presenta como unidad oficial del programa de estudio.",
            "indicators": [f"{goal[0].upper() + goal[1:]}." for _, goal, _ in stages[:3]],
            "indicator_origin": "Criterios de progresión internos derivados del verbo, contenido y alcance del OA oficial",
            "source": f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/{subject_slug}/2-basico/{code.lower().replace(' ', '-')}"
        },
        "lessons": [_lesson(code, i, stage, profile, discipline) for i, stage in enumerate(stages)],
    }


def build_sequence(code: str) -> dict | None:
    if code in L:
        return _build(code, L, "language", "Lectura, escritura y comunicación oral")
    if code in S:
        return _build(code, S, "science", "Ciencias de la Vida, Físicas y de la Tierra")
    if code in H:
        return _build(code, H, "history", "Historia, Geografía y Formación Ciudadana")
    return None


def build_transversal_integration(item: dict) -> dict:
    code = item["oa_code"]
    text = item["oa_text"].split("Unidad de Currículum", 1)[0].strip().rstrip(".")
    if code.startswith("de Actitud LE02"):
        kind, discipline = "Actitud", "language"
    elif code.startswith(("de Habilidad CN02", "de Actitud CN02")):
        kind, discipline = ("Habilidad" if "Habilidad" in code else "Actitud"), "science"
    else:
        kind, discipline = ("Habilidad" if "Habilidad" in code else "Actitud"), "history"
    lessons = []
    for index, (phase, _) in enumerate(item["phases"]):
        contexts = {
            "language": ("un texto leído, escuchado o producido", "decisión comunicativa"),
            "science": ("una observación o indagación de un OA de contenido", "decisión de observación, registro o seguridad"),
            "history": ("una fuente, mapa o situación ciudadana de un OA de contenido", "decisión temporal, espacial, documental o cívica"),
        }
        context, decision = contexts[discipline]
        lessons.append({
            "title": f"{phase}: integración observable",
            "purpose": f"Integrar el OA transversal «{text}» dentro de {context}, sin tratarlo como contenido aislado ni como juicio sobre la personalidad.",
            "goal": f"Hoy haré visible una {decision} y explicaré cómo me ayudó a aprender.",
            "opening": f"Presenta un caso breve de {context} y dos respuestas: una nombra el OA transversal, la otra muestra una acción observable. El curso identifica cuál constituye evidencia.",
            "model": f"Modela {decision} dentro de una tarea real y señala el instante exacto donde se manifiesta: {text}. Evita una charla moral separada del contenido.",
            "guided": "Resuelven una tarea breve en parejas, marcan dónde aplicaron la habilidad o actitud y comparan evidencias sin calificar rapidez, docilidad ni rasgos personales.",
            "independent": f"Cada estudiante completa una tarea nueva de {context}, encierra la evidencia del OA transversal y explica una decisión propia.",
            "ticket": "Muestra una parte de tu producción que evidencie el OA transversal y completa: esto ayudó a mi aprendizaje porque…",
            "materials": "Materiales del OA disciplinar anfitrión, una tarjeta con el OA transversal en lenguaje accesible y un marcador para localizar evidencia.",
            "support": "Ofrece dos ejemplos contrastados y una frase inicial; admite señalar, dibujar o explicar oralmente, manteniendo la acción disciplinar.",
            "extension": "Transfiere la misma habilidad o actitud a otro OA de contenido y compara cómo cambia su manifestación observable.",
            "evidence": f"Producción disciplinar con una marca y explicación atribuible al estudiante sobre la aplicación de esta {kind.lower()}.",
            "criteria": ["resuelve contenido disciplinar pertinente", f"hace observable la {kind.lower()}", "explica cómo influyó en una decisión o revisión"],
            "next_step": "Integra nuevamente en otro contexto si la evidencia depende del apoyo; diversifica la tarea cuando aparece con autonomía.",
            "short_version": "Conserva tarea disciplinar, acción observable, evidencia individual y ticket; elimina repetición, no la integración.",
            "home_task": "Explica con un ejemplo seguro cómo esta habilidad o actitud ayudó a comprender, revisar o cuidar una tarea. Puede responderse oralmente o con dibujo.",
            "complementary": ["Clasificar ejemplos y no ejemplos observables.", "Revisar una producción donde la acción está nombrada pero no aplicada.", "Transferir a otro eje de la asignatura."],
            "difficulty_actions": [
                {"signal": "Repite el nombre del OA, pero no lo usa", "action": "Pide señalar una acción concreta dentro de la tarea.", "check": "La evidencia puede localizarse en la producción."},
                {"signal": "Se transforma en evaluación conductual", "action": "Vuelve a la decisión disciplinar y elimina etiquetas personales.", "check": "La retroalimentación describe una acción modificable."},
                {"signal": "La integración desplaza el contenido", "action": "Recupera la pregunta del OA anfitrión y usa lo transversal como medio.", "check": "El ticket demuestra contenido e integración."},
            ],
            "specialist_coordination": "El docente mantiene el OA disciplinar como foco; profesionales de apoyo acuerdan una barrera, una acción y una evidencia accesible sin diagnosticar ni reducir la tarea.",
        })
    return {"generated_for": "2-basico", "lessons": lessons}
