"""Curated first-grade mathematics sequences grounded in MINEDUC indicators."""
from __future__ import annotations


def _step(title, goal, example, practice, ticket):
    return {"title": title, "goal": goal, "example": example, "practice": practice, "ticket": ticket}


MATH_SKILLS = (
    ("de Habilidad MA01 OAH a", "emplear diversas estrategias para resolver problemas"),
    ("de Habilidad MA01 OAH b", "comprobar enunciados con material concreto y gráfico"),
    ("de Habilidad MA01 OAH c", "expresar un problema con palabras propias"),
    ("de Habilidad MA01 OAH d", "describir situaciones del entorno con lenguaje matemático"),
    ("de Habilidad MA01 OAH e", "comunicar relaciones, patrones y reglas con expresiones matemáticas"),
    ("de Habilidad MA01 OAH f", "explicar soluciones y procedimientos propios"),
    ("de Habilidad MA01 OAH g", "aplicar modelos de suma, resta u orden de cantidades"),
    ("de Habilidad MA01 OAH h", "traducir representaciones y situaciones cotidianas a lenguaje matemático"),
    ("de Habilidad MA01 OAH i", "elegir representaciones concretas, pictóricas y simbólicas"),
    ("de Habilidad MA01 OAH j", "crear un relato a partir de una expresión matemática simple"),
)
MATH_ATTITUDES = (
    ("de Actitud MA01 OAA A", "trabajo ordenado y metódico"),
    ("de Actitud MA01 OAA B", "búsqueda flexible y creativa de soluciones"),
    ("de Actitud MA01 OAA C", "curiosidad e interés por aprender matemática"),
    ("de Actitud MA01 OAA D", "confianza progresiva en las propias capacidades"),
    ("de Actitud MA01 OAA E", "esfuerzo y perseverancia ante un desafío"),
    ("de Actitud MA01 OAA F", "expresión y escucha respetuosa de ideas"),
)


def transversal_links(oa_number: int, lesson_index: int, lesson_goal: str) -> list[dict[str, str]]:
    """Assign one observable skill and attitude to every core lesson."""
    skill_code, skill = MATH_SKILLS[(oa_number * 3 + lesson_index) % len(MATH_SKILLS)]
    attitude_code, attitude = MATH_ATTITUDES[(oa_number + lesson_index * 2) % len(MATH_ATTITUDES)]
    return [
        {"code": skill_code, "type": "Habilidad", "application": f"Se observa al {skill}. La evidencia se recoge durante la meta estudiantil «{lesson_goal}»."},
        {"code": attitude_code, "type": "Actitud", "application": f"Se promueve {attitude}: se retroalimenta la decisión y la revisión, no rapidez ni obediencia."},
    ]


SEQUENCES = {
    "MA01 OA 02": {
        "topic": "Números ordinales del primero al décimo en series y situaciones cotidianas",
        "explanation": "Los ordinales describen posición, no cantidad. La secuencia parte del propio cuerpo y filas visibles, incorpora cambios de referencia y culmina resolviendo problemas donde importa quién está antes, después o en una posición determinada.",
        "prerequisites": "Seguir una secuencia oral breve y distinguir inicio y final. No se exige leer las abreviaturas ordinales antes de comprender la posición.",
        "vocabulary": "primero, segundo, tercero, cuarto, quinto, sexto, séptimo, octavo, noveno, décimo, antes y después",
        "units": ["Unidad 1: Números, patrones repetitivos y unidades no estandarizadas en el tiempo"],
        "indicators": ["Indicar oralmente el orden de acciones realizadas.", "Indicar posiciones ordinales hasta el décimo en una fila.", "Resolver problemas de identificación de números ordinales."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17474.html",
        "materials": "Diez tarjetas con personajes, cinta para marcar una fila, tarjetas ordinales y objetos pequeños para ordenar.",
        "support": "Mantén visible el punto de inicio, usa cinco posiciones antes de ampliar a diez y permite responder señalando; vuelve luego al ordinal oral.",
        "extension": "Cambia el punto de referencia o intercambia dos elementos y explica todas las posiciones que se modifican.",
        "criteria": ["identifica el inicio de la serie", "nombra la posición y no la cantidad", "justifica usando antes, después o entre"],
        "difficulties": [("Cuenta elementos en vez de ubicar una posición", "Pregunta por un elemento concreto y marca el inicio de la fila.", "Nombra la posición de tres elementos sin decir cuántos hay."), ("Invierte el orden", "Recorre la fila físicamente desde la flecha de inicio.", "Ubica primero, quinto y décimo desde la misma referencia."), ("Memoriza nombres, pero no resuelve cambios", "Intercambia dos tarjetas y reconstruye las posiciones afectadas.", "Explica al menos dos cambios correctamente.")],
        "steps": [
            _step("Mi lugar en una fila", "ubicaré posiciones del primero al quinto desde un inicio visible", "Forma una fila de cinco personajes y piensa en voz alta: el primero está junto a la flecha; el tercero tiene dos antes.", "Forman filas, reciben una posición y comprueban recorriendo desde el inicio.", "Señala el cuarto personaje y explica cómo lo encontraste."),
            _step("Del sexto al décimo", "usaré ordinales hasta el décimo sin confundir posición con cantidad", "Añade cinco tarjetas a la fila y contrasta: hay diez personajes, pero uno ocupa el séptimo lugar.", "Relacionan tarjetas 6.º a 10.º con posiciones y corrigen una fila rotulada con dos errores.", "Ubica octavo y décimo; luego indica cuántos elementos hay antes del octavo."),
            _step("Antes, después y entre", "describiré relaciones entre posiciones ordinales", "Con una fila de autos muestra que el quinto está después del cuarto y antes del sexto; cambiar el sentido cambia la referencia.", "Resuelven consignas: coloca el azul después del tercero y el rojo entre sexto y octavo.", "Si Ana es quinta, ¿qué posiciones están inmediatamente antes y después?"),
            _step("Problemas de orden", "resolveré problemas de posición y comprobaré con una representación", "Representa una carrera ficticia: Tomás llega tercero y queda antes de Sara; dibuja casilleros antes de ubicar nombres.", "Resuelven problemas con filas, turnos y secuencias de acciones, justificando con casilleros numerados.", "En una fila de diez, Leo está séptimo. Dibuja una ubicación posible y marca el inicio."),
        ],
    },
    "MA01 OA 03": {
        "topic": "Lectura y representación concreta, pictórica y simbólica de números del 0 al 20",
        "explanation": "Comprender un número supone coordinar cantidad, dibujo y numeral. La secuencia evita copiar cifras sin significado: cada representación se traduce a otra y se comprueba mediante conteo organizado.",
        "prerequisites": "Contar colecciones pequeñas con correspondencia uno a uno y reconocer que cero representa ausencia de elementos.",
        "vocabulary": "cantidad, numeral, representar, concreto, dibujo, símbolo, cero y comprobar",
        "units": ["Unidad 1: Números hasta 10", "Unidad 2: Números hasta 20"],
        "indicators": ["Representar cantidades concretas y escribir el numeral.", "Leer representaciones pictóricas hasta 20.", "Leer números entre 0 y 20."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17475.html",
        "materials": "Veinte fichas por pareja, tarjetas numéricas, marcos de diez, lápices y tarjetas con puntos organizados.",
        "support": "Usa marcos de diez y tarjetas de referencia; permite construir antes de dibujar y retira gradualmente el modelo.",
        "extension": "Representa el mismo número de dos maneras distintas y demuestra que ambas conservan la cantidad.",
        "criteria": ["hace corresponder cantidad y numeral", "traduce entre objeto, dibujo y símbolo", "comprueba mediante conteo o agrupación"],
        "difficulties": [("Invierte cifras como 12 y 21", "Construye doce en un marco de diez y dos sueltas antes de elegir la tarjeta.", "Selecciona y lee 12 entre tres numerales."), ("Dibuja sin conservar la cantidad", "Marca cada objeto concreto al producir un punto en el registro.", "El dibujo contiene exactamente la cantidad solicitada."), ("Confunde cero con uno", "Contrasta una bandeja vacía con otra que contiene una ficha.", "Representa 0 y 1 en tres formas.")],
        "steps": [
            _step("Cantidad y numeral del 0 al 10", "construiré una cantidad y escogeré el numeral que la representa", "Construye 7 fichas, cuéntalas una vez y vincula la tarjeta 7; contrasta con una tarjeta 6 incorrecta.", "Sacan una tarjeta, construyen la cantidad y la comprueban cambiando la disposición.", "Representa 8 con fichas y escribe o selecciona su numeral."),
            _step("Del objeto al dibujo", "dibujaré una cantidad sin perder ni agregar elementos", "Pasa 9 botones a nueve puntos, marcando cada botón al dibujar; explica por qué el tamaño del punto no cambia la cantidad.", "Traducen colecciones de 0 a 10 a puntos organizados y comparan registros.", "Dibuja una representación de 6 y escribe el numeral."),
            _step("Números del 11 al 20", "leeré y representaré números usando un grupo de diez y unidades sueltas", "Representa 14 como un marco completo y cuatro fichas; lee catorce y contrasta con 41 sin introducir valor posicional formal.", "Construyen y dibujan 11, 15, 18 y 20 usando marcos de diez.", "Representa 17 con un marco de diez y fichas sueltas; elige el numeral."),
            _step("Tres formas para el mismo número", "conectaré una colección, un dibujo y un numeral", "Empareja 13 fichas, un dibujo 10+3 y el numeral 13; muestra un emparejamiento erróneo y compruébalo.", "Resuelven estaciones de traducción entre las tres formas y justifican una correspondencia.", "Completa la forma que falta para 19 y explica cómo comprobaste."),
        ],
    },
    "MA01 OA 04": {
        "topic": "Comparación y orden de cantidades y números del 0 al 20",
        "explanation": "Comparar requiere establecer una correspondencia o usar una representación que haga visible la diferencia. La secuencia progresa desde emparejar objetos hasta ordenar numerales y justificar en problemas.",
        "prerequisites": "Representar números hasta 20 y contar colecciones sin omitir elementos.",
        "vocabulary": "más, menos, igual cantidad, mayor, menor, ordenar, ascendente y descendente",
        "units": ["Unidad 1: Comparación de cantidades", "Unidad 2: Orden hasta 20"],
        "indicators": ["Comparar cantidades mediante correspondencia uno a uno.", "Ordenar cantidades hasta 20 de mayor a menor y viceversa.", "Explicar con material concreto por qué una cantidad es mayor."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17476.html",
        "materials": "Fichas de dos colores, torres de cubos, tarjetas 0 a 20, recta numérica y sobres con problemas.",
        "support": "Alinea colecciones una a una y trabaja primero con diferencias visibles; después reduce la diferencia a una unidad.",
        "extension": "Encuentra todos los números posibles entre dos límites o crea un orden con una condición faltante.",
        "criteria": ["compara cantidades con una estrategia visible", "ordena respetando la dirección solicitada", "explica la diferencia con cantidad o posición"],
        "difficulties": [("Elige por tamaño de los objetos", "Usa fichas iguales y empareja una a una.", "Compara dos colecciones con disposiciones distintas."), ("Confunde mayor a menor con menor a mayor", "Coloca flecha y verbaliza inicio y dirección.", "Ordena cuatro números en ambas direcciones."), ("Responde por apariencia", "Reorganiza una colección sin cambiarla y vuelve a comparar.", "Mantiene la comparación tras cambiar la disposición.")],
        "steps": [
            _step("Emparejar para comparar", "compararé dos colecciones formando parejas", "Alinea 8 fichas rojas con 6 azules; las dos rojas sin pareja demuestran cuál tiene más.", "Comparan colecciones hasta 10, primero dispersas y luego emparejadas.", "Compara 7 y 9 fichas y dibuja la correspondencia."),
            _step("Mayor, menor e igual", "usaré lenguaje de comparación y explicaré la diferencia", "Construye torres de 12 y 15 cubos; iguala hasta 12 y muestra que sobran tres.", "Completan frases con mayor, menor o igual y justifican con torres o marcos.", "Compara 14 y 11 y explica cuántas unidades separan las cantidades."),
            _step("Ordenar varios números", "ordenaré números hasta 20 en forma ascendente y descendente", "Ubica 4, 9, 2 y 7 en una recta; recorre de izquierda a derecha y luego invierte la dirección.", "Ordenan grupos de cuatro o cinco tarjetas y verifican con material o recta.", "Ordena 16, 8, 13 y 19 de menor a mayor."),
            _step("Comparar para resolver", "resolveré un problema de comparación y defenderé mi respuesta", "Dos cajas tienen 13 y 17 lápices; representa ambas antes de decidir cuál alcanza para 15 estudiantes.", "Resuelven problemas familiares donde deben comparar u ordenar y explicar la representación elegida.", "Una bandeja tiene 18 vasos y otra 15. ¿Cuál tiene menos y cómo lo sabes?"),
        ],
    },
    "MA01 OA 05": {
        "topic": "Estimación de cantidades hasta 20 usando referentes",
        "explanation": "Estimar no es adivinar: es producir una cantidad razonable comparándola con un referente conocido y comprobar después. La secuencia trabaja referentes de 5 y 10, disposiciones variadas y justificación del rango estimado.",
        "prerequisites": "Reconocer visualmente colecciones pequeñas y contar hasta 20 para comprobar una estimación.",
        "vocabulary": "estimar, aproximadamente, cerca de, más que, menos que, referente y comprobar",
        "units": ["Unidad 2: Números, patrones numéricos y geométricos"],
        "indicators": ["Estimar cantidades hasta 20 en situaciones concretas.", "Usar una colección conocida como referente.", "Comprobar la estimación mediante conteo y comentar su cercanía."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17477.html",
        "materials": "Frascos transparentes, fichas, marcos de cinco y diez, tarjetas de estimación y paño para exposición breve.",
        "support": "Muestra el referente al lado de la colección y ofrece un rango entre dos opciones antes de pedir una cantidad exacta aproximada.",
        "extension": "Construye una colección que parezca mayor o menor sin cambiar la cantidad y explica por qué puede engañar la disposición.",
        "criteria": ["usa un referente identificable", "propone una cantidad razonable", "comprueba y comenta la diferencia sin borrar la estimación"],
        "difficulties": [("Adivina sin referente", "Coloca una colección conocida de diez junto al caso.", "Explica si el caso tiene más o menos que diez antes de estimar."), ("Cuenta antes de estimar", "Muestra la colección solo tres segundos y ocúltala.", "Registra una estimación previa al conteo."), ("Considera error toda diferencia", "Compara cuán cerca estuvo y define un rango razonable.", "Distingue estimación cercana de una muy lejana.")],
        "steps": [
            _step("Cinco como referente", "estimaré si una colección está cerca de cinco", "Muestra un marco completo de cinco y luego 7 fichas por tres segundos; explica que ves cinco y dos más.", "Estiman colecciones de 3 a 9 comparándolas con el marco de cinco y luego cuentan.", "Observa brevemente una colección y registra estimación, referente y total contado."),
            _step("Diez como referente", "usaré diez para estimar cantidades hasta 20", "Compara 16 fichas con un marco de diez: hay un diez completo y aproximadamente seis adicionales.", "Estiman colecciones de 8 a 20 con marco de diez visible y explican más/menos que diez.", "Estima una colección cercana a 15 y explica cómo usaste diez."),
            _step("La disposición puede engañar", "estimaré sin confundir espacio ocupado con cantidad", "Presenta 12 fichas juntas y las mismas 12 muy separadas; conserva la estimación al reconocer grupos.", "Comparan disposiciones ordenadas y dispersas, registran estimación y comprueban.", "Dos imágenes muestran la misma cantidad en distinta disposición: estima y justifica."),
            _step("Elegir y comprobar una estimación", "produciré una estimación razonable y analizaré la diferencia", "Ante 18 tapas, piensa: es casi dos grupos de diez, así que 17 o 18 es razonable; 7 no lo es.", "Resuelven estaciones, conservan estimación inicial, cuentan y calculan oralmente cuán cerca estuvieron.", "Estima un frasco de hasta 20 objetos, comprueba y completa: estuve a __ del total."),
        ],
    },
    "MA01 OA 06": {
        "topic": "Composición y descomposición aditiva de números del 0 al 20",
        "explanation": "Componer y descomponer permite entender que una cantidad puede formarse con partes distintas sin cambiar el total. La progresión conecta objetos, diagramas parte-parte-todo y expresiones aditivas.",
        "prerequisites": "Representar y leer números hasta 20 y reunir dos colecciones pequeñas.",
        "vocabulary": "parte, todo, componer, descomponer, sumar, separar y equivalencia",
        "units": ["Unidad 1 y 2: composición y descomposición de números"],
        "indicators": ["Componer números con sumandos en forma concreta.", "Descomponer números en forma pictórica.", "Registrar composiciones y descomposiciones simbólicamente."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17478.html",
        "materials": "Veinte fichas de dos colores, vasos o aros, marcos de diez, diagramas parte-parte-todo y tarjetas numéricas.",
        "support": "Mantén visible el total mientras separas las partes y usa colores distintos; pasa al dibujo y al símbolo solo cuando la acción tenga sentido.",
        "extension": "Encuentra todas las descomposiciones de un número y explica cómo sabes que no falta ninguna.",
        "criteria": ["conserva el total al separar o reunir", "representa las mismas partes en más de una forma", "explica la relación entre partes y todo"],
        "difficulties": [("Cambia el total al separar", "Cuenta el todo, separa sin agregar ni quitar y vuelve a reunir.", "Obtiene el mismo total antes y después."), ("Solo acepta una descomposición", "Mueve una ficha de una parte a otra manteniendo el todo.", "Produce tres pares distintos para el mismo número."), ("Copia la suma sin representarla", "Construye cada sumando con un color antes de leer la expresión.", "Relaciona correctamente objetos, dibujo y símbolo.")],
        "steps": [
            _step("Un todo formado por dos partes", "formaré un número reuniendo dos colecciones", "Reúne 4 fichas rojas y 3 azules; conserva los colores y muestra que el todo es 7.", "Componen totales hasta 10 con dos colores y registran cada parte.", "Construye 8 como dos partes y explica cuál es el todo."),
            _step("Separar sin cambiar el total", "descompondré un número en dos partes y comprobaré", "Coloca 9 fichas en dos aros: 5 y 4; vuelve a reunir para comprobar que siguen siendo 9.", "Descomponen 6, 8 y 10 de varias maneras y comparan pares.", "Muestra dos descomposiciones diferentes de 10."),
            _step("Del diagrama a la expresión", "conectaré partes concretas, dibujo y suma", "Dibuja un diagrama con partes 7 y 5, completa el todo 12 y escribe 7 + 5 = 12.", "Traducen diagramas parte-parte-todo a expresiones y viceversa.", "Completa un diagrama y una expresión para 13 como 10 y 3."),
            _step("Todas las maneras posibles", "buscaré descomposiciones sistemáticas hasta 20", "Para 6 registra 0+6, 1+5, 2+4 y 3+3; explica el cambio de una unidad entre partes.", "Construyen tablas ordenadas de descomposiciones y detectan repeticiones invertidas.", "Encuentra cuatro descomposiciones de 12 y explica el patrón."),
        ],
    },
    "MA01 OA 07": {
        "topic": "Estrategias de cálculo mental para adiciones y sustracciones hasta 20",
        "explanation": "El cálculo mental se construye con relaciones numéricas, no con velocidad. Se trabajan conteo hacia adelante y atrás, completar diez y dobles, comparando cuándo conviene cada estrategia.",
        "prerequisites": "Contar desde un número dado, componer diez y representar adiciones o sustracciones simples.",
        "vocabulary": "estrategia, contar desde, completar diez, doble, diferencia y comprobar",
        "units": ["Unidad 3 y 4: estrategias de cálculo mental"],
        "indicators": ["Contar mentalmente hacia adelante o atrás desde números dados.", "Calcular sumas completando diez.", "Usar dobles para sumar y restar en problemas."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17479.html",
        "materials": "Marcos de diez, fichas, tarjetas de operaciones, recta numérica opcional y tablero de estrategias.",
        "support": "Permite representar una vez la estrategia, verbalizarla y luego retirar el material; no uses tiempo de respuesta como criterio de logro.",
        "extension": "Resuelve el mismo cálculo con dos estrategias y decide cuál resulta más eficiente.",
        "criteria": ["elige una estrategia pertinente", "mantiene el significado de la operación", "explica y comprueba el resultado"],
        "difficulties": [("Cuenta todo desde uno", "Cubre el sumando mayor y cuenta solo lo que se agrega.", "Resuelve 8+3 comenzando en 8."), ("Completa diez, pero pierde el resto", "Separa el segundo sumando en lo que falta para diez y lo restante.", "Explica 8+5 como 8+2+3."), ("Confunde doble con sumar uno", "Construye dos grupos iguales y contrasta con grupos diferentes.", "Reconoce y usa dobles hasta 10+10.")],
        "steps": [
            _step("Contar desde el mayor", "sumaré contando hacia adelante desde un número", "Para 7+3 guarda 7 y cuenta 8, 9, 10; contrasta con volver a contar siete objetos.", "Practican sumas con un sumando pequeño, verbalizando punto de partida y saltos.", "Resuelve 9+4 y registra desde dónde comenzaste."),
            _step("Retroceder para restar", "restaré contando hacia atrás y comprobaré", "Para 13-4 ubica 13 y retrocede cuatro saltos: 12, 11, 10, 9.", "Resuelven restas con recta y luego sin verla, marcando cantidad de saltos.", "Calcula 16-3 y explica qué representa cada salto."),
            _step("Completar diez", "transformaré una suma para llegar primero a diez", "Descompone 5 en 2 y 3 para resolver 8+5 como 8+2+3.", "Construyen sumas 7+6, 8+4 y 9+5 con marcos de diez y registran la transformación.", "Resuelve 9+7 completando diez y muestra cómo separaste 7."),
            _step("Dobles y elección de estrategia", "usaré dobles y elegiré una estrategia eficiente", "Relaciona 6+6 con dos grupos iguales y usa ese doble para pensar 6+7 como 6+6+1.", "Clasifican operaciones según convenga contar, completar diez o usar un doble.", "Resuelve 8+8 y 8+9; nombra y justifica tu estrategia."),
        ],
    },
    "MA01 OA 08": {
        "topic": "Decenas y unidades en números del 0 al 20",
        "explanation": "El valor posicional comienza al reconocer diez unidades como una nueva unidad compuesta. Las clases conectan agrupación real, dibujo de decenas y unidades, numeral y lectura.",
        "prerequisites": "Contar y representar cantidades hasta 20 y formar grupos de diez sin perder elementos.",
        "vocabulary": "unidad, decena, agrupar, sobrante, cifra, diez y valor posicional",
        "units": ["Unidad 2: números, decenas y unidades"],
        "indicators": ["Agrupar cantidades en decenas.", "Registrar la cantidad de decenas y unidades restantes.", "Representar agrupaciones de diez concreta, pictórica y simbólicamente."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17480.html",
        "materials": "Palitos y elásticos, cubos encajables, marcos de diez, tarjetas 0 a 20 y tabla decenas-unidades.",
        "support": "Permite formar y desarmar el paquete de diez; usa una tabla con espacio físico diferenciado para decenas y unidades.",
        "extension": "Compara dos números con la misma decena o explica por qué dos representaciones distintas forman el mismo numeral.",
        "criteria": ["forma grupos exactos de diez", "distingue decenas de unidades sueltas", "relaciona agrupación, dibujo y numeral"],
        "difficulties": [("Cuenta el paquete como diez objetos y luego otra vez", "Encierra o amarra el grupo y decláralo una decena.", "Cuenta 14 como una decena y cuatro unidades."), ("Intercambia decenas y unidades", "Ubica cada tipo en su columna y reconstruye el número.", "Representa 17 y explica cada cifra."), ("Cree que una decena cambia de cantidad al compactarse", "Desarma y vuelve a armar el paquete contando sus unidades.", "Reconoce diez en distintas disposiciones.")],
        "steps": [
            _step("Formar una decena", "agruparé diez unidades y comprobaré el grupo", "Cuenta diez palitos, amárralos y contrasta con un paquete incorrecto de nueve.", "Forman paquetes de diez y verifican intercambiando con otra pareja.", "Construye una decena y explica cuántas unidades contiene."),
            _step("Una decena y unidades sueltas", "representaré números del 11 al 19 con decena y unidades", "Construye 14 como un paquete y cuatro palitos; registra 1 D y 4 U.", "Representan tarjetas numéricas con paquetes y completan tabla D/U.", "Representa 18 y escribe cuántas decenas y unidades tiene."),
            _step("Dibujar y leer decenas y unidades", "traduciré entre material, dibujo y numeral", "Dibuja una barra para la decena y seis puntos para unidades; vincula con 16.", "Traducen representaciones pictóricas a numerales y crean dibujos para otros números.", "Lee una decena y tres unidades, dibuja y escribe el número."),
            _step("El 20 y comparaciones", "representaré 20 como dos decenas y compararé números", "Agrupa veinte palitos en dos paquetes sin unidades sueltas; compara 20 con 19.", "Construyen 12, 17 y 20 y justifican el orden usando decenas y unidades.", "Explica por qué 20 tiene dos decenas y cero unidades sueltas."),
        ],
    },
    "MA01 OA 09": {
        "topic": "Comprensión de la adición y sustracción hasta 20 mediante problemas",
        "explanation": "Sumar y restar representan acciones y relaciones: agregar, reunir, quitar, separar y comparar. La progresión amplía el rango, conecta representaciones y culmina creando y resolviendo problemas coherentes.",
        "prerequisites": "Componer y descomponer cantidades, contar desde un número y comprender situaciones orales breves.",
        "vocabulary": "agregar, reunir, quitar, separar, diferencia, sumando, total, operación y problema",
        "units": ["Unidad 3: adición y sustracción", "Unidad 4: aplicación en problemas"],
        "indicators": ["Representar acciones de agregar y quitar concreta y pictóricamente.", "Usar símbolos para adiciones y sustracciones hasta 20.", "Resolver y crear problemas en contextos familiares."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17481.html",
        "materials": "Fichas, bandejas, tarjetas de acciones, marcos de diez, tiras de historias, dibujos y tarjetas de operaciones.",
        "support": "Representa la acción con objetos y una flecha antes del símbolo; reduce el rango numérico temporalmente sin cambiar el tipo de problema.",
        "extension": "Crea dos problemas distintos para la misma operación o encuentra una operación diferente que responda otra pregunta sobre el contexto.",
        "criteria": ["identifica la acción o relación del problema", "representa y calcula de forma coherente", "responde y comprueba en el contexto"],
        "difficulties": [("Elige operación por una palabra aislada", "Representa qué ocurre antes y después sin mirar símbolos.", "Explica la acción antes de calcular."), ("Calcula bien, pero no responde", "Vuelve a la pregunta y completa una frase con unidad.", "Entrega respuesta coherente con el contexto."), ("Crea un relato que no coincide con la operación", "Representa cada número y signo dentro del relato.", "Otro estudiante puede reconstruir la operación.")],
        "steps": [
            _step("Agregar y reunir hasta 5", "representaré situaciones de suma hasta cinco", "Cuenta 2 fichas en una bandeja y agrega 3; narra antes, acción y total, luego escribe 2+3=5.", "Representan relatos breves de agregar y reunir con objetos y dibujos.", "Dibuja y resuelve: había 3 aves y llegaron 2."),
            _step("Quitar y separar hasta 10", "representaré situaciones de resta hasta diez", "Parte con 8 fichas, quita 3 y registra 8-3=5; contrasta con agregar tres.", "Resuelven historias de quitar y separar, marcando cantidad inicial, cambio y resultado.", "Representa 9-4 con una historia y comprueba el resultado."),
            _step("Sumar hasta 20 con representaciones", "resolveré adiciones hasta veinte conectando objetos, dibujo y símbolo", "Resuelve 8+7 completando un marco de diez y dibuja la transformación.", "Resuelven problemas de reunir y agregar con dos sumandos hasta 20.", "Resuelve un problema para 9+6 y explica tu estrategia."),
            _step("Restar y comparar hasta 20", "resolveré sustracciones de quitar y comparar", "Compara torres de 15 y 11: iguala once y observa una diferencia de cuatro; registra 15-11=4.", "Distinguen problemas de quitar y comparar usando diagramas y expresiones.", "Hay 17 lápices y se usan 8. ¿Cuántos quedan? Representa y responde."),
            _step("Crear, resolver y revisar problemas", "crearé un problema coherente con una operación y revisaré su solución", "A partir de 12-5 inventa personajes, cantidad inicial, acción y pregunta; comprueba que todos los datos tienen función.", "Crean problemas para operaciones asignadas, los intercambian y revisan coherencia.", "Crea y resuelve un problema para 7+8; subraya dónde aparece cada número."),
        ],
    },
    "MA01 OA 10": {
        "topic": "Adición y sustracción como operaciones inversas",
        "explanation": "La relación inversa se comprende al transformar un mismo todo y sus partes: reunir puede deshacerse separando, y agregar puede deshacerse quitando. No se reduce a memorizar familias de operaciones.",
        "prerequisites": "Representar sumas y restas hasta 20 y reconocer partes y todo.",
        "vocabulary": "operación inversa, partes, todo, familia de operaciones, comprobar y deshacer",
        "units": ["Unidad 4: relación entre adición y sustracción"],
        "indicators": ["Modelar acciones inversas con material concreto.", "Relacionar adiciones y sustracciones pictóricamente.", "Completar familias de operaciones y usarlas para comprobar."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17482.html",
        "materials": "Fichas de dos colores, diagramas parte-parte-todo, tarjetas de operaciones y sobres con familias numéricas.",
        "support": "Mantén visible el mismo todo y las mismas dos partes; verbaliza qué acción se hace y cuál la deshace.",
        "extension": "Encuentra un dato desconocido usando la operación inversa y explica por qué funciona.",
        "criteria": ["conserva las mismas partes y el mismo todo", "relaciona correctamente suma y resta", "usa la inversa para comprobar o encontrar un dato"],
        "difficulties": [("Cambia los números entre operaciones", "Mantén las tres tarjetas de la familia visibles.", "Construye cuatro operaciones con los mismos tres números."), ("Resta una parte de otra sin considerar el todo", "Señala primero el todo en el diagrama.", "Forma restas que comienzan con el total."), ("Recita la familia sin comprender", "Representa una operación y ejecuta físicamente su inversa.", "Explica qué acción deshizo la primera.")],
        "steps": [
            _step("Hacer y deshacer una acción", "mostraré cómo agregar y quitar pueden deshacerse", "Parte con 5 fichas, agrega 3 para obtener 8 y quita las mismas 3 para volver a 5.", "Realizan pares de acciones inversas y registran el estado inicial y final.", "Representa una acción que lleve de 6 a 10 y otra que vuelva a 6."),
            _step("Partes, todo y cuatro operaciones", "construiré una familia de sumas y restas", "Con partes 4 y 7 y todo 11 forma 4+7=11, 7+4=11, 11-4=7 y 11-7=4.", "Construyen familias desde diagramas y detectan una operación intrusa.", "Completa las cuatro operaciones de la familia 5, 8 y 13."),
            _step("Comprobar con la inversa", "comprobaré una suma mediante resta y una resta mediante suma", "Comprueba 9+6=15 calculando 15-6 y explicando por qué debe volver a 9.", "Resuelven operaciones y eligen la inversa adecuada para verificar.", "Resuelve 14-8 y comprueba el resultado con una suma."),
            _step("Encontrar una parte desconocida", "usaré la operación inversa para encontrar un dato faltante", "En 7+__=12 identifica todo 12 y parte 7; calcula 12-7 para hallar la parte faltante.", "Resuelven diagramas y ecuaciones simples con una parte desconocida.", "Completa __+9=16 y demuestra con la operación inversa."),
        ],
    },
    "MA01 OA 11": {
        "topic": "Patrones repetitivos y patrones numéricos crecientes y decrecientes hasta 20",
        "explanation": "Un patrón posee una unidad que se repite o una regla que transforma cada término. La secuencia avanza desde movimiento y sonido hacia figuras y números, exigiendo describir la regla antes de continuar o crear.",
        "prerequisites": "Comparar elementos, copiar una secuencia breve y contar hasta 20.",
        "vocabulary": "patrón, unidad que se repite, regla, término, continuar, creciente y decreciente",
        "units": ["Unidad 1: patrones repetitivos", "Unidad 2: patrones numéricos y geométricos"],
        "indicators": ["Identificar y describir patrones de uno a tres elementos.", "Continuar patrones concretos, pictóricos y simbólicos.", "Crear patrones numéricos crecientes y decrecientes hasta 20."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17483.html",
        "materials": "Fichas de colores y formas, instrumentos u objetos sonoros, tarjetas numéricas, tiras de papel y cuadrícula.",
        "support": "Encierra la unidad mínima que se repite y deja solo dos repeticiones visibles; usa gesto o color para marcar el cambio.",
        "extension": "Crea dos patrones con los mismos elementos pero unidades o reglas diferentes y demuestra que no son iguales.",
        "criteria": ["identifica la unidad o regla", "continúa sin romper la regularidad", "describe o crea un patrón verificable"],
        "difficulties": [("Copia el último elemento", "Encierra la unidad completa y repítela como bloque.", "Continúa tres repeticiones correctas."), ("Describe colores, pero no la regla", "Pregunta qué bloque vuelve a comenzar.", "Nombra la unidad con orden correcto."), ("Cambia más de una cosa en un patrón numérico", "Compara diferencias entre términos consecutivos.", "Mantiene la misma variación cuatro veces.")],
        "steps": [
            _step("Patrones con cuerpo y sonido", "reconoceré una unidad repetitiva en movimientos y sonidos", "Realiza palma-palma-pie tres veces y encierra oralmente la unidad completa.", "Imitan, continúan y describen patrones de dos y tres acciones.", "Escucha golpe-suave-suave repetido y representa su unidad."),
            _step("Patrones con objetos y figuras", "continuaré patrones identificando la unidad que se repite", "Construye rojo-azul-azul y repite el bloque; contrasta con rojo-azul-rojo.", "Completan tiras con unidades ABB, ABC y AAB y justifican el elemento siguiente.", "Continúa círculo-cuadrado-cuadrado por seis términos."),
            _step("Patrones crecientes hasta 20", "describiré y continuaré una regla numérica creciente", "Analiza 3, 5, 7, 9: cada término aumenta dos; represéntalo con torres.", "Continúan secuencias +1, +2 y +5 y corrigen un término que rompe la regla.", "Completa 6, 8, __, __ y explica la regla."),
            _step("Patrones decrecientes", "continuaré reglas numéricas hacia atrás", "En 18, 15, 12 retira tres cubos cada vez y verbaliza menos tres.", "Construyen y registran patrones -1, -2 y -5 dentro del rango hasta 20.", "Completa 20, 15, 10, __, __ y comprueba."),
            _step("Crear y desafiar un patrón", "crearé un patrón y entregaré pistas suficientes para continuarlo", "Diseña un patrón ABC, oculta dos términos y explica la unidad sin revelar la respuesta.", "Crean patrones repetitivos o numéricos, los intercambian y revisan si la regla es única.", "Crea un patrón de seis términos, deja dos espacios y escribe o dicta la regla."),
        ],
    },
    "MA01 OA 12": {
        "topic": "Igualdad y desigualdad como equilibrio y desequilibrio hasta 20",
        "explanation": "El signo igual expresa que dos cantidades tienen el mismo valor, no una orden para calcular. La balanza y las colecciones permiten construir equilibrio, registrar igualdades en ambos sentidos y distinguir desigualdad.",
        "prerequisites": "Componer números hasta 20 y comparar dos cantidades mediante correspondencia.",
        "vocabulary": "igualdad, desigualdad, equilibrio, lado, mismo valor, diferente y signo igual",
        "units": ["Unidad 3: igualdades y desigualdades"],
        "indicators": ["Representar igualdad como equilibrio con una balanza.", "Registrar igualdades concreta, pictórica y simbólicamente.", "Determinar valores faltantes para conservar una igualdad."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17484.html",
        "materials": "Balanza escolar o balanza dibujada, cubos iguales, tarjetas numéricas, signos igual y no igual, diagramas.",
        "support": "Usa objetos idénticos en ambos lados y permite manipular antes de registrar; lee el signo igual como tiene el mismo valor que.",
        "extension": "Construye varias expresiones equivalentes para un mismo valor o encuentra un término desconocido en cualquier lado.",
        "criteria": ["compara el valor de ambos lados", "usa el signo igual entre expresiones equivalentes", "ajusta una cantidad para recuperar equilibrio"],
        "difficulties": [("Lee igual como viene la respuesta", "Lee expresiones en ambos sentidos usando tiene el mismo valor que.", "Acepta 8=5+3 y explica."), ("Compara cantidad de símbolos y no valor", "Construye cada expresión con cubos.", "Reconoce que 4+4 y 6+2 son iguales."), ("Agrega al lado equivocado", "Predice qué lado está más liviano antes de intervenir.", "Recupera equilibrio con una acción justificada.")],
        "steps": [
            _step("Equilibrio con cantidades", "construiré dos lados con la misma cantidad", "Coloca 6 cubos en cada plato y muestra equilibrio; retira uno y observa el desequilibrio.", "Predicen y comprueban pares de cantidades iguales o diferentes.", "Dibuja una balanza equilibrada con 7 elementos por lado."),
            _step("El signo igual", "registraré un equilibrio usando el signo igual", "Representa 5 y 5, escribe 5=5 y lee en ambos sentidos; luego muestra 3+2=5.", "Vinculan balanzas equilibradas con igualdades numéricas.", "Representa y explica 4+3=7."),
            _step("Expresiones equivalentes", "compararé dos expresiones para decidir si tienen el mismo valor", "Construye 6+2 en un lado y 5+3 en otro; ambos forman ocho.", "Evalúan pares de expresiones con material y corrigen igualdades falsas.", "Decide si 9+1=6+4 y justifica."),
            _step("Recuperar el equilibrio", "encontraré una cantidad faltante para completar una igualdad", "En 7+__=10 construye diez a un lado y siete al otro; agrega tres para equilibrar.", "Resuelven igualdades con una parte faltante mediante balanza o diagrama.", "Completa 8=5+__ y demuestra el equilibrio."),
        ],
    },
    "MA01 OA 13": {
        "topic": "Posición de objetos y personas usando lenguaje espacial",
        "explanation": "La ubicación depende de un referente y de la perspectiva. Las clases usan el cuerpo, objetos y planos simples para describir derecha, izquierda, delante, detrás, entre y al lado con precisión.",
        "prerequisites": "Seguir instrucciones corporales de un paso y reconocer objetos o personas usados como referencia.",
        "vocabulary": "derecha, izquierda, delante, detrás, arriba, abajo, entre, al lado, referente y perspectiva",
        "units": ["Unidad 4: posición y ubicación de objetos"],
        "indicators": ["Describir posiciones respecto del propio cuerpo.", "Ubicar objetos respecto de otros objetos o personas.", "Comunicar recorridos y posiciones usando lenguaje espacial."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17485.html",
        "materials": "Cintas para manos, objetos del aula, muñecos, cajas, flechas y cuadrícula o plano simple.",
        "support": "Marca temporalmente derecha e izquierda en el propio cuerpo y mantén fijo el referente; cambia la perspectiva solo después del dominio inicial.",
        "extension": "Describe la misma ubicación desde dos perspectivas y explica por qué puede cambiar derecha o izquierda.",
        "criteria": ["identifica el referente", "usa vocabulario espacial coherente", "ubica o describe de forma que otra persona pueda reproducir"],
        "difficulties": [("Responde sin nombrar referente", "Pregunta derecha de quién o de qué.", "Incluye referente en tres descripciones."), ("Confunde derecha e izquierda al girar", "Vuelve a la marca corporal y gira junto con ella.", "Sigue dos instrucciones desde distinta orientación."), ("Usa aquí o allá", "Ofrece dos términos espaciales y pide precisar.", "Otra persona reproduce la ubicación sin verla.")],
        "steps": [
            _step("Derecha e izquierda en mi cuerpo", "ubicaré objetos respecto de mi propio cuerpo", "Coloca una cinta en la mano derecha y demuestra que la cinta gira contigo.", "Siguen y dan instrucciones para levantar, tocar o mover objetos a derecha e izquierda.", "Dibuja un objeto a tu izquierda y explica el referente."),
            _step("Un objeto respecto de otro", "describiré posiciones usando un referente fijo", "Sitúa un cubo entre dos cajas y otro detrás de la caja azul; nombra referente y relación.", "Ubican muñecos según consignas y revisan descripciones ambiguas.", "Coloca y describe un objeto delante de otro y al lado de un tercero."),
            _step("Dar instrucciones precisas", "comunicaré una ubicación para que otra persona la reproduzca", "Describe sin señalar: pon el lápiz a la derecha del cuaderno y debajo de la tarjeta.", "En parejas crean y ejecutan consignas de dos relaciones espaciales.", "Escribe o dicta una instrucción que use entre y derecha."),
            _step("Posiciones en un plano simple", "representaré ubicaciones y recorridos en una cuadrícula", "Ubica la biblioteca arriba a la izquierda del plano y traza un recorrido desde la puerta.", "Interpretan planos de aula y describen lugares con referentes visibles.", "Marca un objeto en el plano y da dos pistas espaciales para encontrarlo."),
        ],
    },
    "MA01 OA 14": {
        "topic": "Figuras 2D y cuerpos 3D en el entorno y sus relaciones",
        "explanation": "Las figuras planas y los cuerpos se distinguen por sus atributos, no solo por su nombre. La secuencia explora caras, superficies, bordes, vértices, rodar, apilar y la relación entre cuerpos y figuras presentes en sus caras.",
        "prerequisites": "Observar y comparar objetos por forma y manipular materiales de manera segura.",
        "vocabulary": "figura 2D, cuerpo 3D, cara, superficie, borde, vértice, círculo, triángulo, cuadrado, rectángulo, cubo, esfera, cilindro y cono",
        "units": ["Unidad 2: figuras 2D y 3D"],
        "indicators": ["Identificar figuras 2D en el entorno.", "Identificar y describir cuerpos 3D mediante atributos.", "Relacionar caras de cuerpos con figuras 2D."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17486.html",
        "materials": "Objetos con forma de cubo, esfera, cilindro y cono, bloques geométricos, figuras recortadas, masa o tinta lavable para estampar.",
        "support": "Permite explorar táctilmente y clasificar por un atributo a la vez; usa objetos reales antes de fotografías o dibujos.",
        "extension": "Construye un cuerpo a partir de pistas sobre sus caras y comportamiento, o compara cuerpos que comparten una cara.",
        "criteria": ["distingue figura plana de cuerpo", "describe atributos observables", "relaciona una cara 2D con el cuerpo correspondiente"],
        "difficulties": [("Llama círculo a una esfera", "Contrasta una moneda plana y una pelota que ocupa espacio.", "Clasifica tres figuras y tres cuerpos."), ("Clasifica solo por color o tamaño", "Cambia color y tamaño manteniendo la forma.", "Conserva la clasificación por atributo geométrico."), ("No reconoce caras en distintas orientaciones", "Estampa o calca cada cara del cuerpo.", "Nombra la figura obtenida al girar el cuerpo.")],
        "steps": [
            _step("Figuras planas en el entorno", "identificaré figuras 2D por sus atributos", "Compara círculo, triángulo, cuadrado y rectángulo contando lados y vértices.", "Clasifican recortes y buscan ejemplos del entorno justificando por atributos.", "Dibuja una figura de cuatro lados iguales y nómbrala."),
            _step("Cuerpos que ruedan o se apilan", "identificaré cuerpos 3D y describiré sus superficies", "Prueba esfera, cubo, cilindro y cono en una rampa y sobre una mesa; relaciona superficie curva o plana con el comportamiento.", "Exploran estaciones de rodar, deslizar y apilar, registrando resultados.", "Elige un cuerpo que pueda rodar y apilarse; explica por qué."),
            _step("Las caras dejan figuras", "relacionaré cuerpos 3D con figuras 2D de sus caras", "Estampa una cara de cubo para obtener un cuadrado y una de cilindro para obtener un círculo.", "Emparejan cuerpos con huellas o caras y comprueban mediante estampado o calco.", "Dibuja dos figuras 2D que encuentres en las caras de cuerpos."),
            _step("Clasificar y construir con formas", "resolveré un desafío usando atributos de figuras y cuerpos", "Elige cuerpos para construir una torre estable y justifica por qué una esfera no sirve como base.", "Construyen objetos, identifican cada cuerpo y describen figuras visibles en sus caras.", "Clasifica cuatro objetos del entorno y justifica uno con dos atributos."),
        ],
    },
    "MA01 OA 15": {
        "topic": "Identificación y dibujo de líneas rectas y curvas",
        "explanation": "Las líneas se reconocen por su trayectoria, independientemente de su longitud, grosor u orientación. Se exploran con movimiento, objetos, dibujo y composiciones.",
        "prerequisites": "Seguir visualmente recorridos y realizar trazos libres con el medio de acceso disponible.",
        "vocabulary": "línea, recta, curva, trayectoria, segmento, abierta, cerrada y combinar",
        "units": ["Unidad 4: líneas rectas y curvas"],
        "indicators": ["Reconocer líneas rectas y curvas en el entorno.", "Dibujar líneas rectas y curvas en distintas orientaciones.", "Combinar líneas para representar objetos o recorridos."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17487.html",
        "materials": "Cuerdas, palitos, cintas, regla opcional, bandeja con arena o superficie táctil, papel y lápices.",
        "support": "Usa recorridos amplios con cuerpo o dedo y guías táctiles; evalúa la trayectoria, no la precisión motriz fina.",
        "extension": "Crea una imagen o recorrido con una restricción de cantidad y tipo de líneas y explica las elecciones.",
        "criteria": ["distingue trayectoria recta y curva", "produce ambos tipos en distintas orientaciones", "usa líneas intencionalmente en una representación"],
        "difficulties": [("Cree que vertical significa recta y horizontal curva", "Gira el mismo trazo sin cambiar su trayectoria.", "Clasifica líneas rectas inclinadas y curvas en varias posiciones."), ("Asocia recta con regla obligatoria", "Forma una recta con cuerda tensada y un trazo manual.", "Reconoce rectitud aunque cambie el instrumento."), ("La motricidad oculta el reconocimiento", "Permite elegir, señalar o construir con cuerda.", "Demuestra clasificación sin depender del dibujo fino.")],
        "steps": [
            _step("Recorridos rectos y curvos", "reconoceré líneas mediante trayectorias corporales", "Camina una cinta recta y una cuerda curva; describe si la dirección se mantiene o cambia.", "Clasifican recorridos de piso y los reproducen con el dedo o cuerpo.", "Señala un recorrido recto y uno curvo y explica la diferencia."),
            _step("Encontrar líneas en el entorno", "identificaré líneas rectas y curvas en objetos e imágenes", "Traza sobre el borde recto de una mesa y el borde curvo de un plato sin confundir el objeto completo con la línea.", "Buscan, fotografían mentalmente o dibujan ejemplos y justifican la clasificación.", "Dibuja un objeto y marca una línea recta y una curva."),
            _step("Dibujar en distintas orientaciones", "produciré líneas rectas y curvas sin depender de su posición", "Dibuja rectas horizontales, verticales e inclinadas; gira el papel y comprueba que siguen siendo rectas.", "Realizan series de trazos en arena, aire y papel, variando orientación y longitud.", "Dibuja tres rectas en orientaciones distintas y dos curvas."),
            _step("Componer con líneas", "combinaré líneas para representar y describir", "Construye un mapa simple con camino recto y curva, y verbaliza dónde cambia la trayectoria.", "Crean imágenes o recorridos con ambos tipos y los intercambian para clasificarlos.", "Crea una figura con al menos dos rectas y dos curvas; señálalas."),
        ],
    },
    "MA01 OA 16": {
        "topic": "Comparación de duraciones con unidades de tiempo no estandarizadas",
        "explanation": "Medir duración exige repetir una unidad temporal de manera regular. Palmas, pulsos o caídas de una pelota permiten comparar eventos si se mantiene la misma unidad y el mismo ritmo.",
        "prerequisites": "Reconocer inicio y final de una acción, contar eventos repetidos y seguir un pulso estable.",
        "vocabulary": "duración, tiempo, unidad, ritmo, más largo, más corto, inicio y final",
        "units": ["Unidad 1: unidades no estandarizadas de tiempo"],
        "indicators": ["Medir tareas con palmas, conteo u otras unidades no estandarizadas.", "Clasificar tareas según su duración medida.", "Comparar eventos usando la misma unidad temporal."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17488.html",
        "materials": "Tarjetas de tareas breves, pelota blanda, metrónomo visual opcional, tabla de registro y lápices.",
        "support": "Usa una señal clara de inicio y final y un ritmo corporal visible; asigna a otra persona el conteo si la ejecución motriz es la barrera.",
        "extension": "Compara resultados obtenidos con unidades o ritmos distintos y explica por qué no pueden compararse directamente.",
        "criteria": ["mantiene una unidad repetida y regular", "registra desde inicio hasta final", "compara duraciones usando resultados compatibles"],
        "difficulties": [("Acelera el conteo para terminar", "Separa quien realiza la tarea de quien mantiene el pulso.", "Repite con ritmo estable y obtiene medida semejante."), ("Compara medidas con unidades distintas", "Nombra y dibuja la unidad antes de medir.", "Vuelve a medir ambos eventos con la misma unidad."), ("Confunde esfuerzo con duración", "Registra pulsos en vez de opiniones.", "Justifica con la medida obtenida.")],
        "steps": [
            _step("Medir con un pulso", "mediré una duración repitiendo una unidad regular", "Mide guardar cinco fichas con palmas regulares desde la señal de inicio hasta el final.", "Miden tareas breves y comparan registros de pulsos.", "Mide una acción con palmas y registra unidad y resultado."),
            _step("La misma unidad para comparar", "compararé dos eventos usando la misma unidad", "Mide escribir el nombre y ordenar tres tarjetas con el mismo pulso; el mayor conteo indica mayor duración.", "Comparan pares de tareas manteniendo contador, ritmo y unidad.", "Decide qué evento duró más y usa los conteos como evidencia."),
            _step("Ordenar duraciones", "ordenaré tres eventos desde menor a mayor duración", "Registra 4, 7 y 10 pulsos para tres tareas y ordena sin depender de cuál pareció más difícil.", "Miden tres acciones y construyen una tabla de menor a mayor.", "Ordena eventos de 8, 3 y 6 pulsos y explica."),
            _step("Diseñar una medición justa", "planificaré y ejecutaré una comparación de duraciones", "Define eventos, unidad, ritmo, inicio y final antes de medir; identifica qué debe mantenerse.", "En equipos diseñan una comparación, la ejecutan dos veces y revisan variaciones.", "Explica dos condiciones necesarias para comparar duraciones justamente."),
        ],
    },
    "MA01 OA 17": {
        "topic": "Secuenciación temporal de rutinas, días, meses y fechas significativas",
        "explanation": "El tiempo calendario organiza ciclos y secuencias. Las clases conectan momentos del día, antes-durante-después, semana, meses y fechas significativas sin exigir memorizar listas sin contexto.",
        "prerequisites": "Relatar dos acciones en orden y reconocer rutinas cotidianas.",
        "vocabulary": "antes, durante, después, ayer, hoy, mañana, semana, mes, fecha y calendario",
        "units": ["Unidad 1: secuencias temporales y calendario"],
        "indicators": ["Ubicar actividades en momentos del día.", "Ordenar días de la semana y meses del año.", "Identificar fechas significativas en un calendario."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17489.html",
        "materials": "Tarjetas de rutinas ficticias, calendario anual y mensual, tarjetas de días y meses, flechas temporales.",
        "support": "Usa secuencias visuales y canciones solo como apoyo; pide ubicar y explicar en el calendario para demostrar comprensión.",
        "extension": "Calcula qué día o mes viene después de un cambio de semana o de año y explica el ciclo.",
        "criteria": ["ordena eventos con vocabulario temporal", "ubica días o meses en su ciclo", "interpreta una fecha dentro del calendario"],
        "difficulties": [("Recita sin ubicar", "Entrega una tarjeta y pide colocarla entre anterior y siguiente.", "Ubica tres días o meses dentro de la secuencia."), ("Confunde ayer y mañana", "Fija hoy y mueve una flecha un paso a cada lado.", "Responde dos casos desde un hoy dado."), ("Lee la fecha como números sueltos", "Señala día, mes y evento dentro de la cuadrícula.", "Ubica una fecha completa correctamente.")],
        "steps": [
            _step("Antes, durante y después", "ordenaré acciones de una rutina temporal", "Ordena preparar, realizar y guardar materiales; explica por qué guardar no puede ir primero.", "Secuencian rutinas ficticias de tres y cuatro acciones.", "Ordena tres imágenes y usa antes y después en la explicación."),
            _step("Los días forman una semana", "ubicaré días anteriores y posteriores dentro de la semana", "Fija miércoles como hoy, ubica martes y jueves y muestra el paso de domingo a lunes.", "Construyen una rueda semanal y resuelven casos de ayer, hoy y mañana.", "Si hoy es viernes, ¿qué día fue ayer y cuál será mañana?"),
            _step("Los meses forman un año", "ordenaré meses y reconoceré el ciclo anual", "Ubica marzo entre febrero y abril; muestra diciembre seguido de enero en un nuevo año.", "Arman una línea de meses, corrigen omisiones y ubican estaciones o hitos sin universalizar experiencias.", "Escribe o señala el mes anterior y posterior a septiembre."),
            _step("Leer fechas significativas", "ubicaré una fecha y explicaré qué informa", "En un calendario mensual localiza 18 de septiembre distinguiendo número de día, mes y significado nacional.", "Buscan fechas escolares, locales o nacionales previamente seleccionadas y comparan cuál ocurre antes.", "Ubica una fecha indicada y explica qué viene una semana después."),
        ],
    },
    "MA01 OA 18": {
        "topic": "Identificación y comparación de longitudes con lenguaje cotidiano",
        "explanation": "Comparar longitud exige alinear puntos de inicio o recorrer la misma trayectoria. Las clases distinguen largo de tamaño general y trabajan comparación directa e indirecta.",
        "prerequisites": "Manipular objetos y reconocer extremos o puntos de inicio.",
        "vocabulary": "longitud, largo, corto, más largo, más corto, igual longitud, extremo y alinear",
        "units": ["Unidad 3: expresar longitudes en palabras"],
        "indicators": ["Identificar objetos largos y cortos.", "Comparar longitudes alineando un extremo.", "Ordenar objetos según longitud y justificar."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17490.html",
        "materials": "Cintas, lápices, cuerdas, tiras de papel, objetos no desplazables y una tira intermediaria para comparar.",
        "support": "Marca una línea de inicio común y permite superponer objetos; usa alto contraste o exploración táctil cuando corresponda.",
        "extension": "Compara indirectamente dos objetos que no pueden moverse usando una tercera tira y explica la transitividad.",
        "criteria": ["compara la dimensión solicitada", "alinea o usa un intermediario correctamente", "justifica con lenguaje de longitud"],
        "difficulties": [("Compara desde extremos distintos", "Alinea ambos objetos en una línea base.", "Mantiene un inicio común en tres comparaciones."), ("Confunde largo con grueso o alto", "Señala la trayectoria exacta que se comparará.", "Compara la longitud aunque cambie el grosor."), ("Decide por impresión", "Superpone o usa una tira intermediaria.", "Sostiene la conclusión con evidencia directa.")],
        "steps": [
            _step("Largo y corto en un objeto", "identificaré la longitud que se quiere comparar", "Recorre con el dedo el largo de una cinta y contrasta con su ancho.", "Señalan longitudes en objetos y describen sin usar grande o pequeño.", "Marca el largo de un rectángulo y nombra un objeto corto."),
            _step("Comparar alineando", "compararé dos longitudes desde un extremo común", "Alinea dos lápices en la misma base; el extremo que sobresale muestra el más largo.", "Comparan pares con disposiciones engañosas antes y después de alinear.", "Compara dos tiras y dibuja la línea de inicio usada."),
            _step("Ordenar tres longitudes", "ordenaré objetos de más corto a más largo", "Alinea tres cintas, identifica extremos y registra el orden.", "Ordenan conjuntos y verifican comparando pares vecinos.", "Ordena cuatro trazos por longitud y explica una comparación."),
            _step("Comparar sin mover los objetos", "usaré un intermediario para comparar longitudes", "Marca en una cuerda el largo de una mesa y llévala a una repisa para compararlas.", "Resuelven comparaciones indirectas con tiras o cuerdas y registran marcas.", "Explica cómo compararías dos objetos fijos usando una tira."),
        ],
    },
    "MA01 OA 19": {
        "topic": "Recolección y registro de datos para responder preguntas estadísticas",
        "explanation": "Una investigación estadística comienza con una pregunta que admite variación, define categorías, recoge una respuesta por caso y registra sin perder datos. La lectura debe volver a la pregunta inicial.",
        "prerequisites": "Clasificar por una característica, contar colecciones y responder preguntas no sensibles.",
        "vocabulary": "dato, pregunta, categoría, encuesta, conteo, tabla, frecuencia y conclusión",
        "units": ["Unidad 3 y 4: datos, tablas de conteo y pictogramas"],
        "indicators": ["Formular o reconocer preguntas estadísticas sencillas.", "Recolectar datos del entorno con categorías claras.", "Registrar mediante bloques, marcas o tablas de conteo y responder la pregunta."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17491.html",
        "materials": "Tarjetas de opciones, bloques encajables, notas adhesivas, tablas de conteo, lápices y casos ficticios sin datos sensibles.",
        "support": "Limita inicialmente las categorías a dos o tres, usa una respuesta por persona y permite colocar un objeto antes de registrar una marca.",
        "extension": "Detecta cómo cambiaría la conclusión si se agrega una categoría o si faltan respuestas.",
        "criteria": ["recoge un dato pertinente por caso", "registra sin omitir ni duplicar", "responde la pregunta usando frecuencias"],
        "difficulties": [("Pregunta algo con una sola respuesta", "Contrasta una pregunta estadística con una factual.", "Reconoce cuál producirá datos variados."), ("Duplica u omite respuestas", "Entrega una ficha por participante y muévela al registrar.", "El total de marcas coincide con participantes."), ("Opina sin leer datos", "Señala las frecuencias que sostienen la afirmación.", "Responde citando categoría y cantidad.")],
        "steps": [
            _step("Preguntas que producen datos", "distinguiré una pregunta estadística de una pregunta con respuesta única", "Compara cuál es tu fruta preferida con cuántos días tiene una semana; solo la primera varía entre personas.", "Clasifican preguntas y mejoran una que no permite recolectar datos.", "Escribe o elige una pregunta que pueda tener respuestas diferentes."),
            _step("Recolectar una respuesta por caso", "recogeré datos usando categorías claras", "Cada personaje ficticio coloca una ficha en caminar, bicicleta o bus; revisa que nadie vote dos veces.", "Realizan una encuesta segura con opciones visibles y control de participantes.", "Registra cinco respuestas ficticias en tres categorías."),
            _step("De bloques a tabla de conteo", "transformaré datos concretos en marcas y frecuencias", "Una torre de cuatro votos se traduce a cuatro marcas y al número 4 sin moverla hasta comprobar.", "Convierten bloques o adhesivos en tablas y verifican totales.", "Completa una tabla desde tres torres y comprueba el total general."),
            _step("Responder con evidencia", "responderé la pregunta estadística usando los datos", "Lee una tabla: 6 prefieren A, 4 B y 2 C; concluye A es la categoría más frecuente y cita 6.", "Formulan comparaciones, diferencias y totales a partir de tablas propias.", "Escribe una conclusión verdadera y señala los datos que la apoyan."),
        ],
    },
    "MA01 OA 20": {
        "topic": "Construcción, lectura e interpretación de pictogramas",
        "explanation": "Un pictograma representa datos mediante símbolos organizados y una clave. En 1.º básico se prioriza inicialmente una imagen por dato, con alineación y categorías claras, antes de interpretar y construir.",
        "prerequisites": "Recolectar datos, contar hasta 20 y leer una tabla de frecuencias sencilla.",
        "vocabulary": "pictograma, símbolo, categoría, clave, frecuencia, más, menos, diferencia y total",
        "units": ["Unidad 3 y 4: datos y pictogramas"],
        "indicators": ["Leer información presentada en pictogramas.", "Interpretar y responder preguntas a partir de frecuencias.", "Construir pictogramas desde datos concretos o tablas."],
        "source": "https://www.curriculumnacional.cl/614/w3-article-17492.html",
        "materials": "Tablas de datos, pegatinas o tarjetas repetibles, cuadrículas, pictogramas correctos e incorrectos y lápices.",
        "support": "Usa una imagen por dato, filas alineadas y una clave visible; permite tocar o marcar cada símbolo al contar.",
        "extension": "Compara dos pictogramas de los mismos datos con distinta organización o explora una clave simple de dos unidades con apoyo.",
        "criteria": ["lee categorías y clave", "cuenta símbolos sin omitir ni duplicar", "construye e interpreta un pictograma coherente con los datos"],
        "difficulties": [("Cuenta el dibujo de la clave como dato", "Separa visualmente clave y zona de datos.", "Obtiene la frecuencia correcta en tres filas."), ("Compara por largo visual desalineado", "Alinea símbolos en una cuadrícula.", "Compara mediante conteo de símbolos."), ("Dibuja cantidades que no coinciden con la tabla", "Tacha una frecuencia al colocar cada símbolo.", "Todas las filas coinciden con la fuente.")],
        "steps": [
            _step("Leer categorías y símbolos", "leeré un pictograma con clave de una imagen por dato", "Señala título, categorías y clave antes de contar cuatro soles en una fila.", "Leen pictogramas breves y completan una tabla de frecuencias.", "Indica cuántos datos representa una fila y cómo lo sabes."),
            _step("Comparar y calcular diferencias", "interpretaré qué categoría tiene más, menos o cuántos de diferencia", "Compara 7 círculos con 5 cuadrados alineados y empareja para ver diferencia dos.", "Responden preguntas de máximo, mínimo, total y diferencia.", "Escribe una comparación verdadera entre dos categorías."),
            _step("Construir desde objetos", "crearé un pictograma desde datos concretos", "Transforma torres de 3, 5 y 2 bloques en filas de igual cantidad de símbolos, una imagen por bloque.", "Construyen pictogramas pegando tarjetas en cuadrícula y verifican con la colección.", "Representa datos 4, 1 y 6 en tres categorías con clave visible."),
            _step("Construir desde una tabla", "transformaré una tabla de conteo en un pictograma completo", "Lee frecuencias antes de dibujar; coloca título, categorías, clave y exactamente un símbolo por dato.", "Crean pictogramas desde tablas y realizan revisión cruzada fila por fila.", "Construye dos filas desde una tabla y comprueba cada frecuencia."),
            _step("Investigar, representar y comunicar", "integraré pregunta, datos, pictograma y conclusión", "Parte de una pregunta segura, recoge una respuesta por caso, registra, construye y concluye citando cantidades.", "En equipos realizan una miniinvestigación con datos ficticios o del curso no sensibles; cada estudiante produce una conclusión.", "Presenta un pictograma completo y responde una pregunta de comparación con evidencia."),
        ],
    },
}

# La URL canónica coincide con la ficha guardada en el snapshot verificable del proyecto.
for _code, _sequence in SEQUENCES.items():
    _oa_number = int(_code.rsplit(" ", 1)[-1])
    _sequence["source"] = f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/matematica/1-basico/ma01-oa-{_oa_number:02d}"


def build_math_sequence(code: str) -> dict | None:
    data = SEQUENCES.get(code)
    if not data:
        return None
    lessons = []
    for index, step in enumerate(data["steps"]):
        next_step = "Avanza a la clase siguiente si la evidencia cumple al menos dos criterios; en caso contrario, forma un grupo breve con material concreto y recoge una nueva evidencia." if index < len(data["steps"]) - 1 else "Integra este aprendizaje en el siguiente OA y conserva una comprobación individual; reenseña la representación que todavía no coincide con el razonamiento."
        lessons.append({
            "title": step["title"],
            "purpose": f"Construir comprensión de {data['topic'].lower()} mediante «{step['title'].lower()}», haciendo visible la estrategia y su comprobación.",
            "goal": "Hoy " + step["goal"] + ".",
            "opening": f"Antes de modelar, plantea esta situación sin resolver: {step['ticket']} Cada estudiante representa una primera idea con objetos, dibujo o gesto y explica qué cree que debe averiguar; registra dos estrategias para retomarlas al cierre.",
            "model": step["example"],
            "guided": step["practice"] + " El docente pregunta qué representa cada objeto, dibujo o número y corrige la idea, no solo el resultado.",
            "independent": step["ticket"] + " Después resuelve un segundo caso equivalente sin copiar la demostración.",
            "ticket": step["ticket"],
            "materials": data["materials"],
            "support": data["support"],
            "extension": data["extension"],
            "evidence": step["ticket"] + " junto con una explicación oral, gráfica o escrita atribuible al estudiante.",
            "criteria": data["criteria"],
            "next_step": next_step,
            "short_version": "Conserva el ejemplo específico, una práctica guiada, un caso individual y el ticket; reduce la cantidad de ejercicios, no la representación ni la explicación.",
            "home_task": "Crea en casa un ejemplo pequeño del aprendizaje con objetos seguros o un dibujo, explícalo a alguien y trae una comprobación. No requiere internet, impresión ni compras.",
            "complementary": ["Recuperación: vuelve al material concreto y resuelve un caso con menos elementos antes de regresar al rango del OA.", "Juego de errores: corrige una respuesta ficticia y explica exactamente dónde cambia el razonamiento.", "Profundización: modifica una condición del caso y predice el efecto antes de comprobar."],
            "difficulty_actions": [{"signal": signal, "action": action, "check": check} for signal, action, check in data["difficulties"]],
            "specialist_coordination": "El docente conduce la idea matemática y registra la estrategia usada; educación diferencial facilita representaciones, campo visual, manipulación o respuesta oral sin entregar el procedimiento ni reducir el OA.",
            "transversal": transversal_links(int(code.rsplit(" ", 1)[-1]), index, step["goal"]),
        })
    return {
        "topic": data["topic"], "pedagogical_explanation": data["explanation"],
        "prerequisites": data["prerequisites"], "vocabulary": data["vocabulary"],
        "official_alignment": {"units": data["units"], "indicators": data["indicators"], "source": data["source"]},
        "lessons": lessons,
    }
