"""Curated second-grade Orientation, Technology, English and Indigenous Language/Culture."""
from __future__ import annotations


def _steps(value: str) -> list[tuple[str, str, str]]:
    return [tuple(part.strip() for part in row.split("|", 2)) for row in value.split(";")]


ATTITUDES = {
    "TE": (
        ("de Actitud TE02 OAA A", "curiosidad por usos, funcionamiento y materiales tecnológicos"),
        ("de Actitud TE02 OAA B", "creatividad mediante experimentación y pensamiento divergente"),
        ("de Actitud TE02 OAA C", "iniciativa en diseño y creación tecnológica"),
        ("de Actitud TE02 OAA D", "colaboración y recepción de retroalimentación"),
        ("de Actitud TE02 OAA E", "uso seguro y responsable de internet y respeto de autoría"),
    ),
    "EN": (
        ("de Actitud EN02 OAA A", "interés por conocer el contexto y entorno propio"),
        ("de Actitud EN02 OAA B", "confianza progresiva para aprender un nuevo idioma"),
        ("de Actitud EN02 OAA C", "curiosidad y respeto ante realidades y culturas diversas"),
        ("de Actitud EN02 OAA D", "cooperación para alcanzar propósitos comunicativos"),
    ),
    "LC": (
        ("de Actitud LC02 OAA A", "pertenencia responsable a la red de la vida desde lengua y cultura"),
        ("de Actitud LC02 OAA B", "interculturalidad basada en aprecio y comprensión mutuos"),
        ("de Actitud LC02 OAA C", "relación integral y respetuosa con entornos naturales, sociales, culturales y espirituales"),
        ("de Actitud LC02 OAA D", "trabajo riguroso acorde con oralidad, territorio y enseñanza ancestral pertinente"),
    ),
}


OR = {
"OR02 OA 01": ("Características, habilidades e intereses personales", "Describir aspectos propios sin compararse ni revelar información íntima.", "característica, habilidad, interés, aprendizaje, valoración y diversidad", "Tarjetas de fortalezas observables, siluetas opcionales y casos ficticios.", "convertir una característica en etiqueta fija o valorar sólo habilidades académicas", _steps("Lo que me caracteriza|describiré rasgos e intereses que elijo compartir|Completa un retrato simbólico con gustos, formas de aprender y cualidades sin datos privados;Habilidades que se desarrollan|reconoceré algo que puedo hacer y cómo lo aprendí|Construye una línea de progreso con intento, ayuda, práctica y logro;Intereses que orientan elecciones|distinguiré interés propio de expectativa ajena|Analiza casos ficticios donde niñas y niños eligen actividades sin estereotipos;Valorar sin competir|expresaré aprecio por una característica propia y una ajena|Realiza una ronda de evidencias concretas evitando rankings y comparaciones")),
"OR02 OA 02": ("Reconocimiento y expresión segura de emociones", "Nombrar emociones básicas en situaciones ficticias.", "emoción, sensación, expresión, intensidad, contexto, regulación y apoyo", "Historias ficticias, termómetro emocional y tarjetas de estrategias.", "decidir cómo se siente otra persona sólo por su rostro o clasificar emociones como buenas/malas", _steps("Una emoción, muchas señales|identificaré emociones usando situación, palabras y gestos sin asegurar lo que otro siente|Compara tres reacciones posibles ante perder un turno;Formas distintas de expresar|distinguiré emoción de conducta|Analiza rabia con gritar, pedir pausa o apretar una pelota y separa sentir de dañar;Intensidad y cambio|reconoceré que una emoción puede aumentar, disminuir o mezclarse|Ubica casos ficticios en una escala y revisa después de nueva información;Pedir y ofrecer apoyo|elegiré una estrategia segura y una persona de confianza|Practica frases para pedir espacio, compañía o ayuda adulta sin exigir relatos personales")),
"OR02 OA 03": ("Expresiones de afecto y cuidado con consentimiento", "Reconocer gestos de cariño diversos y respetar límites corporales.", "afecto, cuidado, escucha, ayuda, consentimiento, límite y confianza", "Casos ficticios, tarjetas de acciones y red de apoyo institucional.", "suponer que el afecto exige contacto físico o forzar agradecimiento y reciprocidad", _steps("Muchas formas de cuidar|identificaré tiempo, escucha, palabras y ayuda como expresiones posibles|Clasifica gestos de afecto que no dependen de abrazar;Dar y recibir con límites|practicaré preguntar y aceptar un no|Ensaya ¿quieres un abrazo o prefieres otra cosa? en escenas ficticias;Ayuda que respeta autonomía|ofreceré apoyo sin hacer todo por otra persona|Compara ayudar, invadir y acompañar en una tarea escolar;Una red de cuidado|reconoceré adultos y espacios de apoyo sin exponer situaciones privadas|Completa una red institucional con roles, no secretos ni nombres obligatorios")),
"OR02 OA 04": ("Autocuidado, intimidad e información personal", "Distinguir rutinas cotidianas de cuidado y situaciones que requieren ayuda adulta.", "higiene, descanso, recreación, alimentación, intimidad, información personal y protección", "Casos ficticios, secuencias visuales y protocolo escolar vigente.", "responsabilizar al niño por condiciones familiares o enseñar secretos sobre seguridad corporal", _steps("Rutinas que cuidan|organizaré higiene, descanso, recreación y movimiento de forma flexible|Revisa un día ficticio buscando equilibrio sin controlar cuerpos ni alimentos;Alimentación sin culpa|reconoceré variedad, agua y apoyo adulto sin clasificar personas por lo que comen|Elige opciones posibles en casos con distinta disponibilidad;Mi cuerpo y mis límites|distinguiré contacto aceptado, incómodo o no permitido y practicaré decir no|Usa casos ficticios, ropa puesta y lenguaje claro, sin representaciones corporales;Información personal|decidiré qué datos no debo entregar y cuándo pedir ayuda|Clasifica nombre de pila, dirección, contraseña y foto según contexto y adulto responsable;Plan de protección|aplicaré parar, alejarme si puedo, decirlo y seguir contando|Ordena una respuesta ante solicitud incómoda presencial o digital sin prometer guardar secretos")),
"OR02 OA 05": ("Buen trato, solidaridad y respeto cotidiano", "Reconocer acciones observables que favorecen convivencia.", "buen trato, turno, pertenencia, solidaridad, respeto, colaboración y reparación", "Casos ficticios, materiales compartidos y acuerdos del curso.", "confundir respeto con silencio permanente o solidaridad con hacer la tarea de otro", _steps("Formas de buen trato|usaré saludo, petición y despedida según la situación|Compara tono y palabras en encuentros ficticios sin imponer una fórmula única;Escuchar y respetar turnos|mostraré escucha retomando una idea ajena|Practica responder a lo dicho antes de agregar una idea propia;Cuidar pertenencias y espacios|distinguiré préstamo, uso común y propiedad personal|Resuelve casos sobre útiles y materiales sin obligar a prestar objetos personales;Ayudar sin sustituir|ofreceré apoyo que permita participar|Transforma yo lo hago por ti en preguntas y apoyos graduados;Acuerdo de convivencia|aplicaré una acción durante una semana y revisaré su efecto|Define señal observable, recoge evidencia y ajusta sin premios conductuales")),
"OR02 OA 06": ("Resolución guiada de conflictos entre pares", "Distinguir conflicto, accidente y agresión y saber cuándo pedir ayuda.", "conflicto, perspectiva, escucha, acuerdo, reparación, mediación y seguridad", "Historias ficticias y guion visual; nunca se obliga a mediar agresiones reales.", "forzar reconciliación inmediata o tratar violencia y discriminación como desacuerdo entre iguales", _steps("¿Qué ocurrió?|separaré hechos, interpretaciones y emociones en un conflicto ficticio|Reconstruye dos versiones de un turno disputado sin decidir culpable por simpatía;Escuchar perspectivas|reformularé lo que cada persona necesita|Usa entendí que… y permite corrección;Buscar acuerdos|propondré opciones relacionadas con el problema y los derechos|Compara turnarse, compartir espacio y retirarse con seguridad;Reparar y seguir|distinguiré disculpa, reparación y cambio futuro|Elige una reparación coherente con material dañado o palabra hiriente, sin humillar")),
"OR02 OA 07": ("Pertenencia y participación en grupos", "Reconocer grupos significativos sin definir una familia única.", "pertenencia, familia, curso, pares, diversidad, participación y responsabilidad", "Casos ficticios, diagramas flexibles y tarjetas de tareas.", "suponer que todos los grupos son iguales o pedir información familiar privada", _steps("Grupos diversos|describiré qué hace que una persona pertenezca a un grupo|Compara familias y comunidades ficticias sin usar un modelo único;Personas y vínculos|reconoceré roles cambiantes y aportes sin estereotipos|Analiza quién cuida, aprende, juega y decide en ejemplos diversos;Participar de forma accesible|elegiré una tarea que contribuya al grupo|Diseña opciones para ordenar aula o proyecto sin asignarlas por género;Valorar pertenencia y autonomía|explicaré qué recibo y aporto conservando mis límites|Completa un diagrama opcional con casos reales o inventados")),
"OR02 OA 08": ("Hábitos y motivación para aprender", "Preparar materiales y reconocer aprendizajes sin asociarlos a obediencia.", "hábito, organización, material, meta, estrategia, progreso y motivación", "Agenda visual, cajas o sobres, casos ficticios y producciones previas.", "equiparar orden con aprendizaje o culpar al estudiante por recursos que no controla", _steps("Preparar lo necesario|identificaré materiales y alternativas antes de una tarea|Resuelve un caso sin lápiz o cuaderno usando apoyo institucional;Orden que ayuda|organizaré espacio y materiales según la actividad|Compara una mesa despejada para recortar con otra preparada para leer;Cuidar y devolver|aplicaré una rutina común sin exigir objetos propios|Etiqueta, usa y devuelve materiales compartidos;Reconocer aprendizaje|mostraré algo nuevo que comprendí y la evidencia|Completa antes pensaba/ahora puedo con una producción;Elegir el próximo paso|formularé una meta pequeña y una estrategia|Transforma mejorar en revisar mayúsculas en tres oraciones usando una pauta")),
}


TE = {
"TE02 OA 01": ("Diseño de objetos tecnológicos para necesidades cercanas", "Distinguir objeto, usuario y necesidad en situaciones conocidas.", "necesidad, usuario, criterio, restricción, boceto, modelo y decisión", "Papeles, lápices, cartón reutilizable limpio, bloques y fichas de usuario.", "dibujar un objeto atractivo antes de definir para quién sirve y qué debe lograr", _steps("Necesidad antes que objeto|formularé qué necesita una persona y en qué contexto|Analiza cómo transportar tres libros sin que caigan, antes de nombrar una solución;Más de una idea|produciré bocetos distintos para la misma necesidad|Dibuja tres contenedores cambiando cierre, asa o forma sin colorear detalles primero;Comunicar con un boceto|representaré forma, partes y uso mediante vistas y etiquetas|Agrega flechas y notas a un soporte para lápices que otra persona pueda entender;Modelo para pensar|construiré un modelo rápido y reconoceré qué permite comprobar|Usa papel o bloques para revisar tamaño y estabilidad, no terminación;Elegir con criterios|seleccionaré una propuesta justificando usuario, material y función|Compara bocetos con una matriz simple y conserva una mejora de la idea descartada")),
"TE02 OA 02": ("Organización de tareas, materiales y herramientas", "Seguir una secuencia simple y usar herramientas básicas con supervisión.", "tarea, secuencia, material, herramienta, acción, tiempo y seguridad", "Tarjetas de pasos, objetos de muestra, materiales y herramientas escolares revisadas.", "confundir material con herramienta o ordenar pasos sólo por cómo aparecen dibujados", _steps("Resultado y acciones|descompondré un objeto en tareas necesarias|Observa una caja plegada y deduce medir, marcar, cortar, plegar y unir;Material o herramienta|clasificaré qué se transforma y qué permite trabajar|Distingue cartón, pegamento, regla y tijera por función;Orden y dependencias|organizaré pasos explicando por qué uno va antes|Compara pintar antes/después de pegar y medir antes/después de cortar;Plan de trabajo|asignaré tareas y prepararé una alternativa ante falta de material|Crea una tabla acción-material-herramienta-seguridad-responsable")),
"TE02 OA 03": ("Elaboración segura de un objeto tecnológico", "Medir, plegar, unir y cortar materiales simples bajo indicaciones.", "medir, marcar, cortar, plegar, unir, acabado, estabilidad y seguridad", "Papeles, cartones, fibras, plásticos limpios, regla, tijeras escolares y adhesivos.", "seguir pasos mecánicamente sin comprobar función o elegir herramientas por rapidez", _steps("Probar técnicas antes de construir|compararé uniones, pliegues y cortes en retazos|Ensaya pestaña, encaje y pegado y registra cuál resiste una carga liviana;Seleccionar materiales|elegiré material por flexibilidad, resistencia y uso|Compara papel, cartón y plástico limpio para un separador de páginas;Construir con control|seguiré indicaciones verificando medidas y seguridad en cada etapa|Elabora un contenedor pequeño y detente en puntos de control;Terminar y documentar|explicaré cambios realizados durante la elaboración|Fotografía o dibuja proceso, marca un ajuste y limpia el espacio con roles")),
"TE02 OA 04": ("Prueba, explicación y mejora de soluciones tecnológicas", "Distinguir opinión de resultado de prueba.", "probar, criterio, resultado, evidencia, falla, retroalimentación e iteración", "Objetos propios o prototipos, pesos livianos, pauta de prueba y registro.", "evaluar sólo por apariencia o cambiar muchas variables sin saber qué produjo la mejora", _steps("Una prueba responde una pregunta|definiré criterio y procedimiento antes de probar|Para un puente de papel pregunta cuánto sostiene y acuerda carga y tiempo;Registrar sin ocultar fallas|describiré qué ocurrió con datos u observaciones|Anota se inclinó al tercer bloque en vez de no sirve;Explicar a otra persona|presentaré necesidad, decisión y resultado sin defenderme|Usa modelo, evidencia y límite en una explicación breve;Mejorar una variable|propondré un cambio relacionado con la falla y volveré a probar|Refuerza base o unión, no ambas, y compara resultados")),
"TE02 OA 05": ("Dibujo digital para representar ideas", "Usar mouse, panel táctil o alternativa accesible para seleccionar y trazar.", "lienzo, herramienta, trazo, forma, color, selección, deshacer y guardar", "Software de dibujo disponible sin cuenta, dispositivo compartido y alternativa en papel.", "explorar efectos al azar sin propósito o asumir que dibujo digital es copiar imágenes de internet", _steps("Herramientas básicas|usaré trazo, forma, relleno y deshacer con intención|Crea un símbolo usando sólo línea y forma, corrige con deshacer y no reiniciando;Capas visuales simples|ordenaré fondo, objetos y detalles aunque el programa no use capas|Construye un paisaje desde formas grandes a pequeñas;Representar un diseño|crearé una imagen que comunique partes y uso de un objeto|Dibuja un organizador con etiquetas o flechas legibles;Variantes rápidas|probaré color, tamaño o posición sin perder la versión inicial|Guarda o duplica dos opciones y explica cuál comunica mejor;Guardar y recuperar|nombraré, ubicaré y abriré un archivo siguiendo la organización acordada|Usa nombre no personal, carpeta indicada y comprueba reapertura")),
"TE02 OA 06": ("Creación, edición y guardado en procesador de textos", "Escribir palabras y oraciones simples con teclado o alternativa de entrada.", "documento, cursor, seleccionar, editar, formato, archivo, guardar y recuperar", "Procesador de texto local, dispositivo compartido y alternativa impresa sin cuentas personales.", "confundir formato llamativo con claridad o guardar sin comprobar nombre y ubicación", _steps("Crear y escribir|ingresaré título y dos oraciones usando espacios y saltos pertinentes|Redacta una ficha de animal sin usar datos personales;Mover y corregir|usaré cursor, borrar y selección para editar sin reescribir todo|Cambia una palabra repetida y mueve una oración a su lugar;Formato que ayuda|aplicaré tamaño, negrita o alineación sólo cuando mejora lectura|Compara tres títulos y decide cuál conserva legibilidad;Insertar una imagen propia|agregaré un dibujo o forma con pie breve si el software lo permite|Crea una señal y evita imágenes remotas sin autorización;Guardar, cerrar y recuperar|nombraré y localizaré el archivo de forma segura|Guarda en carpeta indicada, cierra y vuelve a abrir para comprobar")),
"TE02 OA 07": ("Búsqueda guiada y segura de información en internet", "Reconocer que internet contiene fuentes de distinta calidad y riesgos.", "internet, navegador, enlace, fuente, autor, fecha, dato, privacidad y autoría", "Sitios previamente seleccionados por docente, navegador protegido y ficha de registro.", "usar el primer resultado como verdad o copiar texto e imágenes sin reconocer autoría", _steps("Entrar por una ruta segura|seguiré enlaces entregados sin abrir anuncios ni ventanas desconocidas|Navega desde una lista docente y aplica parar, cerrar y avisar ante solicitud de datos o descarga;Leer la fuente|identificaré sitio, autor institucional y propósito básico|Compara una página oficial de museo con una publicación sin procedencia;Buscar dentro de una página|usaré palabra clave, título e imagen para hallar un dato|Encuentra hábitat de un animal en un recurso seleccionado sin leer todo;Extraer con palabras propias|registraré un dato breve y la dirección o título de origen|Completa una ficha sin copiar párrafos ni descargar imágenes")),
}


EN = {
"EN02 OA 01": ("Listening to short rhymes, songs, stories and dialogues", "Comprender saludos e instrucciones muy frecuentes con apoyo visual.", "rhyme, chant, song, story, dialogue, speaker, key word and sequence", "Audio o voz docente, imágenes, objetos y textos breves autorizados.", "traducir cada palabra antes de responder o fingir comprensión siguiendo al grupo", _steps("Rhyme and chant patterns|identificaré palabras que se repiten y responderé al ritmo|Listen to a short school chant and raise the matching picture when a key word returns;Song actions|seguiré una canción breve mediante gestos y palabras clave|Match stand, clap, turn and stop to actions without translating the whole song;Story characters|reconoceré personaje, objeto y acción en un cuento oral|Order three picture cards after listening twice;Mini-dialogues|identificaré quién habla y qué necesita|Choose the matching scene for Can I have the red pencil? Here you are;Listening showcase|demostraré comprensión con acción, dibujo o frase breve|Listen to a new short text and select evidence for type, speaker and main action")),
"EN02 OA 02": ("Listening for familiar topics and communicative functions", "Reconocer vocabulario básico de escuela, animales, casa y números.", "instruction, introduction, ability, feeling, possession, quantity, location and action", "Objetos, mapas simples, tarjetas e imágenes culturalmente diversas.", "responder sólo a sustantivos sueltos sin comprender la función de la frase", _steps("Instructions and introductions|seguiré y daré una instrucción y reconoceré una presentación|Act on Open your book and match This is Ana to the correct person;Abilities and feelings|distinguiré can/can't y happy, tired or worried in context|Listen and sort what a character can do and how they feel;Possession and quantities|identificaré have/has y números hasta veinte|Build the set described in Leo has fourteen blue shapes;Places and locations|ubicaré persona u objeto usando in, on, under, next to|Place classroom objects from oral clues;Actions now|reconoceré acciones con is/are plus verb-ing|Match people to pictures from They are cooking or She is walking")),
"EN02 OA 03": ("Evidence of oral comprehension and English sound contrasts", "Responder físicamente a palabras e instrucciones conocidas.", "character, object, action, instruction, frequent expression, /s/, /z/, /w/ and /th/", "Audio o voz docente, imágenes, espejo opcional y tarjetas; no se califica acento nativo.", "evaluar pronunciación como identidad o aislar sonidos sin mantener significado", _steps("People, animals and objects|identificaré referentes en un texto oral breve|Point to the correct wild animal, room or occupation after a clue;Follow the sequence|ejecutaré dos o tres instrucciones en orden|Take a triangle, put it under the chair, then sit down;Frequent expressions|reconoceré chunks completos en vez de palabras aisladas|Match I want…, Here!, This is… and Where is… to scenes;Sounds /s/ and /z/|distinguiré pares por contexto y vibración sin exigir perfección|Listen to sip/zip or bus/buzz in supported sentences and choose the picture;Sounds /w/ and /th/|notaré el contraste en palabras frecuentes y pediré repetición si hace falta|Sort wet/three/with/window using audio and visual cues")),
"EN02 OA 04": ("Listening strategies for meaning", "Usar imágenes y palabras conocidas antes y durante la escucha.", "predict, connect, image, key word, listen again and check", "Texto oral breve, imágenes, tarjetas de estrategia y organizador.", "adivinar desde la imagen y no revisar la predicción con lo escuchado", _steps("Predict with care|haré una predicción y la mantendré abierta|Use title and picture for a school story, then mark confirm or revise;Connect useful knowledge|activaré vocabulario que ayuda al tema|Before listening about a house, group room and furniture words;Images plus words|integraré pistas visuales y auditivas|Choose between similar scenes only after hearing the location phrase;Focus and check|escucharé palabras clave, pediré repetición y comprobaré|Complete a three-box listening plan for a new dialogue")),
"EN02 OA 05": ("Responding personally and creatively to listening", "Mostrar comprensión mediante dibujo, gesto o palabras conocidas.", "response, connection, preference, feeling, opinion, drawing and drama", "Audio breve, materiales visuales y opciones de respuesta sin exposición personal obligatoria.", "usar reacción creativa sin mostrar relación con el texto escuchado", _steps("Draw what mattered|dibujaré una escena e indicaré la pista oral|Listen to a room description and label two heard details;Act an action|representaré una acción o secuencia que escuché|Mime what the character is doing and let peers identify the phrase;Connect safely|relacionaré el texto con una experiencia real o ficticia|Choose I also… or My character… without sharing private information;Preference with a reason|expresaré I like/I don't like más una pista comprensible|React to two foods, games or story moments respectfully;Mixed response|combinaré dibujo, acción y frase para un texto nuevo|Create a response card and point to the words that connect it to the listening")),
"EN02 OA 06": ("Reading short English text types", "Reconocer palabras frecuentes y apoyarse en formato e imágenes.", "story, rhyme, chant, greeting card, instruction, information, character and action", "Textos breves autorizados, tarjetas de formato e imágenes.", "leer en voz alta sin construir significado o asumir el tema sólo por una imagen", _steps("What kind of text?|distinguiré cuento, rima, tarjeta, instrucción e información|Sort five short texts using layout and repeated language;General idea|elegiré la imagen o frase que resume el texto|Read a three-line animal card and reject an attractive but unsupported picture;Characters and actions|ubicaré quién hace qué|Match sentence strips to story characters;Known chunks|reconoceré las expresiones I want it y Here you are como unidades|Find and use the chunks in mini-dialogues;Read and show|demostraré comprensión de un texto nuevo con secuencia o dibujo|Read, order and explain three picture events using words from the text")),
"EN02 OA 07": ("Reading familiar topics and functions in English", "Leer palabras y frases sobre escuela, animales, casa y números.", "ability, feeling, possession, quantity, description, location, occupation and action", "Mini-books, maps, captions and information cards created or licensed for class.", "emparejar por una palabra llamativa y omitir negación, número o preposición", _steps("Instructions and introductions|seguiré texto breve para actuar o identificar personas|Read Draw a blue circle under the star and This is our cook;Ability, feeling and possession|distinguiré can/can't, feels and has|Match character profiles while attending to not;Animals and objects in place|describiré rasgos y ubicación desde una ficha|Read The small tiger is behind the tree and select the scene;Food, jobs and city places|buscaré información solicitada en menús o mapas simples|Answer What does the baker have? and Where is the clinic?;Actions happening now|identificaré who is doing what|Read captions with is/are -ing and correct one mismatched picture")),
"EN02 OA 08": ("Reading strategies with prediction, images and rereading", "Anticipar desde título e imagen y releer frases breves.", "predict, prior knowledge, picture clue, reread, read aloud, draw and retell", "Texto breve, imágenes separables y tarjetas de estrategias.", "mantener una predicción contradicha o releer igual sin cambiar el foco", _steps("Predict and revise|haré una predicción y la cambiaré con evidencia|Use a title and cover, then underline the line that confirms or changes the idea;Connect known words|buscaré palabras relacionadas que activan el tema|Build a small word web before a text about town;Picture and text together|decidiré qué información aporta cada modo|Cover the picture, then the words, and identify what each adds;Reread with a question|volveré a una parte específica para hallar un dato|Reread only the room paragraph to find the red chair;Retell with support|recontaré inicio, acción y cierre con imágenes y palabras del texto|Order three cards and use First, then, finally with help")),
"EN02 OA 09": ("Responding to English reading", "Elegir y comunicar una reacción comprensible a un texto breve.", "connection, preference, feeling, opinion, illustration, drama and evidence", "Textos breves, materiales de dibujo y tarjetas de expresión.", "responder en español o inglés sin mostrar qué parte del texto originó la reacción", _steps("Illustrate a detail|representaré un detalle y copiaré una frase breve que lo respalda|Draw the animal's hiding place and point to the location words;Drama from text|usaré voz o gesto para una acción escrita|Act a mini-dialogue while keeping the meaning of the line;Safe connection|conectaré con experiencia real o inventada|Complete I also… or My character… and show the related sentence;Preference and feeling|usaré las expresiones I like it e I feel happy because con apoyo|Choose a story moment and provide one textual clue;Response gallery|presentaré dibujo, frase o escena y reconoceré otra interpretación posible|Compare two responses to the same short text respectfully")),
"EN02 OA 10": ("English sounds through chants, rhymes and dialogues", "Repetir frases breves con ritmo y claridad suficiente para ser comprendido.", "chant, rhyme, dialogue, rhythm, stress, /w/, /th/, /s/ and /z/", "Modelos orales, espejo opcional, tarjetas e instrumentos suaves de pulso.", "exigir acento nativo o practicar sonidos en listas sin intención comunicativa", _steps("Listen and notice|identificaré un sonido meta dentro de una rima con sentido|Raise /w/ or /th/ cards while listening to a short weather rhyme;Shape and airflow|probaré /w/ y /th/ sin evaluar rasgos del habla|Use mirror or hand cue, then return immediately to meaningful words;Voice for /s/ and /z/|notaré vibración en pares apoyados por imagen|Contrast sip/zip and rice/rise in tiny contexts;Chant with rhythm|reproduciré una rima manteniendo pulso y palabras clave|Perform in group, pair or recorded privately;Mini-dialogue transfer|usaré los sonidos en un intercambio breve comprensible|Create and perform a two-line dialogue with one target word each")),
"EN02 OA 11": ("Participation in brief English interactions", "Responder a saludos, preguntas y consignas con palabras o frases conocidas.", "interaction, turn, support, gesture, image, clarification and presentation", "Objetos, apoyos visuales, tarjetas de diálogo y opción de ensayo privado.", "memorizar un diálogo sin escuchar al interlocutor o penalizar pausas y autocorrección", _steps("Classroom exchanges|responderé a instrucciones y peticiones frecuentes|Use Can I have…? Here you are and Thank you with real classroom objects;Introduce with support|presentaré a una persona o personaje usando tarjeta visual|Say This is…, He/She likes… without personal data;Ask for a word|usaré la pregunta How do you say this in English? para mantener interacción|Complete a task where one needed word is intentionally missing;Mini-presentation|compartiré dos datos apoyándome en objeto o imagen|Present an animal, place or shape for thirty seconds;Flexible dialogue|escucharé y adaptaré una respuesta en vez de recitar|Choose one of two follow-up questions based on what a peer says")),
"EN02 OA 12": ("Supported oral expression for familiar functions", "Producir palabras y frases breves con apoyo docente y visual.", "personal information, ability, quantity, description, prohibition, request, location and present action", "Tarjetas, mapas, objetos e imágenes; nunca se piden dirección, teléfono o datos sensibles.", "exigir frases largas antes de consolidar chunks comprensibles", _steps("Safe personal information|compartiré nombre de pila ficticio o preferencia no sensible|Use I'm…, I like… with option to speak as a character;Abilities and quantities|diré can/can't y contaré hasta veinte en una tarea|Describe what a character can do and how many objects they have;Describe and prohibit|identificaré animal, comida, trabajo o lugar y usaré Don't run como regla segura|Create a zoo or school sign with one spoken reason;Ask and locate|solicitaré comida u objeto y diré dónde está|Use Can I have…? and It's under/next to… in an information gap;Actions now|describiré una acción visible con is/are -ing|Report what figures in a busy picture are doing")),
"EN02 OA 13": ("Model-supported English writing", "Copiar palabras y completar frases breves manteniendo significado.", "copy, complete, model, word order, space, capital, period and check", "Modelos impresos o proyectados, banco de palabras y pauta clara.", "copiar letra por letra sin leer o completar sólo por longitud del espacio", _steps("Copy with meaning|copiaré una frase breve por unidades y la asociaré a una imagen|Copy The fox is fast, then select its picture;Complete from a word bank|elegiré una palabra por significado y orden|Finish The book is ___ the desk using in/on/under;Change the model|sustituiré un elemento y ajustaré la frase|Turn I have two red stars into a new true sentence;Write and check|produciré una oración apoyada y revisaré mayúscula, espacio y punto|Describe a classroom object for a peer to identify")),
"EN02 OA 14": ("Image-supported English writing for familiar meanings", "Escribir etiquetas y frases breves a partir de imágenes.", "label, sentence, animal, action, object, occupation, location, feeling and quantity", "Secuencias de imágenes, banco de palabras y organizadores de oración.", "enumerar palabras sin construir el significado solicitado o usar datos personales reales", _steps("Identify and label|escribiré nombres de animales, objetos, lugares y trabajos desde imágenes|Label a safe mixed scene and check spelling with the provided bank;Feelings and quantities|completaré frases con feels y números hasta veinte|Write The child feels… and There are… from clear pictures;Locations|describiré dónde está un objeto usando preposición|Write two true and one false location sentence for a peer;Actions now|usaré is/are plus -ing con un sujeto visible|Describe three people in a busy picture;Mini information card|integraré identidad ficticia, acción, cantidad y ubicación|Create a card about an imaginary animal or town scene and revise for meaning")),
}


LC_META = {
"LC02 OA LF01": ("Relatos orales en lengua indígena en contexto de fortalecimiento", 4, "escucha, relato, lengua, secuencia, memoria, fuente y comunidad", "comprender un relato desde una fuente comunitaria validada"),
"LC02 OA LF02": ("Descripción del medio natural en lengua indígena", 4, "lengua, descripción, medio natural, mensaje, oralidad, territorio y contexto", "describir un elemento o mensaje natural con expresiones validadas"),
"LC02 OA LF03": ("Interacción con textos escritos en lengua indígena", 5, "texto, lengua, tema, información, imagen, contexto y comprensión", "comprender aspectos de un texto pertinente al pueblo"),
"LC02 OA LF04": ("Escritura inicial en lengua indígena", 4, "palabra, frase, oración, escritura, sonido, significado y revisión", "experimentar con escritura validada sin inventar ortografía"),
"LC02 OA LF05": ("Uso de TIC para escuchar, ver y transcribir lengua indígena", 4, "recurso digital, audio, video, transcripción, fuente, permiso y lengua", "usar un recurso autorizado y transcribir con apoyo"),
"LC02 OA LR01": ("Relatos y palabras significativas en contexto de revitalización", 5, "relato, palabra, expresión, lengua, castellano, memoria y comunidad", "comprender un relato y reconocer expresiones culturalmente significativas"),
"LC02 OA LR02": ("Medio natural y mensajes de la naturaleza en revitalización", 5, "medio natural, mensaje, palabra, expresión, descripción, territorio y oralidad", "describir el entorno usando expresiones comunitariamente validadas"),
"LC02 OA LR03": ("Textos en castellano con expresiones en lengua indígena", 5, "texto, castellano, lengua indígena, contexto, significado, tema y fuente", "integrar expresiones sin separarlas de su contexto cultural"),
"LC02 OA LR04": ("Escritura de palabras y frases en revitalización", 4, "palabra, frase, lengua, grafía, significado, modelo y revisión", "escribir desde modelos validados y reconocer variantes"),
"LC02 OA LR05": ("TIC y transcripción en contexto de revitalización", 4, "audio, video, palabra, frase, transcripción, fuente y autorización", "escuchar y transcribir sin reemplazar a hablantes ni fuentes"),
"LC02 OA LS01": ("Relatos y palabras culturalmente significativas en sensibilización", 5, "relato, tradición, palabra, castellano, lengua indígena, respeto y fuente", "disfrutar un relato y reconocer palabras desde una fuente pertinente"),
"LC02 OA LS02": ("Descripción respetuosa del medio natural en sensibilización", 5, "medio natural, mensaje, palabra, territorio, observación, oralidad y respeto", "describir sin atribuir significados culturales no documentados"),
"LC02 OA LS03": ("Textos en castellano con palabras de culturas originarias", 5, "texto, palabra, cultura, contexto, significado, fuente y comprensión", "comprender palabras en contexto sin tratarlas como decoración"),
"LC02 OA LS04": ("Experimentación respetuosa con palabras culturalmente significativas", 4, "palabra, escritura, modelo, significado, contexto, variante y fuente", "escribir desde un modelo autorizado sin inventar lengua"),
"LC02 OA LS05": ("Recursos tecnológicos para conocer aspectos culturales", 4, "recurso, audio, video, cultura, autoría, permiso y contexto", "examinar recursos autorizados sin extraer prácticas de su contexto"),
"LC02 OA 10": ("Elementos espirituales, naturales y cósmicos en contexto comunitario", 5, "espiritualidad, naturaleza, cosmos, medicina ancestral, comunidad, respeto y fuente", "comprender relaciones desde voces pertinentes sin universalizarlas"),
"LC02 OA 11": ("Naturaleza y actividades productivas desde perspectivas indígenas", 4, "naturaleza, actividad productiva, ciclo, conocimiento, reciprocidad, territorio y fuente", "relacionar conocimiento territorial, ciclos y producción"),
"LC02 OA 12": ("Eventos socioculturales y ceremoniales pertinentes", 4, "evento, ceremonia, convención, momento, espacio, participación y resguardo", "conocer sin reproducir prácticas restringidas ni simular ceremonias"),
"LC02 OA 13": ("Valores sociocomunitarios en convivencia", 4, "reciprocidad, respeto, ayuda mutua, palabra, convivencia, comunidad y práctica", "examinar valores mediante acciones contextualizadas"),
"LC02 OA 14": ("Técnicas y producción vinculadas a valores culturales", 4, "técnica, producción, material, proceso, reciprocidad, respeto y autorización", "experimentar sólo con una técnica compartida para enseñanza"),
"LC02 OA 15": ("Patrimonio cultural de comunidad, territorio y pueblo", 4, "patrimonio, comunidad, territorio, manifestación, sitio, cuidado y autoridad cultural", "reconocer patrimonio y sus condiciones de acceso"),
"LC02 OA 16": ("Relación entre ser humano, naturaleza y cosmos", 4, "ser humano, naturaleza, cosmos, conocimiento, observación, relación y perspectiva", "comprender una relación desde perspectiva indígena documentada"),
"LC02 OA 17": ("Expresiones de arte indígena con pertinencia y resguardo", 4, "arte, expresión, significado, convención, momento, espacio, autoría y permiso", "crear sólo desde prácticas autorizadas y sin copiar símbolos restringidos"),
"LC02 OA 06": ("Espacios significativos y visión de mundo", 4, "territorio, espacio significativo, memoria, uso, nombre, cuidado y comunidad", "reconocer un espacio desde fuentes comunitarias sin divulgar sitios sensibles"),
"LC02 OA 07": ("Historia local: pasado y presente del pueblo", 4, "historia, memoria, pasado, presente, testimonio, fuente y comunidad", "reconstruir aspectos históricos sin presentar una voz como totalidad"),
"LC02 OA 08": ("Valoración cultural e identidad", 4, "cultura, identidad, pertenencia, diversidad, valoración, cambio y continuidad", "valorar sin exigir identidad ni hablar en nombre de otras personas"),
"LC02 OA 09": ("Territorio, lengua e historia en la identidad", 4, "territorio, lengua, historia, identidad, persona, pueblo y relación", "explicar relaciones sin reducir identidad a una lista de rasgos"),
}


def _lc_steps(code: str, count: int, target: str) -> list[tuple[str, str, str]]:
    if code.startswith("LC02 OA LF"):
        sequence = [("Escuchar o observar la fuente", "reconoceré voces, propósito y contexto de una fuente validada", target), ("Comprender con apoyo", "identificaré información, secuencia o significado sin traducir mecánicamente", target), ("Usar con pertinencia", "emplearé el aprendizaje respetando pronunciación, grafía y contexto", target), ("Comunicar y devolver", "compartiré una comprensión citando la fuente y sus límites", target), ("Profundizar en contexto", "compararé dos ejemplos autorizados sin declarar una variante superior", target)]
    elif code.startswith("LC02 OA LR"):
        sequence = [("Activar memoria lingüística", "reconoceré palabras o expresiones disponibles sin evaluar identidad", target), ("Escuchar la fuente comunitaria", "atenderé significado, pronunciación y contexto desde una fuente validada", target), ("Relacionar lengua y experiencia", "usaré una expresión en una situación pertinente y segura", target), ("Registrar sin fijar una única variante", "escribiré o representaré reconociendo variantes comunitarias", target), ("Aportar a la revitalización", "crearé un recurso pequeño que reconoce autoría y no reemplaza a hablantes", target)]
    elif code.startswith("LC02 OA LS"):
        sequence = [("Acercarse con respeto", "observaré o escucharé sin imitar ni apropiarme", target), ("Reconocer contexto y fuente", "identificaré pueblo, territorio y procedencia del recurso", target), ("Comprender una relación", "explicaré un significado documentado sin generalizar", target), ("Responder sin apropiarse", "comunicaré lo aprendido citando la fuente y evitando símbolos restringidos", target), ("Revisar una representación", "detectaré estereotipos o información sin respaldo y los corregiré", target)]
    else:
        sequence = [("Fuente, territorio y voces", "ubicaré el aprendizaje en un pueblo, territorio y fuente pertinente", target), ("Relaciones y significados", "explicaré una relación cultural sin aislarla de su contexto", target), ("Continuidad y presente", "reconoceré que el conocimiento vive, cambia y tiene portadores actuales", target), ("Cuidado y reciprocidad", "propondré una acción respetuosa coherente con los resguardos aprendidos", target), ("Comunicación situada", "presentaré una comprensión, sus fuentes y lo que no puedo afirmar", target)]
    return sequence[:count]


def _attitude(code: str, lesson_index: int, goal: str) -> list[dict[str, str]]:
    prefix = code[:2]
    pool = ATTITUDES.get(prefix, ())
    if not pool:
        return []
    number_token = code.rsplit(" ", 1)[-1]
    number = sum(ord(ch) for ch in number_token)
    attitude_code, text = pool[(number + lesson_index) % len(pool)]
    return [{"code": attitude_code, "type": "Actitud", "application": f"Se promueve {text} durante «{goal}» mediante una acción observable; no se evalúa personalidad, origen, identidad ni obediencia."}]


def _lesson(code: str, index: int, stage: tuple[str, str, str], profile: tuple, discipline: str) -> dict:
    title, goal, challenge = stage
    topic, _, _, materials, misconception, _ = profile
    if discipline == "orientation":
        opening = f"Presenta un caso ficticio y seguro relacionado con «{title.lower()}»: {challenge} Nadie debe revelar experiencias personales para participar."
        model = f"Distingue hechos, emociones, límites, opciones y apoyo adulto en el caso: {challenge} Modela lenguaje respetuoso sin diagnosticar ni prometer secreto."
        guided = f"En parejas eligen entre respuestas posibles para «{title.lower()}», anticipan consecuencias y practican una frase de cuidado, límite, acuerdo o ayuda."
        evidence = f"Decisión individual ante un caso ficticio de «{title.lower()}», con razón, límite y persona o recurso de apoyo cuando corresponda."
        support = "Ofrece personajes ficticios, opciones visuales y derecho a pasar o responder por escrito; deriva situaciones reales al protocolo institucional, no a la discusión pública."
        extension = "Agrega una perspectiva o límite y pide revisar la decisión conservando seguridad, dignidad y posibilidad de ayuda."
        coordination = "El docente conduce prevención y convivencia; orientación o convivencia escolar recibe situaciones reales según protocolo, sin investigar ni exponerlas durante la clase."
    elif discipline == "technology":
        opening = f"Presenta una necesidad, artefacto o interfaz sin resolver: {challenge} Cada estudiante registra qué debería lograr y una restricción."
        model = f"Piensa en voz alta como diseñador: {challenge} Separa necesidad, usuario, decisión, prueba y seguridad; conserva un intento fallido útil."
        guided = f"En parejas desarrollan una variante de «{title.lower()}», registran acción y resultado y comparan dos soluciones mediante criterios, no por apariencia."
        evidence = f"Diseño, objeto, archivo o registro individual de «{title.lower()}» con propósito, decisión, prueba y mejora explicados."
        support = "Ofrece materiales precortados, plantillas de organización, dispositivo compartido o alternativa desconectada equivalente; no realiza la decisión del estudiante."
        extension = "Cambia usuario, material, dato o restricción y solicita adaptar el diseño o procedimiento y volver a probar."
        coordination = "El docente conduce diseño, seguridad física y digital; educación diferencial acuerda acceso a herramientas o interfaz sin ejecutar la solución."
    elif discipline == "english":
        opening = f"Presenta el input una vez con gesto, objeto o imagen y sin traducir completo: {challenge} Cada estudiante responde con acción, elección o marca."
        model = f"Think aloud briefly in accessible English and Spanish only when needed: {challenge} Point to the sound, word, image or pattern that carries meaning."
        guided = f"Practican «{title.lower()}» por eco, information gap, clasificación o turnos breves; cambian al menos un dato para evitar recitación mecánica."
        evidence = f"Respuesta oral, escrita, gráfica o corporal comprensible para «{title.lower()}», vinculada con una palabra, chunk o pista del input."
        support = "Mantén imágenes y banco de palabras visibles, permite ensayo coral y en pareja, reduce extensión y ofrece tiempo de espera; no penaliza acento ni mezcla lingüística inicial."
        extension = "Cambia personaje, cantidad, lugar o acción y pide adaptar el mensaje para una nueva intención comunicativa."
        coordination = "El docente modela inglés comprensible; educación diferencial facilita acceso auditivo, visual, motor o de respuesta sin sustituir la intención comunicativa."
    else:
        opening = f"Para «{title.lower()}», ubica pueblo, territorio, fuente y autorización antes de presentar el recurso: {challenge} Declara qué se puede compartir y qué requiere resguardo."
        model = f"Modela «{title.lower()}» sólo con una fuente comunitaria pertinente o material oficial validado: {challenge} No inventa lengua, pronunciación, grafías, símbolos ni explicaciones espirituales."
        guided = f"Con educador tradicional o fuente comunitaria cuando corresponda, analizan «{title.lower()}», reconocen variantes y distinguen aprender de reproducir o apropiarse."
        evidence = f"Comprensión o producción situada sobre «{title.lower()}» que identifica fuente, pueblo o territorio y respeta límites de uso, autoría y acceso."
        support = "Permite escuchar sin repetir, responder en castellano o mediante imagen y usar modelos validados; nunca usa desconocimiento lingüístico para evaluar identidad o pertenencia."
        extension = "Compara dos fuentes autorizadas o variantes sin jerarquizarlas y explica qué contexto hace pertinente cada una."
        coordination = "El docente no suplanta saberes comunitarios; coordina con educador tradicional, autoridad cultural o fuente comunitaria pertinente y detiene la actividad si falta validación."
    return {
        "title": title,
        "purpose": f"Desarrollar {topic.lower()} mediante «{title.lower()}», con una experiencia específica, segura y revisable.",
        "goal": f"Hoy {goal}.",
        "opening": opening,
        "model": model,
        "guided": guided,
        "independent": f"Resuelve una versión nueva de «{title.lower()}» sin copiar el modelo; toma una decisión, produce evidencia propia y revisa con el criterio trabajado.",
        "ticket": f"En «{title.lower()}»: {challenge} Señala la evidencia o decisión que sostiene tu respuesta.",
        "materials": materials,
        "support": support,
        "extension": extension,
        "evidence": evidence,
        "criteria": ["responde al foco específico de la clase", "toma una decisión pertinente y segura", "explica o localiza evidencia y reconoce límites"],
        "next_step": "Avanza cuando decisión, evidencia y explicación coinciden; si no, cambia acceso o ejemplo y vuelve a recoger evidencia sin etiquetar al estudiante.",
        "short_version": "Conserva situación específica, modelado, práctica guiada, evidencia individual y cierre; reduce cantidad, no propósito ni resguardos.",
        "home_task": "Observa, practica o registra una versión breve y segura con recursos disponibles. No requiere compras, internet, datos personales ni exposición familiar o cultural.",
        "complementary": ["Recuperación: reduce elementos y conserva la misma decisión central.", f"Análisis de error: revisa un caso ficticio con esta confusión: {misconception}.", "Transferencia: cambia contexto o condición y revisa qué debe adaptarse."],
        "difficulty_actions": [
            {"signal": "Repite una respuesta sin comprenderla", "action": "Pide elegir, señalar o aplicar en un caso nuevo antes de explicar.", "check": "La evidencia cambia coherentemente con el nuevo caso."},
            {"signal": misconception.capitalize(), "action": support, "check": "Resuelve un caso nuevo sin repetir la confusión."},
            {"signal": "La tarea exige exposición o recurso no disponible", "action": "Activa caso ficticio, alternativa desconectada o vía de respuesta equivalente.", "check": "Participa sin revelar información ni reducir el OA."},
        ],
        "specialist_coordination": coordination,
        "transversal": _attitude(code, index, goal),
    }


def _build(code: str, table: dict, discipline: str, axis: str) -> dict | None:
    profile = table.get(code)
    if not profile:
        return None
    topic, prior, vocabulary, _, misconception, stages = profile
    stages=[(f"{title} · {topic}",goal,challenge) for title,goal,challenge in stages]
    profile=(*profile[:5],stages)
    slug = {"orientation": "orientacion", "technology": "tecnologia", "english": "ingles-propuesta"}[discipline]
    return {
        "topic": topic,
        "pedagogical_explanation": f"{topic} se desarrolla mediante desempeños propios de la asignatura. La secuencia parte de {prior[0].lower() + prior[1:]} y enfrenta la confusión «{misconception}».",
        "prerequisites": prior,
        "vocabulary": vocabulary,
        "official_alignment": {"units": [f"Eje {axis} · organización interna en {len(stages)} clases"], "unit_origin": "Organización interna derivada del eje y del OA; no se presenta como unidad oficial del programa de estudio.", "indicators": [f"{goal[0].upper() + goal[1:]}." for _, goal, _ in stages[:3]], "indicator_origin": "Criterios de progresión internos derivados del verbo, contenido y alcance del OA oficial", "source": f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/{slug}/2-basico/{code.lower().replace(' ', '-')}"},
        "lessons": [_lesson(code, i, stage, profile, discipline) for i, stage in enumerate(stages)],
    }


def _build_lc(code: str) -> dict | None:
    meta = LC_META.get(code)
    if not meta:
        return None
    topic, count, vocabulary, target = meta
    stages = [(f"{title} · {topic}", goal, challenge) for title, goal, challenge in _lc_steps(code, count, target)]
    profile = (topic, "Acceder a una fuente pertinente con mediación respetuosa, sin exigir conocimiento lingüístico previo ni pertenencia cultural.", vocabulary, "Fuente comunitaria u oficial validada, recurso oral o visual autorizado y materiales definidos con educador tradicional cuando corresponda.", "generalizar entre pueblos, inventar lengua o reproducir prácticas y símbolos sin autorización", stages)
    return {
        "topic": topic,
        "pedagogical_explanation": f"{topic} exige situar cada aprendizaje en el pueblo, territorio, contexto lingüístico y fuente correspondiente. No se inventa lengua ni se sustituye la voz comunitaria; la secuencia trabaja para {target}.",
        "prerequisites": profile[1],
        "vocabulary": vocabulary,
        "official_alignment": {"units": [f"Contexto curricular y eje oficial · organización interna en {count} clases"], "unit_origin": "Organización interna derivada del contexto, eje y OA; no se presenta como unidad oficial adicional.", "indicators": [f"{goal[0].upper() + goal[1:]}." for _, goal, _ in stages[:3]], "indicator_origin": "Criterios internos que requieren fuente comunitaria, pertinencia territorial y no apropiación", "source": f"https://www.curriculumnacional.cl/curriculum/1o-6o-basico/lengua-cultura-pueblos-originarios-ancestrales/2-basico/{code.lower().replace(' ', '-')}"},
        "lessons": [_lesson(code, i, stage, profile, "indigenous") for i, stage in enumerate(stages)],
    }


def build_sequence(code: str) -> dict | None:
    if code in OR:
        return _build(code, OR, "orientation", "Crecimiento, relaciones, pertenencia y trabajo escolar")
    if code in TE:
        return _build(code, TE, "technology", "Diseñar, hacer, probar y TIC")
    if code in EN:
        return _build(code, EN, "english", "Comprensión y expresión oral y escrita")
    return _build_lc(code)


def build_transversal_integration(item: dict) -> dict:
    code = item["oa_code"]
    text = item["oa_text"].split("Unidad de Currículum", 1)[0].strip().rstrip(".")
    if "TE02" in code:
        context = "una tarea real de diseño, elaboración, prueba o ciudadanía digital"
    elif "EN02" in code:
        context = "una interacción comunicativa breve y comprensible en inglés"
    else:
        context = "un aprendizaje situado de lengua o cultura validado por fuente comunitaria pertinente"
    lessons = []
    for phase, _ in item["phases"]:
        lessons.append({
            "title": f"{phase}: actitud en acción",
            "purpose": f"Integrar «{text}» dentro de {context}, sin aislarla ni convertirla en etiqueta personal o cultural.",
            "goal": "Hoy mostraré una decisión concreta y explicaré cómo ayudó a aprender con otros.",
            "opening": "Contrasta una respuesta que sólo nombra la actitud con otra que muestra una acción disciplinar observable; el curso localiza la diferencia.",
            "model": f"Modela una decisión dentro de {context}, explica su efecto y nombra los límites de seguridad, autoría, privacidad o pertinencia cultural.",
            "guided": "Realizan una tarea breve, marcan la acción observable y reciben retroalimentación sobre la decisión, nunca sobre capacidad, identidad, acento, origen o personalidad.",
            "independent": f"Cada estudiante completa una versión nueva de {context}, identifica su decisión y explica cómo la actitud influyó.",
            "ticket": "Muestra una evidencia propia y completa: esta acción ayudó porque…",
            "materials": "Materiales del OA anfitrión y una tarjeta con la actitud expresada como acción observable.",
            "support": "Ofrece ejemplos contrastados y vías oral, gráfica, corporal o digital equivalentes; conserva la intención disciplinar y los resguardos.",
            "extension": "Transfiere la actitud a otro OA y compara cómo cambia su manifestación concreta.",
            "evidence": "Producción disciplinar con una acción localizada y explicación atribuible al estudiante.",
            "criteria": ["resuelve contenido pertinente", "hace visible la actitud mediante una acción", "explica su efecto respetando seguridad, autoría y contexto"],
            "next_step": "Integra nuevamente si depende del apoyo; diversifica el contexto cuando aparece con autonomía.",
            "short_version": "Conserva tarea, decisión observable, evidencia individual y cierre; elimina repetición, no la integración.",
            "home_task": "Explica o dibuja un ejemplo seguro de la actitud; no requiere internet, compras, datos personales ni exposición cultural.",
            "complementary": ["Clasificar evidencia y no evidencia.", "Corregir un caso que confunde actitud con obediencia o identidad.", "Transferir a otro eje."],
            "difficulty_actions": [
                {"signal": "Nombra la actitud, pero no la aplica", "action": "Pide señalar una decisión concreta.", "check": "La acción queda localizada en la producción."},
                {"signal": "Se evalúa personalidad, identidad o acento", "action": "Reformula como acción modificable y disciplinar.", "check": "La retroalimentación no contiene etiquetas personales."},
                {"signal": "La actitud desplaza el OA", "action": "Recupera la tarea anfitriona y usa la actitud como medio.", "check": "El ticket demuestra ambos componentes."},
            ],
            "specialist_coordination": "El docente conserva el OA; profesionales de apoyo y, en Lengua y Cultura, educador tradicional o fuente comunitaria pertinente, acuerdan acceso, resguardo y evidencia.",
        })
    return {"generated_for": "2-basico", "lessons": lessons}
